build.sbt, client/tests/src/main/scala/tapir/client/tests/ClientTests.scala, server/http4s-server/src/main/scala/tapir/server/http4s/Http4sServer.scala, server/http4s-server/src/main/scala/tapir/server/http4s/package.scala, server/http4s-server/src/test/scala/tapir/server/http4s/Http4sServerTests.scala
This is just a first stab -- nothing is optimized and the code is not perfect.
It also bumps Http4s version to 0.20.0-M4 with minor changes to ClientTests. 
Looking forward to review comments! (note, it's Christmas so I'll not be responding quickly)
=> Adds Http4s server interpreter 

core/src/main/scala/tapir/Endpoint.scala, core/src/main/scala/tapir/StatusCodes.scala, core/src/main/scala/tapir/internal/DefaultStatusMappers.scala, core/src/main/scala/tapir/package.scala, server/akka-http-server/src/main/scala/tapir/server/akkahttp/AkkaHttpServer.scala, server/akka-http-server/src/main/scala/tapir/server/akkahttp/EndpointToAkkaServer.scala, server/akka-http-server/src/test/scala/tapir/server/akkahttp/AkkaHttpServerTests.scala, server/http4s-server/src/main/scala/tapir/server/http4s/EndpointToHttp4sServer.scala, server/http4s-server/src/main/scala/tapir/server/http4s/Http4sServer.scala, server/http4s-server/src/test/scala/tapir/server/http4s/Http4sServerTests.scala, server/tests/src/main/scala/tapir/server/tests/ServerTests.scala, tests/src/main/scala/tapir/tests/package.scala
=> Add support for multiple response status codes - 2

docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOpenAPIDocs.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOpenApiPaths.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/OpenAPIDocs.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/OpenAPIDocsOptions.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/OpenApiDocsOptions.scala, docs/openapi-docs/src/test/resources/expected_custom_operation_id.yml, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala
=> Openapi operationid

docs/openapi-docs/src/test/resources/expected_tags.yml, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala
=> Add test that verifies tags support

core/src/main/scala/tapir/generic/SchemaForMagnoliaDerivation.scala, core/src/test/scala/tapir/generic/SchemaForTest.scala
This pull request is intended to solve https://github.com/softwaremill/tapir/issues/71.
=> WIP: Unwrap value classes

docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOpenAPIDocs.scala, openapi/openapi-circe/src/main/scala/tapir/openapi/circe/package.scala, openapi/openapi-model/src/main/scala/tapir/openapi/OpenAPI.scala
Spec: https://swagger.io/specification/#tagObject
Implements https://github.com/softwaremill/tapir/issues/73
=> Add global tag section

docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/ObjectSchemasForEndpoints.scala, docs/openapi-docs/src/test/resources/expected_unfolded_coproduct_unfolded_array.yml, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala
Hello,
The current code was failing to generate a proper schemas for Sequence of coproduct.
For once, the fix was to delete code :)
Regards,
Fabien
=> Properly handle arrays of coproduct in openApi encoding

core/src/main/scala/tapir/Tapir.scala
=> Use hostAddress for client IP

doc/faq.md, doc/index.md
=> Add FAQ for ClassClassException caused by missing ParamAsArgs instance

core/src/main/scala/tapir/Codec.scala, core/src/main/scala/tapir/MediaType.scala, core/src/main/scala/tapir/Tapir.scala
project core is compiling successfully
=> added "text/html" support in utf-8

core/src/main/scala/tapir/Endpoint.scala, docs/openapi-docs/src/test/resources/expected_prepended_input.yml, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala
=> Add support for prepending inputs

client/sttp-client/src/main/scala/tapir/client/sttp/EndpointToSttpClient.scala, client/sttp-client/src/test/scala/tapir/client/sttp/SttpClientTests.scala, client/tests/src/main/scala/tapir/client/tests/ClientTests.scala, core/src/main/scala/tapir/EndpointIO.scala, core/src/main/scala/tapir/Tapir.scala, core/src/main/scala/tapir/internal/package.scala, core/src/main/scala/tapir/internal/server/DecodeInputs.scala, core/src/main/scala/tapir/internal/server/EncodeOutputs.scala, core/src/main/scala/tapir/internal/server/InputValues.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointInputToParameterConverter.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOpenApiPaths.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOperationResponse.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/ObjectSchemasForEndpoints.scala, docs/openapi-docs/src/test/resources/expected_fixed_header_input_request.yml, docs/openapi-docs/src/test/resources/expected_fixed_header_output_response.yml, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala, server/tests/src/main/scala/tapir/server/tests/ServerTests.scala, tests/src/main/scala/tapir/tests/package.scala
=> Add fixed headers

core/src/main/scala/tapir/Schema.scala, core/src/main/scala/tapir/SchemaFor.scala, core/src/main/scala/tapir/generic/SchemaForMapMacro.scala, core/src/test/scala/tapir/generic/SchemaForTest.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/ObjectSchemasForEndpoints.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/TSchemaToOSchema.scala, docs/openapi-docs/src/test/resources/expected_additional_properties.yml, docs/openapi-docs/src/test/resources/expected_map_with_plain_values.yml, docs/openapi-docs/src/test/resources/expected_ordinary_map.yml, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala, openapi/openapi-model/src/main/scala/tapir/openapi/OpenAPI.scala
=> Additional properties

doc/mytapir.md
Is TapirJsonCirce and not TapirCirceJson
=> Typo inside the Json circe dependency

doc/server/debugging.md
Fix for broken link referring to server options
=> fix broken link

core/src/main/scala/tapir/Validator.scala, core/src/test/scala/tapir/ValidatorTest.scala
=> Add optimization to collection validators

core/src/main/scala/tapir/generic/Debug.scala, core/src/main/scala/tapir/generic/FormCodecDerivation.scala, core/src/main/scala/tapir/generic/MultipartCodecDerivation.scala, core/src/main/scala/tapir/generic/OneOfMacro.scala, core/src/main/scala/tapir/generic/SchemaForMapMacro.scala, core/src/main/scala/tapir/generic/ValidatorEnumMacro.scala, doc/quickstart.md
Added logging of generated macros code when env var TAPIR_LOG_GENERATED_CODE = true
=> Logging of generated macros code 

build.sbt, json/sprayjson/src/main/scala/sttp/tapir/json/spray/TapirJsonSpray.scala, json/sprayjson/src/main/scala/sttp/tapir/json/spray/package.scala, json/sprayjson/src/test/scala/sttp/tapir/json/spray/TapirJsonSprayTests.scala, project/Versions.scala
I am new Scala so I just took inspiration of play json support to propose this PR.
I removed test about date because spray does not support date serialization out of the box
=> add support for spray json

build.sbt, doc/server/finatra.md, server/finatra-cats-support/src/main/scala/sttp/tapir/server/finatra/cats/package.scala, server/finatra-cats-support/src/test/scala/sttp/tapir/server/finatra/cats/FinatraServerEffectTests.scala, server/finatra-server/src/main/scala/sttp/tapir/server/finatra/package.scala, server/finatra-server/src/test/scala/sttp/tapir/server/finatra/FinatraServerEffectTests.scala
+ moved cats-effect to a sub-project
+ revised tapir’s Finatra server document
=> [Finatra Server] cats-effect support (moved to a sub-project)

build.sbt, docs/swagger-ui-finatra/src/main/scala/sttp/tapir/swagger/finatra/SwaggerFinatra.scala
=> [Swagger Doc] Finatra support

docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/schema/ObjectSchemasForEndpoints.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/schema/SchemaReferenceMapper.scala, docs/openapi-docs/src/test/resources/expected_coproduct.yml, docs/openapi-docs/src/test/resources/expected_coproduct_discriminator.yml, docs/openapi-docs/src/test/resources/expected_coproduct_discriminator_nested.yml, docs/openapi-docs/src/test/resources/expected_coproduct_nested.yml, docs/openapi-docs/src/test/resources/expected_generic_coproduct.yml, docs/openapi-docs/src/test/resources/expected_unfolded_coproduct_unfolded_array.yml, openapi/openapi-model/src/main/scala/sttp/tapir/openapi/OpenAPI.scala
=> Add allOf support to openApi schemas

docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/CodecToMediaType.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/package.scala, docs/openapi-docs/src/test/resources/expected_multiple_and_single_example_values.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala, openapi/openapi-circe/src/main/scala/sttp/tapir/openapi/circe/package.scala, openapi/openapi-model/src/main/scala/sttp/tapir/openapi/OpenAPI.scala
=> Add support for multiple example values

core/src/main/scala/sttp/tapir/Validator.scala
Did not use the given message string
=> fixed a bug in Custom validator’s show function

build.sbt, project/Versions.scala
+ added a new dependency version variable for Catbird project
=> [Update] Upgraded Finatra version 19.11.0 → 19.12.0

core/src/main/scala/sttp/tapir/Endpoint.scala, core/src/test/scala/sttp/tapir/EndpointTest.scala
Hi, I think it's convenient method to have. My use case is for creating spans, but I think there may be other as well.
=> show HTTP method for an endpoint

core/src/main/scala/sttp/tapir/Endpoint.scala
Hi, I missed much simpler implemenation in https://github.com/softwaremill/tapir/pull/432. This is just a small cleanup
=> simplify httpMethod

core/src/main/scala/sttp/tapir/Codec.scala, core/src/test/scala/sttp/tapir/CodecTest.scala
=> Add Codec for sttp.mode.Uri

build.sbt, doc/endpoint/json.md, json/tethys/src/main/scala/sttp/tapir/json/circe/TapirJsonTethys.scala, json/tethys/src/main/scala/sttp/tapir/json/circe/package.scala, project/Versions.scala
Added support of https://tethys-json.github.io/tethys/
=> added support of tethys json

doc/endpoint/integrations.md
=> Enumeration added to docs

core/src/main/scala/sttp/tapir/monad/MonadError.scala, integrations/cats/src/main/scala/sttp/tapir/cats/ServerEndpointSyntax.scala, integrations/cats/src/main/scala/sttp/tapir/cats/syntax.scala, integrations/cats/src/main/scala/sttp/tapir/monad/cats/MonadErrorSyntax.scala, integrations/cats/src/main/scala/sttp/tapir/monad/cats/syntax.scala, server/finatra-server/finatra-server-cats/src/main/scala/sttp/tapir/server/finatra/cats/package.scala, server/finatra-server/src/main/scala/sttp/tapir/server/finatra/package.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/EndpointToHttp4sServer.scala, server/zio-http4-server/src/main/scala/sttp/tapir/server/http4s/ztapir/ZIOMonadError.scala
=> Remove handleWrappedError method from MonadError & adds imapK syntax for ServerEndpoint and MonadError

doc/endpoint/integrations.md, integrations/cats/src/main/scala/sttp/tapir/codec/cats/package.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/MonadErrorSyntax.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/ServerEndpointSyntax.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/TapirCodecCats.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/codec.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/syntax.scala, integrations/cats/src/main/scala/sttp/tapir/monad/cats/syntax.scala, integrations/cats/src/test/scala/sttp/tapir/integ/cats/TapirCodecCatsTest.scala
Reference https://github.com/softwaremill/tapir/issues/670
=> Move sttp.tapir.cats -> sttp.tapir.integ.cats to resolve cats conflict after importing sttp._

core/src/main/scala/sttp/tapir/CodecFormat.scala, server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/OutputToAkkaRoute.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/OutputToHttp4sResponse.scala
Requires changed sttp-model: https://github.com/softwaremill/sttp-model/pull/15
=> Add application/zip codec format

project/Versions.scala
Reverts softwaremill/tapir#685
=> Revert "Update zio-interop-cats to 2.1.4.0-RC17+1-307f2f6c-SNAPSHOT"

server/play-server/src/main/scala/sttp/tapir/server/play/TapirPlayServer.scala
This PR have been created to solve this bug
https://github.com/softwaremill/tapir/issues/700
=> Call requestHandled method once the request have been completed Play

examples/src/main/scala/sttp/tapir/examples/ZioPartialServerLogicHttp4s.scala, integrations/zio/src/main/scala/sttp/tapir/ztapir/ZPartialServerEndpoint.scala
=> Adds the option to enhance the environment of a ZPartialServerEndpoint

doc/endpoint/customtypes.md
I was going through the docs and saw a typo.
=> fixed a typo and some formatting

core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/generic/internal/SchemaMagnoliaDerivation.scala, core/src/test/scala/sttp/tapir/generic/SchemaGenericTest.scala, doc/endpoint/customtypes.md
Can we add annotation `@description` to fill descriptions of fields in `Schema`s?
=> Add description annotation

.github/workflows/test.yml
Due to very long waiting times on Travis. Nothing fancy like a build matrix yet but it's a start.
=> Add GitHub action for running tests

core/src/main/scala/sttp/tapir/annotations/domain.scala, core/src/main/scala/sttp/tapir/annotations/package.scala, core/src/main/scala/sttp/tapir/generic/internal/CaseClassUtil.scala, core/src/main/scala/sttp/tapir/generic/internal/EndpointInputAnnotations.scala, core/src/main/scala/sttp/tapir/generic/internal/FormCodecDerivation.scala, core/src/main/scala/sttp/tapir/generic/internal/MultipartCodecDerivation.scala, core/src/test/scala/sttp/tapir/annotations/EndpointInputMacroTest.scala, doc/endpoint/ios.md
=> Annotations for endpoint inputs

core/src/main/scala/sttp/tapir/EndpointIO.scala, core/src/main/scala/sttp/tapir/TapirAuth.scala, core/src/main/scala/sttp/tapir/annotations/domain.scala, core/src/main/scala/sttp/tapir/generic/internal/EndpointAnnotations.scala, core/src/main/scala/sttp/tapir/generic/internal/EndpointInputAnnotations.scala, core/src/test/scala/sttp/tapir/annotations/EndpointIOMacroTest.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/SecuritySchemesForEndpoints.scala, docs/openapi-docs/src/test/resources/expected_auth_with_named_schemes.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala
Implementation for https://github.com/softwaremill/tapir/issues/849
=> Allow to specify name of security scheme in api docs

apispec/apispec-model/src/main/scala/sttp/tapir/apispec/Schema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/openapi-docs/src/test/resources/expected_exclusive_bounds.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala
=> Fix rendering exclusive bounds in OpenAPI

examples/src/main/scala/sttp/tapir/examples/BooksExample.scala, examples/src/main/scala/sttp/tapir/examples/BooksExampleSemiauto.scala, playground/src/main/scala/sttp/tapir/example/BooksExample.scala
Now minimal example of creating an http client doesn't involve HKTs
=> Simplify BookExample

core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/generic/internal/SchemaMagnoliaDerivation.scala, core/src/test/scala/sttp/tapir/generic/SchemaGenericAutoTest.scala
```scala
case class I(
@validate[Int](Validator.max(100))
int: Int
)
```
=> validate annotation

build.sbt
=> Remove logback dependency from sttp-client module

server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala
Removes global execution contexts from play server interpreter
Uses execution contexts from akka stream materializer
=> Remove global execution context from play server interpreter

server/vertx/src/main/scala/sttp/tapir/server/vertx/encoders/VertxOutputEncoders.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/interpreters/VertxCatsServerInterpreter.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/streams/Pipe.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/streams/fs2.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/streams/zio.scala
I found several problems in code which converts vertx's stream to zstream/fs2 streams. It seems I fixed all of them. At least my stress tests don't show any errors now.
=> Fix streaming from vertx streams

docs/redoc-http4s/src/main/scala/sttp/tapir/redoc/http4s/RedocHttp4s.scala
Hi,
Tiny improvement allowing to specify a sub-path for Redoc Http4s documentation handler.
I took care about backward compatibility.
=> Add contextPath capability to RedocHttp4s handler

core/src/main/scala/sttp/tapir/Schema.scala, doc/endpoint/customtypes.md
Resolves https://github.com/softwaremill/tapir/issues/1058
=> Schema not found - improvements

generated-doc/out/endpoint/json.md
Added summary for a few missing implementations, and fixed the Json4s module id.
=> Fix some JSON doc

apispec/asyncapi-circe/src/main/scala/sttp/tapir/asyncapi/circe/package.scala, apispec/asyncapi-model/src/main/scala/sttp/tapir/asyncapi/AsyncAPI.scala, core/src/main/scala/sttp/tapir/EndpointIO.scala, doc/docs/asyncapi.md, doc/docs/openapi.md, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/AsyncAPIInterpreter.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/DocsExtensions.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/EndpointToAsyncAPIDocs.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/EndpointToAsyncAPIWebSocketChannel.scala, docs/asyncapi-docs/src/test/resources/expected_extensions.yml, docs/asyncapi-docs/src/test/scala/sttp/tapir/docs/asyncapi/VerifyAsyncAPIYamlTest.scala
AsyncAPI extensions (https://www.asyncapi.com/docs/specifications/2.0.0#specificationExtensions)
=> Asyncapi extensions

server/vertx/src/test/scala/sttp/tapir/server/vertx/streams/Fs2StreamTest.scala
Sorry, it took long time.
It seems that that test doesn't fail anymore. At least I ran tests 5 or 6 times in CI.
Please let me know if some test fails again.
=> Fix test issue #1169

docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOperationResponse.scala, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/EndpointToOpenAPIDocsTest.scala
=> Fixes oneOf with empty body openapi spec generation

project/Versions.scala
Reverts softwaremill/tapir#1289
=> Revert "Update catbird-effect, catbird-finagle to 21.5.0"

apispec/apispec-model/src/main/scala/sttp/tapir/apispec/Schema.scala, apispec/apispec-model/src/main/scala/sttp/tapir/apispec/model.scala, apispec/asyncapi-circe/src/main/scala/sttp/tapir/asyncapi/circe/package.scala, apispec/openapi-circe/src/main/scala/sttp/tapir/openapi/circe/package.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/package.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/openapi-docs/src/test/resources/enum/expected_enumeratum_int_enum_component.yml, docs/openapi-docs/src/test/resources/validator/expected_valid_enum_values.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala
=> Use proper types in openapi docs for example and enum values

core/src/main/scala/sttp/tapir/EndpointIO.scala, core/src/main/scala/sttp/tapir/RenderPathTemplate.scala, core/src/main/scalajs/sttp/tapir/internal/UrlencodedData.scala, core/src/main/scalajvm/sttp/tapir/internal/UrlencodedData.scala, core/src/test/scala/sttp/tapir/EndpointTest.scala
=> Use URLEncoder.encode() for paths rendering

docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/EndpointToAsyncAPIComponents.scala, docs/asyncapi-docs/src/test/resources/expected_string.yml, docs/asyncapi-docs/src/test/scala/sttp/tapir/docs/asyncapi/VerifyAsyncAPIYamlTest.scala
=> Missing components for AsyncAPI

core/src/main/scala-2/sttp/tapir/internal/CaseClassUtil.scala, core/src/test/scala/sttp/tapir/EndpointTest.scala
=> Fix instanceFromValues for case class with defined companion object

core/src/main/scala-3/sttp/tapir/internal/SchemaMagnoliaDerivation.scala
=> schema derivation cannot be checked at runtime

server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala
=> Added filtering of implicit headers for Play

server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerTest.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerWithContextTest.scala
=> Fix play server interpreter when routes are put in context

core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/Validator.scala, core/src/main/scala/sttp/tapir/internal/package.scala, doc/endpoint/validation.md, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/openapi-docs/src/test/resources/validator/expected_validator_encode_from_codec.yml, docs/openapi-docs/src/test/resources/validator/expected_validator_infer_encode_to_raw.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlValidatorTest.scala
=> Improve ergonomics of encode-to-raw function for validators, inferring when possible and providing methods to specify using in-scope codecs

build.sbt, doc/index.md, doc/server/zio-http4s.md, examples/src/main/scala/sttp/tapir/examples/ZioExampleZioHttpServer.scala, integrations/zio/src/main/scala/sttp/tapir/ztapir/ZTapir.scala, integrations/zio/src/main/scala/sttp/tapir/ztapir/ZioServerSentEvents.scala, integrations/zio/src/test/scala/sttp/tapir/ztapir/ZTapirTest.scala, integrations/zio/src/test/scala/sttp/tapir/ztapir/ZioServerSentEventsTest.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sServerSentEvents.scala, server/zio-http4s-server/src/main/scala/sttp/tapir/server/http4s/ztapir/ConvertStreams.scala, server/zio-http4s-server/src/main/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sServerInterpreter.scala, server/zio-http4s-server/src/main/scala/sttp/tapir/server/http4s/ztapir/package.scala, server/zio-http4s-server/src/test/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sServerTest.scala, server/zio-http4s-server/src/test/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sTestServerInterpreter.scala
=> Support streaming & websockets in the zio-http4s interpreter

core/src/main/scala-2/sttp/tapir/generic/internal/SchemaMapMacro.scala, core/src/main/scala-2/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/test/scala/sttp/tapir/SchemaMacroTest.scala
=> Derive schemas for arbitrary maps

core/src/main/scala/sttp/tapir/Codec.scala, core/src/main/scala/sttp/tapir/Schema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/openapi-docs/src/test/resources/validator/expected_whole_numbers_in_examples_of_string_schemas.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlValidatorTest.scala
=> Improve inference of whole numbers when generating docs

build.sbt, doc/docs/openapi.md, docs/redoc-zio-http/src/main/scala/sttp.tapir.redoc.ziohttp/RedocZioHttp.scala
This PR adds`zio-http` Redoc support.
=> Add zio-http redoc support

build.sbt, json/zio/src/test/scalajvm/sttp/tapir/json/zio/TapirJsonZioTest.scala, project/Versions.scala
=> #1448 bump zio-json to 0.2.0-M1

core/src/main/scala-2/sttp/tapir/internal/CodecEnumerationMacro.scala, core/src/main/scala-2/sttp/tapir/internal/SchemaEnumerationMacro.scala, core/src/main/scala-2/sttp/tapir/macros/CodecMacros.scala, core/src/main/scala-2/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala-3/sttp/tapir/macros/CodecMacros.scala, core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala/sttp/tapir/Codec.scala, doc/endpoint/validation.md, docs/openapi-docs/src/test/scala-2/sttp/tapir/docs/openapi/VerifyYamlEnumerationTest.scala, tests/src/main/scala/sttp/tapir/tests/package.scala
=> More convenient derived enumeration schema & codec creation

server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sBodyListener.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sServerToHttpInterpreter.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sToResponseBody.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/package.scala
=> Explicitly set the content length in http4s, as Ember doesn't do that automatically

server/tests/src/main/scala/sttp/tapir/server/tests/CreateServerTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpCompositionTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala
=> Adjust behavior on decode failure to native zio HttpApps

doc/server/play.md, server/play-server/src/main/scala/sttp/tapir/server/play/PlayBodyListener.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayToResponseBody.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayWebSockets.scala, server/play-server/src/main/scala/sttp/tapir/server/play/package.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerTest.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayTestServerInterpreter.scala
I'm pretty new to tapir, hopefully it makes sense 😄
=> Add WebSocket support for Play

core/src/main/scala/sttp/tapir/RenderPathTemplate.scala, core/src/main/scalajs/sttp/tapir/internal/UrlencodedData.scala, core/src/main/scalajvm/sttp/tapir/internal/UrlencodedData.scala, core/src/test/scala/sttp/tapir/EndpointTest.scala
=> Fix OpenApi path encoding

core/src/main/scala-2/sttp/tapir/internal/OneOfVariantMacro.scala, core/src/main/scala-2/sttp/tapir/macros/TapirMacros.scala, core/src/main/scala-3/sttp/tapir/macros/TapirMacros.scala, core/src/main/scala/sttp/tapir/Endpoint.scala, core/src/main/scala/sttp/tapir/EndpointIO.scala, core/src/main/scala/sttp/tapir/Tapir.scala, core/src/main/scala/sttp/tapir/client/ClientOutputParams.scala, core/src/main/scala/sttp/tapir/internal/package.scala, core/src/main/scala/sttp/tapir/server/PartialServerEndpoint.scala, core/src/main/scala/sttp/tapir/server/interpreter/EncodeOutputs.scala, core/src/main/scalajvm/sttp/tapir/static/TapirStaticContentEndpoints.scala, core/src/test/scala/sttp/tapir/EndpointTest.scala, doc/endpoint/basics.md, doc/endpoint/contenttype.md, doc/endpoint/oneof.md, doc/server/logic.md, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlDecodeFailureOutputTest.scala, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlOneOfTest.scala, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerOneOfTests.scala, server/zio-http4s-server/src/main/scala/sttp/tapir/server/http4s/ztapir/ConvertStreams.scala, tests/src/main/scala/sttp/tapir/tests/Basic.scala, tests/src/main/scala/sttp/tapir/tests/ContentNegotiation.scala, tests/src/main/scala/sttp/tapir/tests/OneOf.scala
Implements the last part, and closes https://github.com/softwaremill/tapir/issues/1167
=> Add .errorOutVariant, rename oneOfMapping to oneOfVariant

server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sServerToHttpInterpreter.scala
=> Fix http4s WebSocket headers

core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureHandler.scala, core/src/test/scala/sttp/tapir/server/interceptor/decodefailure/DefaultDecodeFailureHandlerTest.scala
=> Encode possible values when reporting an enumeraton error in the DefaultDecodeFailureHandler

core/src/main/scala/sttp/tapir/server/interceptor/CustomInterceptors.scala, core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLog.scala, core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLogInterceptor.scala, server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaHttpServerOptions.scala, server/finatra-server/finatra-server-cats/src/main/scala/sttp/tapir/server/finatra/cats/FinatraCatsServerOptions.scala, server/finatra-server/src/main/scala/sttp/tapir/server/finatra/FinatraServerOptions.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sServerOptions.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyCatsServerOptions.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyFutureServerOptions.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxCatsServerOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxFutureServerOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxServerOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxZioServerOptions.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerOptions.scala, serverless/aws/lambda/src/main/scala/sttp/tapir/serverless/aws/lambda/AwsCatsEffectServerOptions.scala, serverless/aws/lambda/src/main/scala/sttp/tapir/serverless/aws/lambda/AwsFutureServerOptions.scala
=> ServerLog refactoring

core/src/main/scala/sttp/tapir/server/interpreter/DecodeBasicInputs.scala, core/src/main/scala/sttp/tapir/server/interpreter/ServerInterpreter.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala
=> Properly handle decode failures of both regular & security inputs

server/tests/src/main/scala/sttp/tapir/server/tests/ServerContentNegotiationTests.scala, tests/src/main/scala/sttp/tapir/tests/ContentNegotiation.scala
=> Default content type tests

build.sbt, docs/swagger-ui-bundle/src/main/scala/sttp/tapir/swagger/bundle/SwaggerInterpreter.scala, docs/swagger-ui-bundle/src/test/scala/sttp/tapir/swagger/bundle/SwaggerInterpreterTest.scala, docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUI.scala
=> Add SwaggerUI.basePath

integrations/zio/src/main/scala/sttp/tapir/ztapir/ZPartialServerEndpoint.scala
=> Added ability to map error types with zio

core/src/main/scala/sttp/tapir/server/ServerEndpoint.scala, core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLog.scala, server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaHttpServerOptions.scala, server/finatra-server/src/main/scala/sttp/tapir/server/finatra/FinatraServerOptions.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sServerOptions.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyCatsServerOptions.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyFutureServerOptions.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxCatsServerOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxFutureServerOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxZioServerOptions.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerOptions.scala, serverless/aws/lambda/src/main/scala/sttp/tapir/serverless/aws/lambda/AwsCatsEffectServerOptions.scala, serverless/aws/lambda/src/main/scala/sttp/tapir/serverless/aws/lambda/AwsFutureServerOptions.scala
=> Remove the requirement in DefaultServerLog for a MonadError, pass a "no log" value instead

server/sttp-stub-server/src/main/scala/sttp/tapir/server/stub/SttpStubServer.scala, server/sttp-stub-server/src/test/scala/sttp/tapir/server/stub/SttpStubServerTest.scala
=> Allow stub sttp server to interpret request body

build.sbt, project/Versions.scala, project/build.properties
This is due to https://github.com/coursier/coursier/issues/2016
=> Disable coursier for netty dependencies

core/src/main/scala/sttp/tapir/server/interpreter/DecodeBasicInputs.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, tests/src/main/scala/sttp/tapir/tests/Basic.scala
=> Match path exactly even if the path is only specified in the security inputs

build.sbt, core/src/main/scala-2/sttp/tapir/generic/internal/MagnoliaDerivedMacro.scala, core/src/main/scala-2/sttp/tapir/generic/internal/SchemaMagnoliaDerivation.scala, core/src/main/scala-2/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala-2/sttp/tapir/typelevel/MatchTypeMacros.scala, core/src/main/scala-2/sttp/tapir/typelevel/internal/MatchTypeMagnoliaDerivation.scala
=> Update magnolia to softwaremill's version

core/src/main/scala/sttp/tapir/Tapir.scala, docs/swagger-ui-bundle/src/test/scala/sttp/tapir/swagger/bundle/SwaggerInterpreterTest.scala, docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUI.scala
=> Modify the index.html for Swagger UI so that it references the docs yaml directly

server/play-server/src/main/scala/sttp/tapir/server/play/PlayRequestBody.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerMultipartTests.scala
When the play server receives an unknown part and the and no default codec is defined for the input parts a `None.get` exception was thrown.
Here the part is discarded (and temporary files are cleaned up)
=> Play Server: don't fail on unknown part in multipart body

build.sbt, doc/server/http4s.md, doc/server/zio-http4s.md
=> Removing http4s-blaze-server as a direct dependency.

core/src/main/scala/sttp/tapir/Tapir.scala, docs/swagger-ui-bundle/src/test/scala/sttp/tapir/swagger/bundle/SwaggerInterpreterTest.scala, docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUI.scala
This PR backports [this patch](https://github.com/softwaremill/tapir/commit/2a782024f1bcac3cfd3e60c5bfe2d59f29a60a07) to 0.19.x series
=> Backport patch for swagger ui vulnerability

core/src/main/scala/sttp/tapir/metrics/Metric.scala, core/src/main/scala/sttp/tapir/model/ServerResponse.scala, core/src/main/scala/sttp/tapir/server/interceptor/EndpointHandler.scala, core/src/main/scala/sttp/tapir/server/interceptor/Interceptor.scala, core/src/main/scala/sttp/tapir/server/interceptor/ServerResponseFromOutput.scala, core/src/main/scala/sttp/tapir/server/interceptor/ValuedEndpointOutput.scala, core/src/main/scala/sttp/tapir/server/interceptor/content/UnsupportedMediaTypeInterceptor.scala, core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureInterceptor.scala, core/src/main/scala/sttp/tapir/server/interceptor/exception/ExceptionInterceptor.scala, core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLog.scala, core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLogInterceptor.scala, core/src/main/scala/sttp/tapir/server/interceptor/metrics/MetricsEndpointInterceptor.scala, core/src/main/scala/sttp/tapir/server/interpreter/ServerInterpreter.scala, core/src/test/scala/sttp/tapir/server/interpreter/ServerInterpreterTest.scala, integrations/zio/src/test/scala/sttp/tapir/ztapir/ZTapirTest.scala, integrations/zio1/src/test/scala/sttp/tapir/ztapir/ZTapirTest.scala, metrics/opentelemetry-metrics/src/main/scala/sttp/tapir/metrics/opentelemetry/OpenTelemetryMetrics.scala, server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaHttpServerOptions.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerHandler.scala, server/sttp-stub-server/src/main/scala/sttp/tapir/server/stub/StubServerInterpreter.scala
=> Make the source of a server response available for interceptors

apispec/openapi-circe/src/main/scala/sttp/tapir/openapi/circe/package.scala, apispec/openapi-model/src/main/scala/sttp/tapir/openapi/OpenAPI.scala, core/src/main/scala/sttp/tapir/EndpointIO.scala, core/src/main/scala/sttp/tapir/model/StatusCodeRange.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOperationResponse.scala, docs/openapi-docs/src/test/resources/oneOf/expected_one_of_status_code_range.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlOneOfTest.scala
=> Possibility to document status code ranges in dynamic statuc code outputs

core/src/main/scala-2/sttp/tapir/generic/internal/OneOfMacro.scala, core/src/main/scala-2/sttp/tapir/generic/internal/SchemaMagnoliaDerivation.scala, core/src/main/scala-3/sttp/tapir/internal/SchemaMagnoliaDerivation.scala, core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/SchemaType.scala, core/src/test/scala-2/sttp/tapir/LegacySchemaApplyValidationTest.scala, core/src/test/scala/sttp/tapir/SchemaApplyValidationTest.scala
=> Fix coproduct subtype schemas which are not direct subtypes of the main type

core/src/main/scalajvm/sttp/tapir/static/Resources.scala, docs/swagger-ui-bundle/src/test/scala/sttp/tapir/swagger/bundle/SwaggerInterpreterTest.scala
=> Change the way a sanity check when reading static resource is done

core/src/main/scala-2/sttp/tapir/generic/internal/OneOfMacro.scala, core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/test/scala/sttp/tapir/SchemaApplyValidationTest.scala
=> Use proper subtype values when creating coproduct schemas using oneOfUsingField

core/src/main/scala-2/sttp/tapir/generic/internal/OneOfMacro.scala, core/src/main/scala-2/sttp/tapir/internal/SchemaEnumerationMacro.scala, core/src/test/scala-2/sttp/tapir/generic/LegacySchemaGenericAutoTest.scala, core/src/test/scala/sttp/tapir/SchemaMacroTest.scala, examples/src/main/scala/sttp/tapir/examples/CustomErrorsOnDecodeFailureAkkaServer.scala, examples/src/main/scala/sttp/tapir/examples/ServerSecurityLogicAkka.scala, examples/src/main/scala/sttp/tapir/examples/WebSocketAkkaServer.scala
=> Fix oneOfSchema generation using an enum extractor

server/core/src/main/scala/sttp/tapir/server/interceptor/DecodeFailureContext.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/DecodeSuccessContext.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/EndpointHandler.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/content/UnsupportedMediaTypeInterceptor.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureInterceptor.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/exception/ExceptionInterceptor.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/log/ExceptionContext.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLog.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLogInterceptor.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/metrics/MetricsEndpointInterceptor.scala, server/core/src/main/scala/sttp/tapir/server/interpreter/ServerInterpreter.scala, server/core/src/test/scala/sttp/tapir/server/interpreter/DecodeBasicInputsTest.scala, server/core/src/test/scala/sttp/tapir/server/interpreter/ServerInterpreterTest.scala, server/finatra-server/finatra-server-cats/src/main/scala/sttp/tapir/server/finatra/cats/FinatraCatsServerInterpreter.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala
=> Add more metadata to interceptors

server/core/src/main/scala/sttp/tapir/server/interceptor/CustomInterceptors.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/reject/RejectHandler.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/reject/RejectInterceptor.scala, server/core/src/test/scala/sttp/tapir/server/interpreter/ServerInterpreterTest.scala, server/sttp-stub-server/src/test/scala/sttp/tapir/server/stub/TapirStubInterpreterTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerRejectTests.scala
Follow up for https://github.com/softwaremill/tapir/pull/2001 - making RejectHandler effectful
=> make reject handler effectful

server/akka-http-server/src/test/scala/sttp/tapir/server/akkahttp/AkkaHttpServerTest.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sWebSockets.scala, server/http4s-server/src/test/scala/sttp/tapir/server/http4s/Http4sServerTest.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerWebSocketTests.scala, server/zio-http4s-server/src/test/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sServerTest.scala, server/zio1-http4s-server/src/test/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sServerTest.scala
=> Close the server web socket when the stream ends

build.sbt, docs/redoc-bundle/src/main/scala/sttp/tapir/redoc/bundle/RedocInterpreter.scala, docs/redoc-bundle/src/test/scala/sttp/tapir/redoc/bundle/RedocInterpreterTest.scala, docs/redoc/src/main/scala/sttp/tapir/redoc/Redoc.scala, docs/redoc/src/main/scala/sttp/tapir/redoc/RedocUIOptions.scala, examples/src/main/scala/sttp/tapir/examples/RedocContextPathHttp4sServer.scala, examples/src/main/scala/sttp/tapir/examples/RedocZioHttpServer.scala
Related with issues: 
closes https://github.com/softwaremill/tapir/issues/1916
=> Added context path to RedocInterpreter

docs/redoc-bundle/src/test/scala/sttp/tapir/redoc/bundle/RedocInterpreterTest.scala, docs/redoc/src/main/scala/sttp/tapir/redoc/Redoc.scala, docs/swagger-ui-bundle/src/test/scala/sttp/tapir/swagger/bundle/SwaggerInterpreterTest.scala, docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUI.scala
=> Provide doc endpoint available from root.

docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUI.scala, examples/src/main/scala/sttp/tapir/examples/SwaggerUIOauth2AkkaServer.scala
closes https://github.com/softwaremill/tapir/issues/1894
=> Fix for Swagger oauth2-redirect.html resource.

client/core/src/main/scala/sttp/tapir/client/ClientOutputParams.scala, client/http4s-client/src/main/scala/sttp/tapir/client/http4s/EndpointToHttp4sClient.scala, client/play-client/src/main/scala/sttp/tapir/client/play/EndpointToPlayClient.scala, client/sttp-client/src/main/scala/sttp/tapir/client/sttp/EndpointToSttpClient.scala, client/tests/src/main/scala/sttp/tapir/client/tests/ClientStreamingTests.scala, core/src/main/scala/sttp/tapir/EndpointIO.scala, core/src/main/scala/sttp/tapir/Tapir.scala, core/src/main/scala/sttp/tapir/internal/package.scala, doc/endpoint/oneof.md, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/SecurityRequirementsForEndpoints.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/SchemasForEndpoints.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointInputToDecodeFailureOutput.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOpenAPIPaths.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOperationResponse.scala, server/core/src/main/scala/sttp/tapir/server/interpreter/EncodeOutputs.scala, server/core/src/main/scala/sttp/tapir/server/interpreter/ServerInterpreter.scala, server/sttp-stub-server/src/main/scala/sttp/tapir/server/stub/SttpRequestDecoder.scala, server/sttp-stub-server/src/main/scala/sttp/tapir/server/stub/SttpResponseEncoder.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerStreamingTests.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/handlers/package.scala, server/zio-http4s-server/src/main/scala/sttp/tapir/server/http4s/ztapir/ConvertStreams.scala, server/zio1-http4s-server/src/main/scala/sttp/tapir/server/http4s/ztapir/ConvertStreams.scala, tests/src/main/scala/sttp/tapir/tests/Streaming.scala
=> Allow using streaming bodies in oneOf

core/src/main/scala/sttp/tapir/EndpointIO.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/SecuritySchemesForEndpoints.scala, docs/openapi-docs/src/test/resources/security/expected_auth_with_bearer_format.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlSecurityTest.scala
=> Support for defining optional bearerFormat.

core/src/main/scala/sttp/tapir/Validator.scala
Hi!
https://github.com/lampepfl/dotty/issues/12226 seems to be fixed so I thought to clean that up a little bit ;)
It's my first commit so please let me know if something is wrong.
=> Validator: convert to patterns

core/src/main/scala/sttp/tapir/Codec.scala, doc/endpoint/ios.md, json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala, json/json4s/src/main/scala/sttp/tapir/json/json4s/TapirJson4s.scala, json/jsoniter/src/main/scala/sttp/tapir/json/jsoniter/TapirJsonJsoniter.scala, json/playjson/src/main/scala/sttp/tapir/json/play/TapirJsonPlay.scala, json/sprayjson/src/main/scala/sttp/tapir/json/spray/TapirJsonSpray.scala, json/tethys/src/main/scala/sttp/tapir/json/circe/TapirJsonTethys.scala, json/upickle/src/main/scala/sttp/tapir/json/upickle/TapirJsonuPickle.scala, json/zio/src/main/scala/sttp/tapir/json/zio/TapirJsonZio.scala, json/zio1/src/main/scala/sttp/tapir/json/zio/TapirJsonZio.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, tests/src/main/scala/sttp/tapir/tests/Basic.scala
=> Add Codec.tupledWithRaw and jsonBodyWithRaw body descriptions

core/src/main/scala-2/sttp/tapir/internal/OneOfMacro.scala, core/src/main/scala-2/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala/sttp/tapir/SchemaType.scala, core/src/test/scala/sttp/tapir/SchemaMacroTest.scala, core/src/test/scala/sttp/tapir/SchemaTest.scala
=> Add the discriminator as a field when using oneOfUsingField

core/src/main/scala-2/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala-2/sttp/tapir/internal/SchemaAnnotationsMacro.scala, core/src/main/scala-3/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala-3/sttp/tapir/internal/SchemaAnnotationsMacro.scala, core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/SchemaAnnotations.scala, core/src/test/scala/sttp/tapir/SchemaAnnotationsTest.scala, core/src/test/scala/sttp/tapir/SchemaAnnotationsTestData.scala, core/src/test/scala/sttp/tapir/SchemaMacroTest.scala, core/src/test/scala/sttp/tapir/SchemaMacroTestData.scala, core/src/test/scala/sttp/tapir/generic/SchemaGenericAutoTest.scala, doc/endpoint/schemas.md
=> Add a validateEach annotation

core/src/main/scala/sttp/tapir/Schema.scala, core/src/test/scala/sttp/tapir/generic/SchemaGenericAutoTest.scala, docs/openapi-docs/src/test/resources/validator/expected_whole_numbers_in_examples_of_string_schemas.yml, json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala, json/circe/src/test/scalajvm/sttp/tapir/json/circe/TapirJsonCirceTests.scala, json/zio/src/main/scala/sttp/tapir/json/zio/TapirJsonZio.scala, json/zio/src/test/scalajvm/sttp/tapir/json/zio/TapirJsonZioTest.scala, json/zio1/src/main/scala/sttp/tapir/json/zio/TapirJsonZio.scala, json/zio1/src/test/scalajvm/sttp/tapir/json/zio/TapirJsonZioTest.scala
=> Change the schema of BigDecimal to number and BigInteger to integer

client/http4s-client/src/main/scala/sttp/tapir/client/http4s/EndpointToHttp4sClient.scala, client/play-client/src/main/scala/sttp/tapir/client/play/EndpointToPlayClient.scala, client/sttp-client/src/main/scala/sttp/tapir/client/sttp/EndpointToSttpClient.scala, client/sttp-client/src/test/scala/sttp/tapir/client/sttp/SttpClientRequestTests.scala, core/src/main/scala/sttp/tapir/EndpointIO.scala, core/src/main/scala/sttp/tapir/Tapir.scala, core/src/test/scala/sttp/tapir/annotations/DeriveEndpointIOTest.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/SecuritySchemesForEndpoints.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/SchemasForEndpoints.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/EndpointToAsyncAPIWebSocketChannel.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointInputToDecodeFailureOutput.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointInputToParameterConverter.scala, docs/openapi-docs/src/test/resources/expected_flag_query.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala, examples/src/main/scala/sttp/tapir/examples/CustomErrorsOnDecodeFailureAkkaServer.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureHandler.scala, server/core/src/main/scala/sttp/tapir/server/interpreter/DecodeBasicInputs.scala, server/core/src/test/scala/sttp/tapir/server/interpreter/DecodeBasicInputsTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, tests/src/main/scala/sttp/tapir/tests/Basic.scala
=> Support flag query parameters

core/src/main/scala-2/sttp/tapir/internal/SchemaMapMacro.scala, core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/SchemaType.scala, core/src/test/scala-2/sttp/tapir/generic/LegacySchemaGenericAutoTest.scala, core/src/test/scala/sttp/tapir/SchemaMacroTest.scala, core/src/test/scala/sttp/tapir/SchemaTest.scala, core/src/test/scala/sttp/tapir/generic/SchemaGenericAutoTest.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/openapi-docs/src/test/resources/expected_fields_with_additional_properties.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala
=> Open product with non-open fields #1699

build.sbt, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpBodyListener.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpToResponseBody.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/package.scala, server/zio1-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpBodyListener.scala, server/zio1-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio1-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpToResponseBody.scala, server/zio1-http-server/src/main/scala/sttp/tapir/server/ziohttp/ziohttp.scala, serverless/aws/lambda/src/main/scala/sttp/tapir/serverless/aws/lambda/AwsBodyListener.scala, serverless/aws/lambda/src/main/scala/sttp/tapir/serverless/aws/lambda/AwsServerInterpreter.scala, serverless/aws/lambda/src/main/scala/sttp/tapir/serverless/aws/lambda/package.scala, serverless/aws/lambda/src/main/scalajs/sttp/tapir/serverless/aws/lambda/AwsToResponseBody.scala, serverless/aws/lambda/src/main/scalajvm/sttp/tapir/serverless/aws/lambda/AwsToResponseBody.scala
=> Properly set content-length header if known in the zio-http interpreter

docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlOneOfTest.scala
This should be straightforward. Though I'm new to tapir.
=> remove unneeded old workaround code

build.sbt, core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/SchemaType.scala, core/src/test/scala/sttp/tapir/SchemaSerialisationTest.scala, core/src/test/scalajvm/sttp/tapir/SchemaSerialisationTest.scala
=> Make schema serialisable

core/src/main/scala/sttp/tapir/Validator.scala, integrations/refined/src/main/scala/sttp/tapir/codec/refined/TapirCodecRefined.scala, server/zio1-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala
=> Allow validation to return multiple custom messages when the result is invalid

doc/endpoint/security.md
=> Fix sentence in security.md

server/core/src/main/scala/sttp/tapir/server/interpreter/EncodeOutputs.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerOneOfTests.scala, tests/src/main/scala/sttp/tapir/tests/OneOf.scala, tests/src/main/scala/sttp/tapir/tests/data/CustomError.scala
=> Fix one-of variants when a variant has no body

server/core/src/main/scala/sttp/tapir/server/interpreter/EncodeOutputs.scala, server/vertx-server/zio/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala, server/vertx-server/zio1/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala
=> Properly handle a failed fiber in vertx-zio, improve error messages

.github/workflows/ci.yml, .github/workflows/scala-steward.yml, .mergify.yml
=> fix mergify configuration

core/src/main/scala-3/sttp/tapir/internal/MappingMacros.scala
=> Improve macro code so that there are no warnings at usage site

client/core/src/main/scala/sttp/tapir/client/ClientOutputParams.scala, client/tests/src/main/scala/sttp/tapir/client/tests/ClientBasicTests.scala, client/testserver/src/main/scala/sttp/tapir/client/tests/HttpServer.scala, core/src/main/scala/sttp/tapir/Tapir.scala, core/src/main/scala/sttp/tapir/internal/package.scala, core/src/test/scala/sttp/tapir/internal/RichEndpointOutputTest.scala, core/src/test/scalajvm/sttp/tapir/internal/RichEndpointOutputTest.scala, tests/src/main/scala/sttp/tapir/tests/OneOf.scala
=> Don't reject a oneof variant when there's no body, and the response specifies a content-type

doc/endpoint/ios.md
=> chore: remove extra quotation mark

build.sbt, doc/endpoint/integrations.md, doc/stability.md, generated-doc/out/endpoint/integrations.md, generated-doc/out/stability.md, integrations/monix-newtype/src/main/scala/sttp/tapir/codec/monix/newtype/TapirCodecMonixNewType.scala, integrations/monix-newtype/src/main/scala/sttp/tapir/codec/monix/newtype/newtype.scala, integrations/monix-newtype/src/test/scala/sttp/tapir/codec/monix/newtype/TapirCodecMonixNewTypeTest.scala, project/Versions.scala
=> #2361 add monix newtypes integration

server/core/src/main/scala/sttp/tapir/server/interceptor/CustomiseInterceptors.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/content/NotAcceptableInterceptor.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/content/UnsupportedMediaTypeInterceptor.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerContentNegotiationTests.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerOneOfBodyTests.scala
=> Use 406 instead of 415 when the Accept header doesn't match any of the supported content

core/src/main/scala-2/sttp/tapir/internal/OneOfMacro.scala, core/src/main/scala-2/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala/sttp/tapir/Schema.scala, core/src/test/scala/sttp/tapir/SchemaMacroTest.scala, doc/endpoint/customtypes.md, doc/endpoint/json.md, doc/endpoint/schemas.md, docs/openapi-docs/src/test/resources/coproduct/expected_coproduct_wrapped.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlCoproductTest.scala
=> Coproduct using a wrapped representation of child schemas

core/src/main/scala/sttp/tapir/Endpoint.scala, doc/endpoint/oneof.md
=> Add errorOutVariantPrepend

doc/index.md, generated-doc/out/index.md
Follow-up to https://github.com/softwaremill/adopt-tapir/issues/217
=> fix: adjust adopt-tapir iframe's height

build.sbt, doc/endpoint/integrations.md, doc/stability.md, generated-doc/out/endpoint/integrations.md, generated-doc/out/stability.md, integrations/zio-prelude/src/main/scala/sttp/tapir/codec/zio/prelude/newtype/TapirNewtype.scala, integrations/zio-prelude/src/main/scala/sttp/tapir/codec/zio/prelude/newtype/TapirNewtypeSupport.scala, integrations/zio-prelude/src/test/scala-2/sttp/tapir/codec/zio/prelude/newtype/TapirNewtypeSupportTestFixture.scala, integrations/zio-prelude/src/test/scala-2/sttp/tapir/codec/zio/prelude/newtype/TapirNewtypeTestFixture.scala, integrations/zio-prelude/src/test/scala-3/sttp/tapir/codec/zio/prelude/newtype/TapirNewtypeSupportTestFixture.scala, integrations/zio-prelude/src/test/scala-3/sttp/tapir/codec/zio/prelude/newtype/TapirNewtypeTestFixture.scala, integrations/zio-prelude/src/test/scala/sttp/tapir/codec/zio/prelude/newtype/TapirNewtypeSupportTest.scala, integrations/zio-prelude/src/test/scala/sttp/tapir/codec/zio/prelude/newtype/TapirNewtypeTest.scala, project/Versions.scala
Addresses https://github.com/softwaremill/tapir/issues/2361.
=> feat(integrations): add ZIO Prelude Newtype support

server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerOptions.scala
=> Add a default log to the zio http interpreter

server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerHandler.scala
=> Properly release netty requests

doc/grpc.md, grpc/protobuf/src/main/scala/sttp/tapir/grpc/protobuf/EndpointToProtobufMessage.scala, grpc/protobuf/src/main/scala/sttp/tapir/grpc/protobuf/ProtoRenderer.scala, grpc/protobuf/src/main/scala/sttp/tapir/grpc/protobuf/ProtobufScalarType.scala, grpc/protobuf/src/main/scala/sttp/tapir/grpc/protobuf/model/ProtobufMessage.scala, grpc/protobuf/src/test/scala/sttp/tapir/grpc/protobuf/ProtoRendererTest.scala, grpc/protobuf/src/test/scala/sttp/tapir/grpc/protobuf/ProtobufInterpreterTest.scala
Closes https://github.com/softwaremill/tapir/issues/2524 https://github.com/softwaremill/tapir/issues/2525
=> Add support for grpc repeated  and oneof fields

server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyOptions.scala
Hi,
I need the possibility to use SSL with the Netty-based server.
Added a method to the NettyOptions to be able to inject a SslContext.
=> add possibility to define a SslContext for a Netty-based server

build.sbt, doc/server/ziohttp.md, examples/src/main/scala/sttp/tapir/examples/HelloWorldZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/ZioExampleZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/observability/ZioMetricsExample.scala, examples/src/main/scala/sttp/tapir/examples/openapi/RedocZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/streaming/StreamingZioHttpServer.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpRequestBody.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerRequest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpCompositionTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala
Hopefully I've managed to figure everything out, especially regarding the tests. 🤞
=> chore: support zio http 0.0.3

core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala
In `generateOneOfWrapped` method, added a meaningful error message for a case when it is not possible to summon subclass schema.
=> Meaningful error message when it is not possible to summon subclass schema.

serverless/aws/sam/src/main/scala/sttp/tapir/serverless/aws/sam/AwsSamOptions.scala, serverless/aws/sam/src/main/scala/sttp/tapir/serverless/aws/sam/AwsSamTemplateEncoders.scala, serverless/aws/sam/src/main/scala/sttp/tapir/serverless/aws/sam/EndpointsToSamTemplate.scala, serverless/aws/sam/src/main/scala/sttp/tapir/serverless/aws/sam/model.scala, serverless/aws/sam/src/test/resources/http_api_template.yaml, serverless/aws/sam/src/test/scala/sttp/tapir/serverless/aws/sam/VerifySamTemplateTest.scala
=> configure aws sam environment

server/vertx-server/zio/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala, server/vertx-server/zio/src/test/scala/sttp/tapir/server/vertx/zio/ZioVertxServerTest.scala
=> Fix synchronous effect execution for ZIO2 Vert.X server

core/src/main/scala/sttp/tapir/Codec.scala
Close https://github.com/softwaremill/tapir/issues/2646
=> add content range codec

server/core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLog.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLogInterceptor.scala
Add token to ServerLog.requestReceived as suggested by #2641
=> Change that ServerLog.requestReceived takes a token as the other callbacks

README.md, build.sbt, client/sttp-client/src/main/scala/sttp/tapir/client/sttp/EndpointToSttpClient.scala, client/sttp-client/src/main/scalajs/sttp/tapir/client/sttp/EndpointToSttpClientExtensions.scala, client/sttp-client/src/main/scalajs/sttp/tapir/client/sttp/ws/fs2/TapirSttpClientFs2WebSockets.scala, client/sttp-client/src/main/scalajs/sttp/tapir/client/sttp/ws/fs2/WebSocketToFs2Pipe.scala, client/sttp-client/src/main/scalajs/sttp/tapir/client/sttp/ws/fs2/package.scala, client/sttp-client/src/main/scalajs/sttp/tapir/client/sttp/ws/zio/TapirSttpClientZioWebSockets.scala, client/sttp-client/src/main/scalajs/sttp/tapir/client/sttp/ws/zio/WebSocketToZioPipe.scala, client/sttp-client/src/main/scalajs/sttp/tapir/client/sttp/ws/zio/package.scala, client/sttp-client/src/main/scalajvm/sttp/tapir/client/sttp/EndpointToSttpClientExtensions.scala, client/sttp-client/src/main/scalanative/sttp/tapir/client/sttp/EndpointToSttpClientExtensions.scala, client/sttp-client/src/test/scalajs/sttp/tapir/client/sttp/SttpClientWebSocketZioTests.scala, client/sttp-client/src/test/scalajs/sttp/tapir/client/sttp/SttpClientZioTests.scala
=> Properly determine if a WS request is successful when running in JS (sttp client interpreter)

server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/impl/JsonCodecs.scala, server/sttp-mock-server/src/test/scala/sttp/tapir/server/mockserver/SttpMockServerClientSpec.scala, server/sttp-mock-server/src/test/scala/sttp/tapir/server/mockserver/fixture/fixture.scala
A low effort attempt to fix #2763 also trying not to invade the whole code base. Let me know if that's not sufficient enough / not really a desired approach, since we could try to come up with smth more radical.
Closes #2763
=> MockServerClient null / empty body regression fix

core/src/main/scala/sttp/tapir/Codec.scala, json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala, json/circe/src/test/scalajvm/sttp/tapir/json/circe/TapirJsonCirceTests.scala, json/json4s/src/main/scala/sttp/tapir/json/json4s/TapirJson4s.scala, json/jsoniter/src/main/scala/sttp/tapir/json/jsoniter/TapirJsonJsoniter.scala, json/playjson/src/main/scala/sttp/tapir/json/play/TapirJsonPlay.scala, json/sprayjson/src/main/scala/sttp/tapir/json/spray/TapirJsonSpray.scala, json/tethys/src/main/scala/sttp/tapir/json/circe/TapirJsonTethys.scala, json/upickle/src/main/scala/sttp/tapir/json/upickle/TapirJsonuPickle.scala, json/zio/src/main/scala/sttp/tapir/json/zio/TapirJsonZio.scala, json/zio1/src/main/scala/sttp/tapir/json/zio/TapirJsonZio.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerOptions.scala
Closes https://github.com/softwaremill/tapir/issues/2786
=> Properly handle optional json query parameters

server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerRequest.scala
Set connectionInfo.remote correctly to zio-http's request.remoteAddress
=> use remoteAddress from zio-http Request

core/src/main/scala/sttp/tapir/Codec.scala, core/src/main/scala/sttp/tapir/Schema.scala, core/src/test/scalajvm/sttp/tapir/CodecTestDateTime.scala
=> Add ZoneId support

files/src/main/scalajvm/sttp/tapir/files/TapirStaticContentEndpoints.scala, files/src/main/scalajvm/sttp/tapir/files/model.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerFilesTests.scala
Fixes https://github.com/softwaremill/tapir/issues/2869
=>  [bugfix] Detecting gzip in Accept-Encoding

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala
=> Openapi codegen support tags on endpoints

doc/docs/json-schema.md, doc/index.md, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/schema.scala
A follow-up to https://github.com/softwaremill/tapir/pull/2873
=> Document generating JSON schema

doc/endpoint/ios.md, doc/index.md, doc/server/errors.md, doc/server/path.md, server/core/src/main/scala/sttp/tapir/server/interpreter/DecodeBasicInputs.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala
=> Decode method inputs first, before path inputs

build.sbt, doc/index.md, doc/server/jdkhttp.md, examples/src/main/scala/sttp/tapir/examples/HelloWorldJdkHttpServer.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/JdkHttpServer.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/JdkHttpServerInterpreter.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/JdkHttpServerOptions.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/internal/JdkHttpBodyListener.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/internal/JdkHttpRequestBody.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/internal/JdkHttpServerRequest.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/internal/JdkHttpToResponseBody.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/internal/package.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/package.scala, server/jdkhttp-server/src/test/scala/sttp/tapir/server/jdkhttp/JdkHttpServerTest.scala, server/jdkhttp-server/src/test/scala/sttp/tapir/server/jdkhttp/JdkHttpTestServerInterpreter.scala
WIP, needs clean up and debugging work.
=> Simple, synchronous, zero-dependency http server for toy/small projects

doc/server/aws.md
* Should I write more about it?
=> Update serverless documentation to mention "fat lambdas"

server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyConfig.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettySocketConfig.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyBootstrap.scala
Extends netty configuration with socket options
=> extend netty configutation with socket options

project/Versions.scala
Fixes https://github.com/softwaremill/tapir/issues/2980
=> Update sttp-apispecs to v0.5.3

core/src/main/scala-2/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala-2/sttp/tapir/internal/OneOfMacro.scala, core/src/main/scala-2/sttp/tapir/internal/SchemaAnnotationsMacro.scala, core/src/main/scala-3/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/SchemaAnnotations.scala, core/src/main/scala/sttp/tapir/SchemaType.scala, doc/docs/json-schema.md, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/Schemas.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/ToKeyedSchemas.scala, docs/apispec-docs/src/test/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchemaTest.scala, generated-doc/out/docs/json-schema.md
This reverts commit 492dfb81caf53b6b6c3ea7d4b11dba0b522d0d2d.
=> Revert "Add title to jsonschema (#3001)"

core/src/main/scala-2/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala-3/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala/sttp/tapir/Schema.scala, doc/docs/json-schema.md, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchema.scala, docs/apispec-docs/src/test/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchemaTest.scala, generated-doc/out/docs/json-schema.md
- Add title annotation for jsonschema
=> add json title annotation

server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyConfig.scala
* Improvments after review in https://github.com/softwaremill/tapir/pull/2983
=> Improvments in netty configuration

core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/test/scala-3/sttp/tapir/SchemaMacroScala3Test.scala
=> Support parameterless enum cases in oneOfWrapped macro

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/ModelParserSpec.scala
I've just started looking at the using the codegen plugin. This works and seems to be the intended pattern, but I haven't done much on the testing front...
=> Support uuid format string in codegen

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala
Permits inclusion of other legal field names in path items - cf https://swagger.io/specification/#path-item-object
=> permit extra fields in paths item object

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiComponent.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala
Completely exclusive with #3073 - this demonstrates the other approach I was thinking of. Not sure which is really better tbh - this one retains parameter ordering, but the other might be simpler 🤷 Got a bit carried away exploring it, and couldn't decide which approach was best. Please feel free to close one or the other if the decision seems obvious
=> alternative approach to param resolution in codegen

project/Versions.scala
=> Update sttp-model to 1.7.2

server/core/src/main/scala/sttp/tapir/server/interpreter/ServerInterpreter.scala
=> Server interpreter optimizations

build.sbt, doc/server/jdkhttp.md, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/internal/JdkHttpRequestBody.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/internal/JdkHttpToResponseBody.scala, server/jdkhttp-server/src/main/scala/sttp/tapir/server/jdkhttp/internal/ParsedMultiPart.scala, server/jdkhttp-server/src/test/scala/sttp/tapir/server/jdkhttp/JdkHttpServerTest.scala
Fixes https://github.com/softwaremill/tapir/issues/3130
Took a bunch of inspiration from the finatra-server, but I'm new to the codebase (and multipart 😅) so feel free to go hard on me 😄
=> Add jdkhttp-server multipart support

project/Versions.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerContentNegotiationTests.scala, tests/src/main/scala/sttp/tapir/tests/ContentNegotiation.scala
=> Only check content type range parameters if they are present

doc/docs/openapi.md
Add a config for sbt-assembly whereas Swagger static files from the webjar are included.
=> Update docs for sbt-assembly config

server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sWebSockets.scala
Some performance improvements.
=> Improve Http4sWebSockets.pipeToBody

core/src/main/scala-3/sttp/tapir/internal/SchemaAnnotationsMacro.scala, core/src/test/scala/sttp/tapir/SchemaAnnotationsTest.scala, core/src/test/scala/sttp/tapir/SchemaAnnotationsTestData.scala
=> Fix the hidden schema annotation for Scala 3

examples/src/main/scala/sttp/tapir/examples/security/CorsInterceptorPekkoServer.scala
In a response for https://github.com/softwaremill/tapir/issues/3326
=> Added CORSInterceptor example for PekkoServer

build.sbt, client/sttp-client/src/main/scalajvm/sttp/tapir/client/sttp/ws/pekkohttp/TapirSttpClientPekkoHttpWebSockets.scala, client/sttp-client/src/main/scalajvm/sttp/tapir/client/sttp/ws/pekkohttp/WebSocketToPekkoPipe.scala, client/sttp-client/src/main/scalajvm/sttp/tapir/client/sttp/ws/pekkohttp/package.scala, client/sttp-client/src/test/scalajvm/sttp/tapir/client/sttp/SttpClientPekkoTests.scala, client/sttp-client/src/test/scalajvm/sttp/tapir/client/sttp/SttpClientWebSocketPekkoTests.scala, doc/client/sttp.md, examples/src/main/scala/sttp/tapir/examples/websocket/WebSocketPekkoServer.scala
=> Add support for pekko http in sttp client interpreter

core/src/main/scala-3-2.13+/sttp/tapir/CodecExtensions2.scala, core/src/main/scala/sttp/tapir/Schema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/package.scala, docs/openapi-docs/src/test/resources/enum/expected_enum_in_delimited_query_with_default.yml, docs/openapi-docs/src/test/scalajvm-3-2.13+/sttp/tapir/docs/openapi/VerifyYamlEnumerationTest.scala
=> Add a delimiter attribute to properly represent delimited values in examples/defaults

core/src/main/scala/sttp/tapir/generic/Configuration.scala, core/src/test/scala/sttp/tapir/generic/FormCodecDerivationTest.scala, core/src/test/scala/sttp/tapir/generic/MultipartCodecDerivationTest.scala, core/src/test/scala/sttp/tapir/generic/SchemaGenericAutoTest.scala, json/pickler/src/main/scala/sttp/tapir/json/pickler/PicklerConfiguration.scala, json/pickler/src/test/scala/sttp/tapir/json/pickler/SchemaDerivationTest.scala
Added 
- withScreamingSnakeCaseDiscriminatorValues 
- withScreamingSnakeCaseMemberNames
to Configuration and PicklerConfiguration.
=> Schema screaming snake case

core/src/main/boilerplate-gen/sttp/tapir/typelevel/TupleOps.scala, core/src/main/scala-3/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala-3/sttp/tapir/internal/AnnotationsMacros.scala, core/src/main/scala-3/sttp/tapir/internal/CaseClass.scala, core/src/main/scala-3/sttp/tapir/internal/ComplietimeErrors.scala, core/src/main/scala-3/sttp/tapir/macros/CodecMacros.scala, core/src/main/scala-3/sttp/tapir/macros/EndpointInputMacros.scala, core/src/main/scala-3/sttp/tapir/macros/EndpointMacros.scala, core/src/main/scala-3/sttp/tapir/macros/EndpointOutputMacros.scala, core/src/main/scala-3/sttp/tapir/macros/EndpointTransputMacros.scala, core/src/main/scala-3/sttp/tapir/macros/ErasureSameAsTypeMacros.scala, core/src/main/scala-3/sttp/tapir/macros/FormCodecMacros.scala, core/src/main/scala-3/sttp/tapir/macros/ModifyMacroSupport.scala, core/src/main/scala-3/sttp/tapir/macros/MultipartCodecMacros.scala, core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala-3/sttp/tapir/typelevel/IntersectionTypeMirror.scala, core/src/main/scala-3/sttp/tapir/typelevel/UnionTypeMirror.scala, core/src/main/scala/sttp/tapir/TapirAuth.scala, core/src/main/scalajvm/sttp/tapir/Defaults.scala
A little cleanup to reducing the number of compilation warnings.
=> Clear compilation warnings

doc/server/netty.md
Fixed "should can" and missing article.
=> Fix small wording issue in netty.md

build.sbt, project/Versions.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpBodyListener.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala
=> Update `zio-http` to v3.0.0-RC6

core/src/main/scala/sttp/tapir/Codec.scala, core/src/main/scala/sttp/tapir/Schema.scala
=> Add schema for uri

docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/MessagesForEndpoints.scala, docs/asyncapi-docs/src/test/resources/expected_json_examples.yml
=> Updated conversion from CodecWithInfo into asyncapi.Message.

server/core/src/main/scala/sttp/tapir/server/interpreter/ServerInterpreter.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala
resolves #3682
resolves #3712
sorry it took a while! :)
=> remove validation on body for NoContent/NotModified

build.sbt, project/Versions.scala
=> Update tethys version and add scala 3 support for tethys-json module.

build.sbt
A follow-up to https://github.com/softwaremill/tapir/pull/3894 and https://github.com/softwaremill/tapir/pull/3896
=> Enable nativePlatform for jsoniter

server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala
=> Fix extractFromRequest in zio http endpoints

core/src/main/scala/sttp/tapir/Tapir.scala, server/armeria-server/src/main/scala/sttp/tapir/server/armeria/RouteMapping.scala, server/finatra-server/src/main/scala/sttp/tapir/server/finatra/FinatraServerInterpreter.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala
=> Generate exact zio patterns for endpoints, taking into account lack of zio's support for no-trailing-slashes

core/src/main/scala-2/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala-3/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala/sttp/tapir/Schema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/apispec-docs/src/test/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchemaTest.scala
Follow-up to https://github.com/softwaremill/tapir/pull/3941
=> Properly derive schemas for tuples

core/src/main/scala-3/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala
This should satisfy the compiler's checks
Closes #3967
=> Handle nulls more explicitly in schema derivation

.github/workflows/ci.yml, build.sbt, project/Versions.scala
=> feat(zio): support Native

server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala
=> Add a path matching test

build.sbt, client/sttp-client/src/test/scalajvm/sttp/tapir/client/sttp/SttpClientWebSocketTests.scala, client/testserver/src/main/scala/sttp/tapir/client/tests/HttpServer.scala
Related to https://github.com/softwaremill/tapir/issues/3959
=> Add test for reading headers from web socket responses

build.sbt
Use commonSettings for root projects, commonJvmSettings for the JVM axis, do not duplicate settings
=> Cleanup sbt settings

doc/client/sttp.md
Commit 7f6d4218ff72fcd259eced12113fb38666c4270b renamed the books example file. This PR adjusts sources to changes.
=> Update booksExample reference

docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointInputToDecodeFailureOutput.scala, docs/openapi-docs/src/test/resources/example/expected_examples_of_list_and_not_list_types.yml, docs/openapi-docs/src/test/resources/expected_array_no_format.yml, docs/openapi-docs/src/test/resources/expected_optional_header.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala
=> Better inference of infallible schemas when generating OpenAPI docs

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/DefaultValueRenderer.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Some failures will now be less cryptic, and defaults for inline enums should now work
=> codegen: better error reporting + support defaults on inline enums

metrics/prometheus-metrics/src/main/scala/sttp/tapir/server/metrics/prometheus/PrometheusMetrics.scala
=> Make buckets configurable for default histogram

integrations/zio/src/main/scala/sttp/tapir/ztapir/ZPartialServerEndpoint.scala
=> ZPartialServerEndpoint.serverLogic should return ServerEndpoint.Full (#4397)

.github/workflows/ci.yml, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerHandler.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/reactivestreams/CancellingSubscriber.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/reactivestreams/SubscribeTrackingStreamedHttpRequest.scala, server/netty-server/src/test/scala/sttp/tapir/server/netty/NettyFutureServerTest.scala
=> Netty: cancel the request body if never used

core/src/main/scala/sttp/tapir/TapirAuth.scala, doc/endpoint/security.md, docs/openapi-docs/src/test/resources/security/expected_multiple_optional_auth_oauth2.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlSecurityTest.scala
=> Make it possible to create optional oauth2 authorization flows

docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchema.scala, docs/apispec-docs/src/test/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchemaTest.scala
Closes https://github.com/softwaremill/sttp-apispec/issues/232
=> Properly render json schemas for top-level arrays

docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchema.scala, docs/apispec-docs/src/test/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchemaTest.scala
=> Support root-recursive schemas when generating JSON Schema

.gitignore, build.sbt, server/sttp-stub4-server/src/main/scala/sttp/tapir/server/stub4/SttpRequestBody.scala, server/sttp-stub4-server/src/main/scalajs/sttp/tapir/server/stub4/internal/SttpFileToTapirFile.scala, server/sttp-stub4-server/src/main/scalajvm/sttp/tapir/server/stub4/internal/SttpFileToTapirFile.scala
=> Enabling stub server for JS

integrations/iron/src/main/scala/sttp/iron/codec/iron/TapirCodecIron.scala
See https://github.com/Iltotore/iron/issues/327 and https://github.com/scala/scala3/issues/23201
=> fix: De-inline iron given instances
