build.sbt
Upgrade http4s to the newest version. Unfortunately there are breaking changes between M5 and M6 so it's crucial to release this version.
I've ran `sbt compile test` and everything passed successfully, so it seems like `tapir` wasn't using any of breaking changes itself.
=> Upgrade http4s version to 0.20.0-M6

docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOpenAPIDocs.scala
Add servers parameter to toOpenAPI to avoid `.toOpenAPI(...).copy(servers = List(Server(...)))`
Addresses https://github.com/softwaremill/tapir/issues/61
=> Add servers parameter to toOpenAPI

docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOpenAPIDocs.scala, openapi/openapi-model/src/main/scala/tapir/openapi/OpenAPI.scala
Avoid using a default parameter and instead add a `servers` method to `OpenAPI` which prevents error like this:
```
[error] /Users/adamw/projects/tapir/docs/openapi-docs/src/main/scala/tapir/docs/openapi/TapirOpenAPIDocs.scala:7:18: in class RichOpenAPIEndpoint, multiple overloaded alternatives of method toOpenAPI define default arguments.
[error]   implicit class RichOpenAPIEndpoint[I, E, O, S](e: Endpoint[I, E, O, S]) {
```
=> Add servers parameter openapi

doc/requirements.pip
With this installing all required packages can be done with single line:
`pip3 -r requirements.pip` 
Additional benefit is that we will be immune bugs in newer versions :)
=> Add requirements.pip

core/src/main/scala/tapir/Schema.scala, core/src/main/scala/tapir/SchemaFor.scala, core/src/main/scala/tapir/generic/DiscriminatorDerivationMacro.scala, core/src/main/scala/tapir/generic/MethodNameMacro.scala, core/src/main/scala/tapir/generic/OneOfMacro.scala, core/src/main/scala/tapir/generic/SchemaForMagnoliaDerivation.scala, doc/endpoint/codecs.md, docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOpenAPIDocs.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOpenApiComponents.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/DiscriminatorToOpenApi.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/ObjectSchemas.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/ObjectSchemasForEndpoints.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/SchemaReferenceMapper.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/TSchemaToOSchema.scala, docs/openapi-docs/src/test/resources/expected_coproduct.yml, docs/openapi-docs/src/test/resources/expected_coproduct_discriminator.yml, docs/openapi-docs/src/test/resources/expected_coproduct_discriminator_nested.yml, docs/openapi-docs/src/test/resources/expected_coproduct_nested.yml, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala, openapi/openapi-circe/src/main/scala/tapir/openapi/circe/package.scala, openapi/openapi-model/src/main/scala/tapir/openapi/OpenAPI.scala, playground/src/main/scala/tapir/example/BooksExample.scala
I am not very happy with the `disclaimer` implementation as with how it is being used although generally this solution works quite well even for more complicated sets of coproducts. 
I had to use @BBartosz code for schemas extraction in order to properly reference sealed classes within `oneOf` section.
This closes #10
=> Add support for coproducts

json/circe/src/main/scala/tapir/json/circe/TapirJsonCirce.scala
This instance helps magnolia to derive SchemaFor instances for ADT's like `case class Person(name: String, meta: Json)`.
This is helpful if you're providing an object with free structured field.
=> Add instance SchemaFor[io.circe.Json]

.travis.yml, build.sbt, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala, openapi/openapi-circe/src/main/scala/tapir/openapi/circe/package.scala, server/http4s-server/src/main/scala/tapir/server/http4s/EndpointToHttp4sServer.scala, server/http4s-server/src/main/scala/tapir/server/http4s/OutputToHttp4sResponse.scala, server/tests/src/main/scala/tapir/server/tests/ServerTests.scala
This closes #59 
Solved issues:
- knownDirectSubclasses of <class> observed before subclass <class> registered - circe/circe#639
- http4s compilation errors -  enabling YpartialUnification
- other compilation errors - enabling Xexperimental
- fromResource is not a member of Source class - https://stackoverflow.com/questions/27360977/how-to-read-files-from-resources-folder-in-scala
- downgraded scala-logging due to missing artifact for scala 2.11 - https://github.com/lightbend/scala-logging/issues/160
=> Add support for scala 2.11

core/src/main/scala/tapir/EndpointIO.scala, core/src/main/scala/tapir/TapirAuth.scala, doc/endpoint/auth.md, doc/openapi.md, docs/openapi-docs/src/main/scala/tapir/docs/openapi/SecuritySchemesForEndpoints.scala, openapi/openapi-model/src/main/scala/tapir/openapi/OpenAPI.scala
add another auth method - oauth2 using authorizationCode.
I did not investigate the other methods, so this PR is specific for authorizationCode.
example usage:
```
val apiEndpoint = baseEndpoint.in("api" / "v1")
.in(auth.oauth2(
"http://localhost:8080/auth/realms/realm/protocol/openid-connect/auth",
"http://localhost:8080/auth/realms/realm/protocol/openid-connect/token", 
ListMap(("profile", "")))
).mapInTo(Auth)
```
in order for it to work - need to add the following route: 
```
private def redirectToOath2(query: String): Route =
redirect(s"/swagger/oauth2-redirect.html$query", StatusCodes.PermanentRedirect)
~ path("oauth2-redirect.html") { request =>
redirectToOath2(request.request.uri.rawQueryString.map(s => '?' + s).getOrElse(""))(request)
}
```
=> Oauth2 authorization code

core/src/main/scala/tapir/Endpoint.scala, core/src/test/scala/tapir/EndpointTest.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOpenApiPaths.scala
Result of discussion from gitter https://gitter.im/softwaremill/tapir?at=5d07970126477710bbc78249
Added method which can be used to return path with query params of given endpoint, e.g. for 
```scala
endpoint.in("p1" / path[String] / query[String]("par2"))
```
returns `/p1/{param1}?par2={par2}`
It can be used in various cases when there is a need to describe the endpoint path, e.g. in transaction naming in metrics or in openapi endpoint definition. In fact most of the code is extracted from `EndpointToOpenApiPaths`.
Similar approach described in #112
=> Added method to render path of Endpoint

server/tests/src/main/scala/tapir/server/tests/ServerTests.scala, tests/src/main/scala/tapir/tests/package.scala
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
at tapir.server.tests.ServerTests.$anonfun$$init$$53(ServerTests.scala:112)
```
=> Test - broken input parsing when header input is specified before path input

client/sttp-client/src/main/scala/tapir/client/sttp/EndpointToSttpClient.scala, client/tests/src/main/scala/tapir/client/tests/ClientTests.scala, core/src/main/scala/tapir/EndpointIO.scala, core/src/main/scala/tapir/Tapir.scala, core/src/main/scala/tapir/internal/server/EncodeOutputs.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOperationResponse.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/ObjectSchemasForEndpoints.scala, docs/openapi-docs/src/test/resources/expected.yml, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala, tests/src/main/scala/tapir/tests/package.scala
This PR addresses issue: https://github.com/softwaremill/tapir/issues/155 and allows the assigning of a description to a response status code when using FixedStatusCode.
=> Add description for FixedStatusCode

docs/openapi-docs/src/main/scala/tapir/docs/openapi/EndpointToOpenApiPaths.scala, docs/openapi-docs/src/test/resources/expected_multipart.yml
The default operationId is a concatenation of the path and operation. For example, a path
`POST /v1/user/create/:id` may become something like `client.postV1UserCreateId` in the generated python/golang/java client.
It would be great if we can use the given name, instead. That way, you can specify the name you want in the API definition. Currently, the name set to `Endpoint#info.name` does not seem to be rendered out into the OpenAPI yaml.
`endpoint.name("createUser")` would become `client.createUser`
=> Use name as operationId, if it is set

core/src/main/scala/tapir/internal/server/DecodeInputs.scala, core/src/main/scala/tapir/server/ServerDefaults.scala, server/tests/src/main/scala/tapir/server/tests/ServerTests.scala, tests/src/main/scala/tapir/tests/AlwaysSuccess.scala, tests/src/main/scala/tapir/tests/package.scala
Implement route matching which matches the "shape" of a route where the shape is determined by matching the constant segments and wildcard segments (path parameters).
e.g. A path of /"customer"/path[String]/"orders"/path[Int] has the shape of /customer/*/orders/*
Any request URI the path shape with invalid path parameters will return a 400 BadRequest instead of DecodeFailureHandling.NoMatch
To obtain the original behaviour where an invalid path parameter results in NoMatch (i.e. tries to match later routes), the user can override `decodeFailureHandler` to not fail on an error resulting from `EndpointInput.PathCapture[_]`
=> #141 Shape-aware route matching

core/src/main/scala/tapir/TapirAliases.scala, doc/mytapir.md
This addresses https://github.com/softwaremill/tapir/issues/161. I decided to introduce aliases for all top-level types and modules in `package tapir` – I hope I didn't miss any.
=> Added `TapirAliases` mixin

build.sbt, project/plugins.sbt
You will probably need to ask the macwire team to publish a ScalaJS/Scala Native version but it doesn't seem to prevent sttp client from being generated.
=> Compile sttp client for ScalaJS and Scala Native

core/src/main/scala/tapir/Validator.scala, core/src/main/scala/tapir/server/ServerDefaults.scala, core/src/test/scala/tapir/ValidatorTest.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/TSchemaToOSchema.scala, docs/openapi-docs/src/test/resources/expected_valid_body_collection.yml, docs/openapi-docs/src/test/resources/expected_valid_body_wrapped.yml, openapi/openapi-model/src/main/scala/tapir/openapi/OpenAPI.scala, tests/src/main/scala/tapir/tests/FruitAmount.scala, tests/src/main/scala/tapir/tests/package.scala
This PR allows to support `minLength` and `maxLength` validators on strings, defined by OpenAPI https://swagger.io/docs/specification/data-models/data-types/#string
=> Add minLength and maxLength validators

build.sbt, project/Versions.scala
this version introduced a binary incompatibility.
it also pulls cats-2.
PR also updates sttp to 1.6.7 since it has the same dependencies.
=> http4s-0.21.0-M5

core/src/main/scala/tapir/Codec.scala, core/src/main/scala/tapir/Validator.scala, core/src/main/scala/tapir/generic/ValidatorEnumMacro.scala, core/src/main/scala/tapir/server/ServerDefaults.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/package.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/ObjectSchemasForEndpoints.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/TSchemaToOSchema.scala, docs/openapi-docs/src/main/scala/tapir/docs/openapi/schema/TypeData.scala, docs/openapi-docs/src/test/resources/expected_valid_enum_object.yml, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala, tests/src/main/scala/tapir/tests/package.scala
Currently there is no way to make an Enum within in a parent object render correctly (AFAICS).
The main issue for Enums seems to be that the TSchemaToOSchema.apply will call itself, without the encodeToAny parameters, so every nested Enum will not have any values.
See b75346a4e39f09c6e4a49e10b58848a17e8fa895 for a test demonstrating the issue.
This PR also includes a "fix" - it doesn't solve all problems but it let you implements workarounds for it.
It is fine by me if this is solved properly instead of using this workaround. I can't spend more time on this though, so I defer to you guys :)
I think the issue for #237 is related to this. Maybe @mpapillon wants to see if this works for him or not. Again: it is not a complete solution though.
=> Enable workaround for Validator.Enum

core/src/main/scala/tapir/SchemaFor.scala
ZoneOffset is often used in APIs involving time data if separating the time from the time zone, for example providing a field that is always in UTC and another field to indicate the time zone.
Time Zone offsets are usually sent in the format: `"[-+]?\d\d:\d\d"` and so can reuse the `SchemaFor(SString)`
=> Add a SchemaFor[ZoneOffset]

build.sbt, doc/openapi.md, docs/redoc-http4s/src/main/resources/redoc.html, docs/redoc-http4s/src/main/scala/tapir/redoc/http4s/RedocHttp4s.scala
As already discussed on gitter, I would like to a module to tapir that uses Redoc to display a OpenAPI UI.
Since the website already needs an internet connection to download fonts from Google Fonts, I opted to download the main JS file from a CDN as well, instead of loading it from a webjar. Is this a problem?
=> Add Redoc-powered UI

docs/openapi-docs/src/test/resources/expected_valid_body_enum.yml, docs/openapi-docs/src/test/resources/expected_valid_enum_class.yml, docs/openapi-docs/src/test/resources/expected_valid_enum_class_wrapped_in_option.yml, docs/openapi-docs/src/test/scala/tapir/docs/openapi/VerifyYamlTest.scala, tests/src/main/scala/tapir/tests/FruitAmount.scala, tests/src/main/scala/tapir/tests/package.scala
Breaking test to help diagnose the issue in #260 
```
[info] - validator with enum type in body *** FAILED ***
[info]   "...1
[info]   color:
[info]   type:string[]" was not equal to "...1
[info]   color:
[info]   type:string[
[info]   enum:
[info]   -blue
[info]   -red]" (VerifyYamlTest.scala:431)
```
=> Add breaking test with enum in body

docs/redoc-http4s/src/main/resources/redoc.html
I noticed that the version I originally added is a few months old and much never one exists.
=> Use a newer version of Redoc

build.sbt, cats/src/main/scala/tapir/cats/CatsSchemaFor.scala, cats/src/main/scala/tapir/cats/package.scala, cats/src/test/scala/tapir/cats/SchemaForTest.scala, project/Versions.scala
This PR adds a new module "tapir-cats" for some cats integrations. Initially it contains SchemaFor instances for NonEmptyList, NonEmptyChain and NonEmptySet.
=> Add cats module with instances for SchemaFor

docs/swagger-ui-http4s/src/main/scala/tapir/swagger/http4s/SwaggerHttp4s.scala, project/Versions.scala, server/http4s-server/src/main/scala/tapir/server/http4s/Http4sRequestToRawBody.scala, server/http4s-server/src/main/scala/tapir/server/http4s/OutputToHttp4sResponse.scala
This PR upgrades http4s and sttpClient in Scala 2.12. It doesn't choose any exotic versions, just the same versions as chosen in Scala 2.13. It also upgrades sttpClient in Scala 2.12 -- I wasn't sure if that was the source of a binary compatibility issue or if I'd just needed a full clean in the testing artifacts. Anyway, apparently it didn't hurt anything.
Since http4s has dropped future support for Scala 2.11 and there's already a healthy tapir release out on http4s for people who specifically want not to be on a milestone release, it should be safe to push to the next milestone for people who need to keep their versions in sync for other reasons (for example, I can't serve docs in https://github.com/raster-foundry/granary/ due to a binary compatibility issue, and I _think_ it stems …
=> Upgrade scala 2.12 http4s and sttp client versions

doc/openapi.md, doc/server/akkahttp.md
Since 0.12, Tapir Akka modules depend on Akka 2.6 which is very fresh and may require more careful migration. However, due to good binary compatibility, for some projects forcing Akka 2.5 may be good enough, so it's worth mentioning in the docs.
=> Add information about excluding Akka 2.6

project/Versions.scala, server/finatra-server/src/main/scala/sttp/tapir/server/finatra/FinatraRoute.scala, server/finatra-server/src/main/scala/sttp/tapir/server/finatra/OutputToFinatraResponse.scala, server/finatra-server/src/main/scala/sttp/tapir/server/finatra/TapirController.scala, server/finatra-server/src/main/scala/sttp/tapir/server/finatra/package.scala
Updated Tapir’s good Finatra support to accommodate newer Finatra version’s internal RouteDSL’s changes.
=> Support newer (after 19.8.0) Finatra

README.md
The current example makes a compilation error:
```
found   : (sample.Main.BooksFromYear, sample.Main.Limit, sample.Main.AuthToken) => scala.concurrent.Future[Either[String,List[sample.Main.Book]]]
(which expands to)  (sample.Main.BooksFromYear, Int, String) => scala.concurrent.Future[Either[String,List[sample.Main.Book]]]
required: ((sample.Main.BooksFromYear, sample.Main.Limit, sample.Main.AuthToken)) => scala.concurrent.Future[Either[String,List[sample.Main.Book]]]
(which expands to)  ((sample.Main.BooksFromYear, Int, String)) => scala.concurrent.Future[Either[String,List[sample.Main.Book]]]
```
We need to define the function as:
```scala
def bookListingLogic(x: (BooksFromYear, Limit, AuthToken)): Future[Either[String, List[Book]]] = 
Future.successful(Right(List(Book("The Sorrows of …
```
=> Update akka-http Route generation example in README

doc/endpoint/customtypes.md
This is just a quick fix to the documentation to make the examples compile and work.
=> Replaces usages of `SchemaFor` -> `Schema`

core/src/main/scala/sttp/tapir/Endpoint.scala, core/src/main/scala/sttp/tapir/EndpointIO.scala, core/src/main/scala/sttp/tapir/Tapir.scala, core/src/main/scala/sttp/tapir/server/internal/EncodeOutputs.scala, core/src/main/scala/sttp/tapir/typelevel/RuntimeMatch.scala, core/src/test/scala/sttp/tapir/typelevel/MatchTypeTest.scala, doc/endpoint/statuscodes.md, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerTests.scala, tests/src/main/scala/sttp/tapir/tests/package.scala
I discover than type erasure can cause problem when mapping output to status code.
To explain my problem, I wrote a test for it. I wrote another commit to propose a solution for this problem.
But in some word, when we define a status mapping for a type such as M[X], because of type erasure it become M[_] and when mapping concrete value a output of M[X] can be applied on a value of type M[D].
I am not a huge fan of it, we should be able to have something better.
I also try playing with TypeTag (https://github.com/softwaremill/tapir/compare/master...strokyl:investigate_type_tag?expand=1) without a lot of success:
- would probably need to much modification one the code
- issue with mapped output
- it seems that we always finish to loose some type information (for example: Left[String, Bool] …
=> Solving type erasure issue

core/src/main/scala/sttp/tapir/Validator.scala, core/src/main/scala/sttp/tapir/generic/SealedTrait.scala, core/src/main/scala/sttp/tapir/generic/internal/ValidatorMagnoliaDerivation.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/schema/ObjectSchemasForEndpoints.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/schema/package.scala, docs/openapi-docs/src/test/resources/expected_valid_coproduct.yml, docs/openapi-docs/src/test/resources/expected_valid_optional_body_wrapped.yml, docs/openapi-docs/src/test/resources/expected_valid_optional_coproduct.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerTests.scala, tests/src/main/scala/sttp/tapir/tests/FruitAmount.scala, tests/src/main/scala/sttp/tapir/tests/package.scala
#363 
Of course I don't like leaking magnolia internals into our validators, but didn't have any other idea.
Update:
While working on it I spotted following code:
```
private def fieldsSchemaWithValidator(p: TSchemaType.SProduct, v: Validator[_]): immutable.Seq[TypeData[_]] = {	  
v match {	    
case Validator.Product(validatedFields) =>	
p.fields.map { f =>	 
TypeData(f._2, validatedFields.get(f._1).map(_.validator).getOrElse(Validator.pass))	 
}.toList	
case _ => p.fields.map(f => TypeData(f._2, Validator.pass)).toList
}
}
```
I couldn't understand the reason behind the second case and why this function takes `Validator[_]` instead of `Validator.Product[_]`. So I decided to change it and see what's gonna happen. It turned out that this other case was handling situation when we had …
=> Render field validator when used inside of coproduct

core/src/main/scala/sttp/tapir/Schema.scala, docs/openapi-docs/src/test/resources/expected_array_no_format.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala
As discussed in #386, array types should not have a format. It just confuses the swagger ui.
This PR fixes the issue and adds a testcase
=> #386: Unset format for array types

build.sbt, cats/src/main/scala/sttp/tapir/codec/cats/TapirCodecCats.scala, cats/src/test/scala/sttp/tapir/codec/cats/TapirCodecCatsTest.scala, core/src/main/scala/sttp/tapir/DecodeResult.scala, project/Versions.scala
Today, I was writing an endpoint with NonEmptyList as a result for a get parameter.
I had to add this line too make it work.
Would you be interested in providing PlainCodec for NonEmpty collection of cats here ?
If yes is it the correct way to do it ?
And if you want I can write the code for other NonEmpty collecttion.
Also I am not quite sure, how to test codec
=> Add support for using NonEmptyList as get paramter

docs/redoc-http4s/src/main/resources/redoc.html
The new Redoc version also contains the following fix: https://github.com/Redocly/redoc/commit/52484157912d908daea8255d0b7d684b33258d7a
Will this enable tapir to get rid of the `linkFromChildToParent` property here? https://github.com/softwaremill/tapir/blob/master/docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/OpenAPIDocsOptions.scala#L9
Or is the Redoc fix about something else?
In any case, I will try it out once the next tapir release has happened.
=> Upgrade Redoc version

core/src/main/scala/sttp/tapir/EndpointIO.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOpenApiPaths.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/SecuritySchemesForEndpoints.scala, docs/openapi-docs/src/test/resources/expected_oauth2.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala
I fiddled a little bit around and came up with this. Maybe it is good enough (at least as a discussion base)
---
To add required scopes on an Endpoint, you have to call `.withRequiredScopes` on Oauth2. Those scopes will then be passed with the token and rendered within OpenAPI Operations. Actually, `.withRequiredScopes` uses `Mapped` to map `Auth[String] => Auth[String, Seq[String]]`, where `String` is the _token_ and `Seq[String]` the seq of _required scopes_.
Fixes #422
=> add support for security requirements on Operations

json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala
Fixes #420
Results in the following JSON Schema:
```yaml
components:
schemas:
Json: {}
```
Where the empty schema can be read as "any JSON value" which is exactly what we want.
=> Update Schema[Json] to be a coproduct

.travis.yml, build.sbt, project/plugins.sbt
This PR introduces the sbt-mima-plugin to check for binary compatibility with previous version(s).
As Tapir is still pre-1.0.0 software, the major goal it not to prevent binary incompatibility, but rather to _know_ about binary incompatibilities, and document those in release notes.
Because Tapir had/has no focus on binary compatibility so far, this PR configures mima to only check against the previous version, currently 0.12.21.
In case an incompatibility is introduced, the mima check can be 'disabled' by changing `build.sbt` line 25 to the version currently being released. In addition, please increase either the minor version (when still before 1.0.0) or the major version (when after 1.0.0).
When Tapir 1.0.0 has been released, it might be better to undo this PR and switch to …
=> Binary compatibility checks

docs/openapi-docs/src/test/resources/expected_multiple_servers.yml, docs/openapi-docs/src/test/resources/expected_single_server_with_variables.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala, openapi/openapi-circe/src/main/scala/sttp/tapir/openapi/circe/package.scala, openapi/openapi-model/src/main/scala/sttp/tapir/openapi/OpenAPI.scala
Add missing field 'variables' in Server class from OpenAPI spec. Doesn't handle the restriction of "default" being one of the values in "enum", if "enum" is defined.
Not sure where you'd want the restriction to be applied as per this project's conventions - e.g. maybe throw an exception in constructor of ServerVariable upon violation?
P.S. This is my first ever PR on a proper project, so do let know how if the changes aren't sufficient or something's off
=> Add missing server variable to OpenAPI (#11)

json/playjson/src/main/scala/sttp/tapir/json/play/TapirJsonPlay.scala, json/playjson/src/test/scala/sttp/tapir/json/play/TapirJsonPlayTests.scala
Hello.
I think this PR is pretty self-explanatory.
Currently the play-json bindings call `Json.prettyPrint` to serialize `JsValue`s into strings.
This unnecessarily inflates the size of Json response bodies from Tapir endpoints.
While at it, I checked Circe, Spray Json and µPickle bindings, they correctly use compact (no spaces) stringification.
=> Do not pretty-print play-json output

client/tests/src/main/scala/sttp/tapir/client/tests/ClientTests.scala, core/src/main/boilerplate/sttp/tapir/internal/ParamsToSeq.scala.template, core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/SchemaType.scala, core/src/main/scala/sttp/tapir/server/internal/EncodeOutputs.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerTests.scala, tests/src/main/scala/sttp/tapir/tests/package.scala
This PR introduces support for serializing `jsonBody[Unit]` as `{}`. Currently event provided with valid `sttp.tapir.Schema[Unit]` (as discussed in [this gitter thread](https://gitter.im/softwaremill/tapir?at=5e774ba7b11a2f7c801fb29c)) tapir would generate valid swagger docs, but server would fail when encoding the response.
=> Serialize jsonBody[Unit] to empty object

client/sttp-client/src/main/scala/sttp/tapir/client/sttp/EndpointToSttpClient.scala, client/sttp-client/src/test/scala/sttp/tapir/client/sttp/SttpClientTests.scala, client/tests/src/main/scala/sttp/tapir/client/tests/ClientTests.scala, core/src/main/scala/sttp/tapir/SchemaType.scala, tests/src/main/scala/sttp/tapir/tests/package.scala
There are cases when client is unable to decode the response, due to server fail (e.g. 404). Then in exception there is not much clue what endpoint is triggered:
`java.lang.IllegalArgumentException: Cannot find mapping for status code 404 in outputs Vector...`
This MR adds wrapper for decoding exceptions with explicit information what's the endpoint address which failed, which helps debugging.
=> Added more information in exceptions during response decoding failure

core/src/main/scala/sttp/tapir/Codec.scala, core/src/test/scala/sttp/tapir/generic/FormCodecDerivationTest.scala
After migration to 0.13 there were compilation errors due to lack of `Codec[List[T], Set[U], CF]`, which were present for `CodecForMany` in 0.12. This MR should resolve this.
=> Add codecs for vectors and sets

core/src/main/scala/sttp/tapir/Validator.scala
The `Validator.pass` method is used extensively, both in the library and in application code (default auto-derivated validator is killing the compile time, and the byte-code size). It currently creates a new instance at each call. 
This PR is a quick-win to reduce the GC pressure and allocations, caching a single instance of `pass` and `reject`, using a common pattern.
=> Cache Validator pass/reject instances.

core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/internal/ModifySchemaMacro.scala, core/src/test/scala/sttp/tapir/SchemaMacroTest.scala
I found modification of schema description quite annoying especially for big case classes. 
WDYT about this shortcut for description modification?
```scala
case class Foo(a: Int, b: Int, c: Int)
object Foo {
Schema.derivedSchema[Foo] 
.description(_.a, "A")  <--  proposed syntax
.description(_.b, "B")
.description(_.c, "C")
Schema.derivedSchema[Foo]
.modify(_.a)(_.description("A")) <-- current available
.modify(_.b)(_.description("B"))
.modify(_.c)(_.description("C"))
}
```
=> added description macro

integrations/cats/src/main/scala/sttp/tapir/codec/cats/TapirCodecCats.scala, integrations/cats/src/test/scala/sttp/tapir/codec/cats/TapirCodecCatsTest.scala
As discussed on [Gitter](https://gitter.im/softwaremill/tapir?at=5ea6abfc1eb8bd3978fa74de), I think the Cats codecs should use the schema (isOptional = false) and validator (size>=1) defined in the trait, this way the automatic documentation derivation works as expected.
=> Make Cats NonEmpty collections codecs use appropriate schemas and validators

json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala
A Product with no fields will encode to a schema of
```
type: object
```
which is exactly what we want.
=> Add Schema for io.circe.JsonObject

server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/EndpointToAkkaDirective.scala
The akka-server-backend implementation currently does not set the content-type of individual parts of a multipart request. This is a small PR to fix it. I spent a bit of time looking for a way to unit test this, but looking at how ServerTests are setup, I couldn't figure out a simple way to assert how the servers were generating the correct Part objects.
=> Set content-type of multipart parts

core/src/main/scala/sttp/tapir/Codec.scala, core/src/main/scala/sttp/tapir/CodecFormat.scala, core/src/main/scala/sttp/tapir/Tapir.scala
When working with tapir in our services, I realized there was no easy way to have tapir parse XML body.
I thought it would be good to add this feature to the official tapir library, as I'm sure many others can benefit from this, as XML is still used in many places today.
With this Users can simply create their own XML Codec via `Codec.xml()`, and then they will have the ability to use `xmlBody[T]` in both the request and response.
=> Add XML body type

README.md
Hello. I'm playing with `tapir` and `tapir-sttp-client` and I see there's no such package as `com.softwaremill.sttp` as stated in README.
I believe it could be a typo and it should be `import sttp.client._` instead.
I see the same issue in the docs here: https://tapir.softwaremill.com/en/latest/#code-teaser
Versions used:
```
"com.softwaremill.sttp.tapir" %% "tapir-core" % "0.16.0"
"com.softwaremill.sttp.tapir" %% "tapir-sttp-client" % "0.16.0"
```
=> Incorrect import declaration in README

server/play-server/src/main/scala/sttp/tapir/server/play/OutputToPlayResponse.scala
Hi everyone. There is no HTML case in `OutputToPlayResponse#formatToContentType` in Play server. 
There are also no such cases in akka-http and http4s servers but for them there are cases with `toString`:
```scala
case f                                => parseContentType(f.mediaType.toString())
```
I wonder if Play server should also work this way.
=> Play server crashes on HTML responses

build.sbt, core/src/main/scala/sttp/tapir/EndpointIO.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/ExampleInstances.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/instances.scala, integrations/cats/src/test/scala/sttp/tapir/integ/cats/ExampleFunctorLawSpec.scala, integrations/cats/src/test/scala/sttp/tapir/integ/cats/TapirCodecCatsTest.scala
This PR adds map function on Example, and Functor instance to cats module together with law test.
=> Add map and functor instance for Example

README.md, build.sbt, doc/openapi.md, docs/redoc-play/src/main/scala/sttp/tapir/redoc/play/RedocPlay.scala, docs/redoc-play/src/main/twirl/redoc.scala.html, docs/swagger-ui-play/src/main/scala/sttp/tapir/swagger/play/SwaggerPlay.scala, project/plugins.sbt, server/play-server/src/main/scala/sttp/tapir/server/play/TapirPlayServer.scala
We use Play heavily in our team, and thought it would be good to have tapir generate swagger UI and redoc routes for Play as well.
=> Adding Swagger UI and Redoc for Play

server/http4s-server/src/main/scala/sttp/tapir/server/http4s/EndpointToHttp4sServer.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/TapirHttp4sServer.scala
Here is implementation of feature which suggested in the [gitter](https://gitter.im/softwaremill/tapir?at=5f19439e7a668c64e9fdbcab) by @nigredo-tori :
```scala
def toHttp[I, E, O, G[_]: Sync](se: ServerEndpoint[I, E, O, EntityBody[F], G]): Http[OptionT[G, *], F]
```
For instance, when some `Context` required in the server logic we cat consider `G` like `ReaderT[F, Context, *]` and describe server endpoints as `ServerEndpoint[I, E, O, EntityBody[F], ReaderT[F, Context, *]]`.
=> Http4s server, add `EndpointToHttp4sServer.toHttp` method

.travis.yml
Follow up to https://github.com/softwaremill/tapir/pull/696
This change will cause the documentation to be compiled during CI runs, thus enforcing that it's always up-to-date.
=> Compile documentation on CI

core/src/main/scala/sttp/tapir/generic/internal/FormCodecDerivation.scala
This fixes the following warning generated when tapir is being
used with Scala 2.13:
```
method mapValues in trait MapOps is deprecated (since 2.13.0): Use .view.mapValues(f). A future version will include a strict version of this method (for now, .view.mapValues(f).toMap)
```
I am using tapir in my project with warnings-as-errors enabled. This
warning prevents me from using `.in(formBody[...])` with case
classes.
The idea to switch to `transform` which is compatible with Scala 2.11,
2.12 and 2.13 was originally found here: https://github.com/scala/scala-collection-compat/issues/216#issuecomment-505104324
=> Use `transform` when mapping Map values

docs/redoc-akka-http/src/main/scala/sttp/tapir/redoc/akkahttp/RedocAkkaHttp.scala, docs/swagger-ui-akka-http/src/main/scala/sttp/tapir/swagger/akkahttp/SwaggerAkka.scala, examples/src/main/scala/sttp/tapir/examples/BooksExample.scala, examples/src/main/scala/sttp/tapir/examples/MultipleEndpointsDocumentationAkkaServer.scala, examples/src/main/scala/sttp/tapir/examples/PartialServerLogicAkka.scala, server/akka-http-server/src/test/scala/sttp/tapir/server/akkahttp/AkkaHttpServerTests.scala
According to [akka doc](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/index.html#composing-directives-with-operator) 
> Gotcha: forgetting the ~ (tilde) character in between directives can result in perfectly valid Scala code that compiles but does not work as expected. What would be intended as a single expression would actually be multiple expressions, and only the final one would be used as the result of the parent directive. Because of this, the recommended way to compose routes is with the the concat combinator.
So i changed all tildes into concats
=> Remove tildes

build.sbt, integrations/refined/src/main/scala/sttp/tapir/codec/refined/TapirCodecRefined.scala, integrations/refined/src/test/scala/sttp/tapir/codec/refined/TapirCodecRefinedTest.scala
Additional implicit which prevent `diverging implicit expansion for type T` compilation errors. Solves #643.
This PR replaces #752.
=> Improve inference of codecs while using refined

doc/endpoint/statuscodes.md
I was going through the docs and was a little confused by the note around type erasure, so I tried to simplify it a bit.
=> wordsmith type-erasure issue with status mappings

core/src/main/scala/sttp/tapir/Codec.scala, core/src/test/scala/sttp/tapir/CodecTest.scala
Javatime codecs should serialize dates and times with formats that are used to parse them. 
Tapir uses OffsetDateTime's .toString to encode Instants, but you can't parse back some of its outputs:
```scala
import java.time.Instant
import sttp.tapir.Codec.instant
val epoch = instant.encode(Instant.EPOCH)
// epoch: String = 1970-01-01T00:00Z
Instant.parse(epoch)
// java.time.format.DateTimeParseException: Text '1970-01-01T00:00Z' could not be parsed at index 16
```
I think it's better to be more explicit about formats and not to rely on .toString for javatime codecs.
=> Use DateTimeFormatter for javatime codecs

generated-doc/out/other_interpreters.md
It's fairly clear that [tapir-gen](https://github.com/xplosunn/tapir-gen) is a dead project so I've removed it from the docs. If it ever starts up again, we can add it back.
=> remove tapir-gen from the docs

build.sbt, sbt/sbt-openapi-codegen/src/main/scala/OpenapiCodegenPlugin.scala, sbt/sbt-openapi-codegen/src/main/scala/OpenapiCodegenTask.scala, sbt/sbt-openapi-codegen/src/main/scala/codegen/BasicGenerator.scala, sbt/sbt-openapi-codegen/src/main/scala/codegen/ClassDefinitionGenerator.scala, sbt/sbt-openapi-codegen/src/main/scala/codegen/EndpointGenerator.scala, sbt/sbt-openapi-codegen/src/main/scala/codegen/openapi/models/OpenapiModels.scala, sbt/sbt-openapi-codegen/src/main/scala/codegen/openapi/models/OpenapiSchemaType.scala, sbt/sbt-openapi-codegen/src/test/scala/codegen/BasicGeneratorSpec.scala, sbt/sbt-openapi-codegen/src/test/scala/codegen/ClassDefinitionGeneratorSpec.scala, sbt/sbt-openapi-codegen/src/test/scala/codegen/EndpointGeneratorSpec.scala, sbt/sbt-openapi-codegen/src/test/scala/codegen/TestHelpers.scala, sbt/sbt-openapi-codegen/src/test/scala/codegen/openapi/models/ModelParserSpec.scala, sbt/sbt-openapi-codegen/src/test/scala/codegen/openapi/models/SchemaParserSpec.scala, sbt/sbt-openapi-codegen/src/test/scala/codegen/testutils/CompileCheckTestBase.scala, sbt/sbt-openapi-codegen/src/test/scala/codegen/testutils/CompileCheckTestBaseSpec.scala
Added a new `shouldCompile ()` test helper, split the generator into three classes, and made the class generator a bit smarter.
I think my next candidates are;
- support tags to endpoints
- changeable package name and generated object name
- changeable json lib
Do you have a list of public projects with tapir interfaces to create a larger e2e test set?
Its a follow up to #810
> if you think it's worthy, you can add a hacktoberfest-accepted label to this PR ;)
=> Openapi codegen tests and better class generator

.github/workflows/test.yml
Follow-up to #854 to fix the OOM error.
It also adds a build matrix to run the JVM and the JS tests in parallel which should speed up the CI tests considerably.
=> Add build matrix and increase heap space in CI to avoid OOM errors

doc/endpoint/auth.md
Tapir will currently _not_ provide headers automatically which would
make a browser show a login prompt if `auth.basic` is used.
=> Add notice regarding authentication headers.

docs/swagger-ui-akka-http/src/main/scala/sttp/tapir/swagger/akkahttp/SwaggerAkka.scala
This solves #694 without an API change. No deprecations are necessary.
=> Allow swagger-ui to run on a non-root context-path. Solves #694.

core/src/main/scala/sttp/tapir/Codec.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/decoders/VertxInputDecoders.scala, tests/src/main/scala/sttp/tapir/tests/package.scala
This is fix for https://github.com/softwaremill/tapir/issues/875
While fixing codec itself it turned out that Vertx server interpreter skipped fields that were not part of `MultipartBody.partTypes`
=> Fix for ClassCastException when using default multipart codec

.gitignore, build.sbt, core/src/main/scala/sttp/tapir/DecodeResult.scala, core/src/main/scala/sttp/tapir/server/ServerDefaults.scala, core/src/test/scala/sttp/tapir/JsonDecodeExceptionTests.scala, json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala, json/circe/src/test/scalajvm/sttp/tapir/json/circe/TapirJsonCirceTests.scala, json/jsoniter/src/main/scala/sttp/tapir/json/jsoniter/TapirJsonJsoniter.scala, json/jsoniter/src/test/scala/sttp/tapir/json/jsoniter/TapirJsonJsoniterTests.scala, json/playjson/src/main/scala/sttp/tapir/json/play/TapirJsonPlay.scala, json/playjson/src/test/scala/sttp/tapir/json/play/TapirJsonPlayTests.scala, json/sprayjson/src/main/scala/sttp/tapir/json/spray/TapirJsonSpray.scala, json/sprayjson/src/test/scala/sttp/tapir/json/spray/TapirJsonSprayTests.scala, json/tethys/src/main/scala/sttp/tapir/json/circe/TapirJsonTethys.scala, json/tethys/src/test/scala/sttp/tapir/json/circe/TapirJsonTethysTests.scala, json/upickle/src/main/scala/sttp/tapir/json/upickle/TapirJsonuPickle.scala, json/upickle/src/test/scala/sttp/tapir/json/upickle/TapirJsonuPickleTests.scala
This PR introduces a `JsonDecodeException`, it aims to improve JSON-specific decode errors handling. 
In its current implementation, this PR allows to output JSON decode errors in responses when wrongly formatted JSONs bodies are submitted. 
For example, using Play-JSON and given an endpoint expecting a
```scala
case class User(name: String)
```
in request body, sending 
```json
{}
``` 
will output `error.path.missing at 'obj.name'` in the response body alongside with the 404 status code.
Errors and failed paths are populated according to what JSON-libraries provide. 
Default behavior of decode errors handling was changed to output detailed JSON decode errors, when available.
Closes https://github.com/softwaremill/tapir/issues/872.
=> JSON specific decode errors

build.sbt
This removes a lot of false warnings about unused implicit arguments
=> Add "-Ywarn-macros:after" option

apispec/openapi-model/src/main/scala/sttp/tapir/openapi/OpenAPI.scala, core/src/main/scala/sttp/tapir/Endpoint.scala, core/src/main/scala/sttp/tapir/internal/package.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOperationResponse.scala, docs/openapi-docs/src/test/resources/expected_the_same_status_codes.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala
Accordingly OpenAPI documentation one status code may have several response schemas with different media types. For example,
```
"200": {
"description": "a pet to be returned",
"content": {
"application/json": {
"schema": {
"$ref": "#/components/schemas/Pet"
}
},
"text/plain": {
"schema": {
"type": "string"
}
}
}
}
```
But function RichEndpointOutput.asBasicOutputsList returns map from status code to response. So OpenAPI contains only one response per status code.
=> Handle responses with the same status code and different media types

client/sttp-client/src/main/scala/sttp/tapir/client/sttp/SttpClientInterpreter.scala, client/sttp-client/src/main/scala/sttp/tapir/client/sttp/internal/Util.scala, client/sttp-client/src/main/scalajs/sttp/tapir/client/sttp/SttpClientInterpreterExtensions.scala, client/sttp-client/src/main/scalajvm/sttp/tapir/client/sttp/SttpClientInterpreterExtensions.scala
I'm trying to replicate spring-like (the good parts :) ) experience creating http clients.
Given an endpoint `Endpoint[I, E, O]` I want to easily create create clients of types `I => Either[E, O]`, `I => O`, `I => ZIO[Any, E, O]`... 
Currently I have to first create an interpreter (so, deal with `Request` and `Response` objects), then create a backend (so, probably deal with HKTs) and then do some plumbing.
This PR tries to
1) add `toClientUnsafe` method that puts together a backend and an interpreter
2) add helper methods for creating minimalistic synchronous backends
If this direction is right, let's also add Fetch and AsyncHttp backends
=> make creation of http clients easier

core/src/main/scala/sttp/tapir/generic/internal/CaseClassUtil.scala, core/src/main/scala/sttp/tapir/generic/internal/EndpointAnnotations.scala, core/src/main/scala/sttp/tapir/generic/internal/EndpointInputAnnotations.scala, core/src/main/scala/sttp/tapir/generic/internal/FormCodecDerivation.scala, core/src/main/scala/sttp/tapir/generic/internal/MagnoliaDerivedMacro.scala, core/src/main/scala/sttp/tapir/generic/internal/MultipartCodecDerivation.scala, core/src/main/scala/sttp/tapir/generic/internal/OneOfMacro.scala, core/src/main/scala/sttp/tapir/generic/internal/SchemaMapMacro.scala, core/src/main/scala/sttp/tapir/generic/internal/ValidatorEnumMacro.scala, core/src/main/scala/sttp/tapir/internal/ModifySchemaMacro.scala, core/src/main/scala/sttp/tapir/internal/StatusMappingMacro.scala
I have mechanically gone through and made the macros hygienic by fully-qualifying every type used in quasiquotes. (With the exception of some in `OneOfMacro`—I didn't have time to look up where all of the types are defined, so I added a FIXME.) If nobody gets there before me, I may get a chance to come back to this later...
How well-tested are the macros? I've made quite a lot of changes, and a small typo would certainly break that macro. Can I rely on CI to tell me if I've made a mistake?
=> Include the `_root_` prefix in quasiquotes to ensure macro hygiene

docs/redoc-http4s/src/main/resources/redoc.html, docs/redoc-http4s/src/main/scala/sttp/tapir/redoc/http4s/RedocHttp4s.scala
Hi,
Thank you for creating this library.
A very small contribution allowing to specify which Redoc version you want to use with Http4sRedoc.
Actually, the version used (rc.22) has a real annoying bug: https://github.com/Redocly/redoc/issues/1177
=> Add redocVersion parameter for RedocHttp4s 

build.sbt, core/src/main/scala/sttp/tapir/server/internal/EncodeOutputs.scala, doc/server/vertx.md, project/Versions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxEndpointOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/decoders/VertxDecodeInputsContext.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/decoders/VertxInputDecoders.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/decoders/VertxServerRequest.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/encoders/VertxOutputEncoders.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/encoders/package.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/handlers/package.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/interpreters/CommonInterpreter.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/interpreters/VertxCatsServerInterpreter.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/interpreters/VertxFutureServerInterpreter.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/interpreters/VertxZioServerInterpreter.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/package.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/routing/MethodMapping.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/routing/PathMapping.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/streams/ReadStreamCompatible.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/streams/domain.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/streams/fs2.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/streams/zio.scala, server/vertx/src/test/scala/sttp/tapir/server/vertx/CatsVertxServerTests.scala, server/vertx/src/test/scala/sttp/tapir/server/vertx/CatsVertxTestServerInterpreter.scala, server/vertx/src/test/scala/sttp/tapir/server/vertx/VertxBlockingServerTests.scala, server/vertx/src/test/scala/sttp/tapir/server/vertx/VertxServerTests.scala, server/vertx/src/test/scala/sttp/tapir/server/vertx/VertxTestServerBlockingInterpreter.scala, server/vertx/src/test/scala/sttp/tapir/server/vertx/streams/FakeStream.scala, server/vertx/src/test/scala/sttp/tapir/server/vertx/streams/Fs2StreamTest.scala, server/vertx/src/test/scala/sttp/tapir/server/vertx/streams/ZStreamTest.scala
I would to make some changes in vertx interpreter to support streaming and zio.
I replaced `vertx-web-scala` by plain java `vertx-web` because:
1. `vertx-web-scala` is only available for scala 2.12. Using java `vertx-web` we can compile this interpreter even for dotty.
2. `vertx-web-scala` replaces `io.vertx.core.Future` by scala `Future` and it doesn't allow interrupt evaluation of effect if connection is already closed.
I added two new interpreters `ZioVertxServerInterpreter` and `CatsVertxServerInterpreter`. Both interpreters support interruption and streaming. `CatsVertxServerInterpreter` supports streaming based on fs2 streams. `ZioVertxServerInterpreter` supports ZStreams.
Work is still in progress. I need to make more tests. But it seems that general functionality already works. …
=> Support cats and zio in vertx interpreter

core/src/main/scala/sttp/tapir/EndpointIO.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/EndpointIOInstances.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/instances.scala, integrations/cats/src/test/scala/sttp/tapir/integ/cats/EndpointIOInstancesSpec.scala
Closes #1020
This turned out to be less useful than I imagined. :frowning: Combinators in `sttp.tapir` tend to return specific subtypes of `EndpointInput` etc., which means that the tuple doesn't get unified to the type we can have an instance for. A little nudge (specifying a wider type for an element of the tuple) helps, but that's ugly. Still, this notation might be useful when combining a lot of inputs.
I'm also not sure about `InvariantMonoidal`. It's possible to make an instance of it for `EndpointInput`, but that would expose the package-private value `emptyInput` as `unit` - I'm not sure we want that. However, I did add an instance of `InvariantMonoidal[EndpointOutput]`. This is based on the assumption that `emptyOutput` is an identity WRT `and`. From what I can see, this should …
=> Add InvariantSemigroupal instances for Endpoint(Input|IO|Output)

integrations/cats/src/main/scala/sttp/tapir/integ/cats/ModifyFunctorInstances.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/TapirCodecCats.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/instances.scala, integrations/cats/src/test/scala/sttp/tapir/integ/cats/ModifyFunctorInstancesTest.scala
Adding instances of `ModifyFunctor` for cats.data collections, so we can modify schemas of such collections (https://tapir.softwaremill.com/en/latest/endpoint/customtypes.html#customising-derived-schemas)
=> Add instances of ModifyFunctor for cats.data collections

json/playjson/src/main/scala/sttp/tapir/json/play/TapirJsonPlay.scala, json/playjson/src/test/scalajvm/sttp/tapir/json/play/TapirJsonPlayTestExtensions.scala
Currently, when submitting an invalid JSON document such as (missing comma):
```json
{
"title": "Pride and Prejudice"
"year": 1813
}
```
to an endpoint using Play-JSON, the output will be the following:
```
Invalid value for: body
```
this PR allows to produce this output instead:
```
Invalid value for: body (Unexpected character ('"' (code 34)): was expecting comma to separate Object entries
at [Source: (String)"{
"title": "Pride and Prejudice"
"year": 1813
}"; line: 3, column: 4])
```
=> fixed Play JSON error message when input is not a valid JSON document

core/src/main/scala/sttp/tapir/Schema.scala, integrations/refined/src/main/scala/sttp/tapir/codec/refined/TapirCodecRefined.scala
Thanks to that in OpenAPI the format of string is visible: `string($uuid)`
=> Add schema for uuid

server/finatra-server/src/main/scala/sttp/tapir/server/finatra/FinatraDecodeInputsContext.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sDecodeInputsContext.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayDecodeInputContext.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/decoders/VertxDecodeInputsContext.scala
Fixes https://github.com/softwaremill/tapir/issues/896.
Http4s, Play, Finatra and Vert.x all seem to decode URL path segments. For each server interpreter, I used the same decoder as in the original implementation.
Links to the code where decoding seems to be done in the original implementations:
- [http4s](https://github.com/http4s/http4s/blob/c5509ce4bbe47398229e5c16f38f9a2eb5d58433/core/src/main/scala/org/http4s/Uri.scala#L390) 
- Play: [(1)](https://github.com/playframework/playframework/blob/814f0c73f86eb0e85bcae7f2167c73a08fed9fd7/core/play/src/main/scala/play/api/routing/sird/PathExtractor.scala#L38) [(2)](https://github.com/playframework/playframework/blob/814f0c73f86eb0e85bcae7f2167c73a08fed9fd7/core/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala#L57)
- …
=> fix(server): URL-decode captured path segments

server/http4s-server/src/main/scala/sttp/tapir/server/http4s/OutputToHttp4sResponse.scala, server/http4s-server/src/test/scala/sttp/tapir/server/http4s/Http4SCreateServerTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerStreamingTests.scala
If we want to stream data using HTTP4s we have to add the `Transfer-Encoding` header (according to https://http4s.org/v0.18/dsl/). If `chunked` `Transfer-Encoding` is used, then the `Content-Length` should not be included (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding)
=> Add Transfer-Encoding header while streaming data and using HTTP4s

build.sbt, doc/endpoint/integrations.md, integrations/derevo/src/main/scala/sttp/tapir/derevo/schema.scala, integrations/derevo/src/test/scala/sttp/tapir/derevo/DerevoSchemaDerivationSpec.scala, project/Versions.scala
Derevo recently got support for newtypes (NB it does not need a dependency on any of the newtype libraries) and also changed the organization.
This PR addresses both of those changes.
=> Update derevo integration;

build.sbt, client/http4s-client/src/main/scala/sttp/tapir/client/http4s/EndpointToHttp4sClient.scala, client/http4s-client/src/main/scala/sttp/tapir/client/http4s/Http4sClientInterpreter.scala, client/http4s-client/src/main/scala/sttp/tapir/client/http4s/Http4sClientOptions.scala, client/http4s-client/src/test/scala/sttp/tapir/client/http4s/Http4ClientStreamingTests.scala, client/http4s-client/src/test/scala/sttp/tapir/client/http4s/Http4sClientBasicTests.scala, client/http4s-client/src/test/scala/sttp/tapir/client/http4s/Http4sClientTests.scala, doc/client/http4s.md, doc/index.md, examples/src/main/scala/sttp/tapir/examples/Http4sClientExample.scala
Partly fixes https://github.com/softwaremill/tapir/issues/713. As yet the interpreter doesn't support WebSockets or multipart requests.
=> feature: implement http4s client interpreter

core/src/main/scala/sttp/tapir/Tapir.scala, core/src/test/scala/sttp/tapir/EndpointTest.scala, generated-doc/out/endpoint/statuscodes.md
The recommended use of `oneOf` combinator for outputs involves providing outputs for every sub-type of a coproduct (`sealed trait`). For parameterless case objects you will often want an empty body output. 
Right now the only convenient way of declaring an empty body `Endpoint.Output` is by using the `emptyOutput` value. Using this will then require a `.map(_ => ...)(_ => ())` conversion. This piece of boiler-plate adds noise to the code and its necessity can make it harder to discover the correct pattern for defining `oneOf` statements. 
The method I add removes the need for boilerplate and covers a large number of empty body use cases.
=> [Minor] Add convenience method for empty outputs 

build.sbt
Hi,
This PR allows to use endpoints with newtype in a scala.js context.
I was able to `+publishLocal` and use the generated artifacts in a shared module js/jvm where the endpoints are defined.
These endpoints are then used from frontend (js) and backend (jvm) modules.
Please, let me know if it requires some extra changes in order to be merged.
Regards,
=> Add newtype support for scala.js

build.sbt, integrations/zio/src/main/scala/sttp/tapir/ztapir/ZPartialServerEndpoint.scala, integrations/zio/src/main/scala/sttp/tapir/ztapir/ZServerEndpointInParts.scala, integrations/zio/src/main/scala/sttp/tapir/ztapir/ZTapir.scala, integrations/zio/src/test/scala/sttp/tapir/ztapir/TestError.scala, integrations/zio/src/test/scala/sttp/tapir/ztapir/ZTapirTest.scala, integrations/zio/src/test/scala/sttp/tapir/ztapir/instances/TestMonadError.scala, server/zio-http4s-server/src/main/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sServerInterpreter.scala
It fixes following issues related to ZIO:
* By default, errors from failure channel are forwarded to the main entry point (omitting Tapir and Http4s error handling). This causes the server to terminate in the case of an error that is not of type `E` (e.g. caused by `Task(10/0).orDie`).
* `Http4sServerOptions` is not passed to the next method, but is silently ignored. This causes any changes we make are ignored, instead the default `Http4sServerOptions` is used.
=> Fix ZIO issues

docs/swagger-ui-play/src/main/scala/sttp/tapir/swagger/play/SwaggerPlay.scala
This aims to fix https://github.com/softwaremill/tapir/issues/1272
I've tested it manually on a Play project of mine but I admit I did not spend time writing a proper test in the project as there was no existing test and not sure how to write such a test.
=> fix: 🐛 #1272 Allow exposing Swagger on a non-root route

docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/CodecToMediaType.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOpenAPIPaths.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOperationResponse.scala, docs/openapi-docs/src/test/resources/expected_explicit_content_type_header.yml, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, tests/src/main/scala/sttp/tapir/tests/package.scala
Closes  https://github.com/softwaremill/tapir/issues/1280
=> Add fix for explicit content-type header priority issue

README.md, build.sbt, client/http4s-client/src/main/scala/sttp/tapir/client/http4s/EndpointToHttp4sClient.scala, client/http4s-client/src/test/scala/sttp/tapir/client/http4s/Http4sClientRequestTests.scala
Fixes https://github.com/softwaremill/tapir/issues/1306
=> fix(http4s-client): exclude empty query params from URI

docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/openapi-docs/src/test/resources/enum/expected_enumeratum_enum_collection_component.yml, docs/openapi-docs/src/test/resources/enum/expected_enumeratum_enum_component.yml, docs/openapi-docs/src/test/scala-2/sttp/tapir/docs/openapi/VerifyYamlEnumerationTest.scala
I've found that during documentation generation if a class contains an optional enum field then `referenceEnums` isn't affecting the result.
For example, if I have the enum:
```scala
sealed abstract class MyEnum extends EnumEntry
object MyEnum extends Enum[MyEnum] {
case object Foo1 extends MyEnum
case object Foo2 extends MyEnum
override def values: immutable.IndexedSeq[MyEnum] = findValues
}
```
and use it in the class:
```scala
case class MyResult(enumField: MyEnum, enumFieldOpt: Option[MyEnum])
```
Then generated documentation would use a reference to specify the type of `enumField` and will inline all options for `enumFieldOpt`.
I've found that the problem was inside `TSchemaToASchema.scala` because was not handled in a case when an option field might contain an enum.
=> fixed referencing enums for optional fields

apispec/apispec-model/src/main/scala/sttp/tapir/apispec/SecurityScheme.scala, core/src/main/scala/sttp/tapir/EndpointIO.scala, core/src/main/scala/sttp/tapir/TapirAuth.scala, docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlSecurityTest.scala, examples/src/main/scala/sttp/tapir/examples/OAuth2GithubHttp4sServer.scala
=> Make authorizationUrl optional

build.sbt, client/http4s-client/src/main/scala/sttp/tapir/client/http4s/EndpointToHttp4sClient.scala, docs/swagger-ui-http4s/src/main/scala/sttp/tapir/swagger/http4s/SwaggerHttp4s.scala
Enables for following modules for scala 3. 
* `testing-server`
* `tapir-swagger-ui-http4s`
*  `tapir-redoc-http4s`
*  `tapir-http4s-client`
Only a slight type description for SwaggerHttp4s.scala needed for compilation.
=> Enable more http4s modules for scala 3

build.sbt, doc/docs/openapi.md, doc/examples.md, docs/swagger-ui-zio-http/src/main/scala/sttp/tapir/swagger/ziohttp/SwaggerZioHttp.scala, examples/src/main/scala/sttp/tapir/examples/ExampleZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/ZioExampleZioHttpServer.scala
Add support for serving swagger docs via zio-http
=> Add SwaggerZioHttp

json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala, json/circe/src/test/scalajvm/sttp/tapir/json/circe/TapirJsonCirceTests.scala
=> Use strings for big decimal schemas when using circe

json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala, json/circe/src/test/scalajvm/sttp/tapir/json/circe/TapirJsonCirceTests.scala
The purpose of this PR is just to enable error accumulation for Circe users. 
Currently if there are missing keys in the Json(or typo) the error from Tapir is just for the first missing key
So, in this case:
```scala
case class Person(name: String, surname: String, age: Int)
```
```json
{
"name": "Foo"
}
```
We have an error that say `Attempt to decode value on failed cursor at 'name'` but nothing for `age`.
Using `decodeAccumulating` from `Circe` we'll have all errors and not only the first one.
```
Attempt to decode value on failed cursor at 'name'
Attempt to decode value on failed cursor at 'age'
```
=> Enable errors accumulations by default with Circe

server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerTest.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerWithContextTest.scala
(cherry picked from commit 343995a5680fb79527897d1f5cef9fdd674149b4)
=> #1400: fix play server interpreter when routes are put in context for 0.18

build.sbt, server/play-server/src/main/scala/sttp/tapir/server/play/PlayRequestBody.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayToResponseBody.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerTest.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayTestServerInterpreter.scala
This aims to solve #1385.
It's a draft because only the response as stream is implemented for now: I'm not sure how to implement request as a stream.
Either:
- we accept to implement only for response and not request (but then either we remove the tests about streaming or we split them in streaming request vs streaming response)
- or, we wait until finding the good way to implement request streaming (`PlayRequestBody#toStream()`)
=> Support AkkaStreams capacity in Play server interpreter

json/zio/src/main/scala/sttp/tapir/json/zio/TapirJsonZio.scala, json/zio/src/test/scalajvm/sttp/tapir/json/zio/TapirJsonZioTest.scala
The same case as #321 and #1405.
=> Use numbers for BigDecimal schemas when using zio-json

integrations/enumeratum/src/main/scala/sttp/tapir/codec/enumeratum/TapirCodecEnumeratum.scala
- Leave the existing one as the default but add a case-insensitive method too.
- Thought about adding similar methods for upper/lower/other cases but I think the `enumeratum` stackable traits should address those needs, perhaps. Can add.
=> [Minor] Add case insensitive enumeratum codec

core/src/main/scala/sttp/tapir/internal/package.scala, core/src/test/scala/sttp/tapir/internal/RichEndpointOutputTest.scala
Hi softwaremill,
thanks for tapir, I think it is an interesting approach. 
I stumbled upon an issue: since the media type parser retains the case of the charset, a comparison with the (uppercase) charset name might fail (for example when a service mesh/API gateway lowercases all headers, which is still valid). See the test case.
In my fix attempt, the comparison is now using the `matches` method of `MediaType` which already takes this into account.
=> (core): fix output media type matching

server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerRequest.scala
Play's `Request` may contain additional context like authentication when it is produced by `ActionBuilder`. Access to that data was possible it Tapir 0.18.1 by casting `ServerRequest.underlying` to type that is produced by `defaultActionBuilder`.
Unfortunately, this was broken in 0.18.3. Fix in #1423 replaced `Request` with `RequestHeader` that misses that context.
This pull request provider better fix for #1400, that fixes that problem without affecting `underlying`. In Play Framework, any `Request` extends `RequestHeader`, so this change is backward compatible and should no break code that works with 0.18.3.
=> Fix access to underlying request in PlayServerInterpreter

core/src/main/scala/sttp/tapir/Validator.scala, core/src/test/scala/sttp/tapir/ValidatorTest.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/TapirCodecCats.scala, integrations/cats/src/main/scala/sttp/tapir/integ/cats/ValidatorCats.scala, integrations/cats/src/test/scala/sttp/tapir/integ/cats/ValidatorCatsTest.scala
Hi, I'm trying to split my last PR (https://github.com/softwaremill/tapir/pull/1467) since it was too big.
With this PR  i'd like to add some new Validators such:
- positive
- positiveOrZero
- negative
- inRange
- fixedLength 
- nonEmptyString
- nonEmpty
- fixedSize
- nonEmptyFoldable
=> Add new validators

server/play-server/src/main/scala/sttp/tapir/server/play/PlayRequestBody.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerTest.scala
Closes #1583
Play doesn't expose headers, but it exposes `contentType` which can be set as a header so that it is accessible on tapir side.
=> Set content type header in Part when using PlayServerInterpreter

doc/endpoint/basics.md
Found what looks like a little typo. `S` is not described in the section below, but `R` is.
=> Fixed typo

core/src/main/scala/sttp/tapir/server/interpreter/DecodeBasicInputs.scala, core/src/test/scala/sttp/tapir/server/interpreter/DecodeBasicInputsResultTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, tests/src/main/scala/sttp/tapir/tests/Basic.scala
=> Omit boundary when decoding fixed content-type header

core/src/main/scala/sttp/tapir/internal/package.scala, core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureHandler.scala, doc/server/errors.md, doc/server/options.md, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/SecuritySchemesForEndpoints.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/EndpointToAsyncAPIDocs.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/EndpointToAsyncAPIWebSocketChannel.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOpenAPIPaths.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOperationResponse.scala, server/finatra-server/src/main/scala/sttp/tapir/server/finatra/FinatraServerInterpreter.scala, server/tests/src/main/scala/sttp/tapir/server/tests/CreateServerTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerSecurityTests.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/handlers/package.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/routing/PathMapping.scala, serverless/aws/lambda-tests/src/test/scala/sttp/tapir/serverless/aws/lambda/tests/AwsLambdaCreateServerStubTest.scala, serverless/aws/sam/src/main/scala/sttp/tapir/serverless/aws/sam/EndpointsToSamTemplate.scala, serverless/aws/terraform/src/main/scala/sttp/tapir/serverless/aws/terraform/EndpointsToTerraformConfig.scala
Return 404 instead of a 401/400
=> Enables hiding endpoints with auth inputs if any inputs fails to decode

client/http4s-client/src/main/scala/sttp/tapir/client/http4s/EndpointToHttp4sClient.scala, client/play-client/src/main/scala/sttp/tapir/client/play/EndpointToPlayClient.scala, client/tests/src/main/scala/sttp/tapir/client/tests/ClientBasicTests.scala
When building a http4s request, currently `addPath` is used to append segments to the path. Which results in the string being split by `/` and added as multiple segments (URL-encoding them).
So right now it's impossible to have a path segment that contains a `/` symbol (an edge case, but still):
* if you pre-url-encode it – http4s will encode it again, and you get the double encoded `/`: `/` -> `%2f` -> `%252f`
* if you don't url-encode it – it ends up "unencoded" in the resulting URI, causing a segment split
In either case, you can't get the desired `%2f` encoding.
=> use `addSegment` instead of `addPath` for http4s

build.sbt
This unnecessary dependency brings the whole cats ecosystem 😭
=> Don't depend on zio-interop-cats in tapir-zio-http-server

core/src/main/scala/sttp/tapir/server/interceptor/DecodeSuccessContext.scala, core/src/main/scala/sttp/tapir/server/interpreter/ServerInterpreter.scala
As discussed on gitter, the current name are not really expressing what those parameters represents.
=> Rename DecodeSuccessContext parameters

doc/endpoint/schemas.md, generated-doc/out/endpoint/schemas.md
https://tapir.softwaremill.com/en/latest/endpoint/schemas.html is pointing to https://propensive.com/opensource/magnolia/ which is giving a 404. The project migrated to https://github.com/softwaremill/magnolia
I wasn't sure if I should touch files in `generated-doc` directory. I erred on the side of doing it, happy to amend if it should be excluded.
=> Point to softwaremill/magnolia

core/src/main/scala-2/sttp/tapir/macros/EndpointMacros.scala, core/src/test/scala/sttp/tapir/EndpointTest.scala
fixed passing A (security) instead of I (input) parameter for mapSecurityInTo
=> fixed mapSecurityInTo

README.md, doc/quickstart.md
-Ypartial-unification is now on by default in Scala 2.13, and actually gives an error (Error: scalac: bad option).
=> Scala 2.13 partial unification comment

core/src/main/scala-2/sttp/tapir/generic/internal/SchemaMagnoliaDerivation.scala, core/src/main/scala-3/sttp/tapir/internal/SchemaMagnoliaDerivation.scala, core/src/test/scala-2/sttp/tapir/SchemaMacroTest2.scala, core/src/test/scala-2/sttp/tapir/SchemaMacroTestData2.scala
I don't know if there is something better we can do for the reported case for scala2 (we could probably implement some macro to do the check in compile time but is it worth the effort)? I added the test in scala2 sources since for scala3 it won't compile although not mentioning the `Num` class specifically in the message.
=> require value class parameters list to not be empty

client/http4s-client/src/main/scala/sttp/tapir/client/http4s/EndpointToHttp4sClient.scala, client/http4s-client/src/main/scala/sttp/tapir/client/http4s/Http4sClientInterpreter.scala, client/http4s-client/src/test/scala/sttp/tapir/client/http4s/Http4sClientTests.scala, client/play-client/src/main/scala/sttp/tapir/client/play/EndpointToPlayClient.scala, client/play-client/src/main/scala/sttp/tapir/client/play/PlayClientInterpreter.scala, client/play-client/src/test/scala/sttp/tapir/client/play/PlayClientTests.scala, doc/client/http4s.md, doc/client/play.md, doc/client/sttp.md, generated-doc/out/client/play.md
=> Consistent naming of client interpreter methods, fixing docs

client/tests/src/main/scala/sttp/tapir/client/tests/ClientMultipartTests.scala, core/src/main/scala/sttp/tapir/Codec.scala
when I use multipart upload, it shows error like this.
```
[info] - Endpoint[echo raw parts](securityin: -, in: POST /api /echo /multipart {body as multipart/form-data}, errout: -, out: {body as text/plain (UTF-8)}) *** FAILED *** (2 milliseconds)
[info]   java.lang.ClassCastException: class sttp.model.Part cannot be cast to class scala.collection.immutable.List (sttp.model.Part is in unnamed module of loader sbt.internal.LayeredClassLoader @9cb3542; scala.collection.immutable.List is in unnamed module of loader sbt.internal.ScalaLibraryClassLoader @13aa12e4)
[info]   at sttp.tapir.Mapping$$anon$4.encode(Mapping.scala:60)
[info]   at sttp.tapir.Codec$$anon$1.encode(Codec.scala:75)
[info]   at sttp.tapir.Codec$$anon$2.encode(Codec.scala:93)
[info]   at …
```
=> fix multiPart upload codec

server/play-server/src/main/scala/sttp/tapir/server/play/PlayToResponseBody.scala
Aims to close #1799 
If content length is known, use `HttpEntity.Streamed`, otherwise use `HttpEntity.Chunked`.
=> fix: 🐛 (Play Server) Use HttpEntity.Chunked when possible

build.sbt, client/sttp-client-ws-zio1/src/main/scalajvm/sttp/tapir/client/sttp/ws/zio1/TapirSttpClientZioWebSockets.scala, client/sttp-client-ws-zio1/src/main/scalajvm/sttp/tapir/client/sttp/ws/zio1/WebSocketToZioPipe.scala, client/sttp-client-ws-zio1/src/main/scalajvm/sttp/tapir/client/sttp/ws/zio1/package.scala, client/sttp-client-ws-zio1/src/test/scalajvm/sttp/tapir/client/sttp/SttpClientWebSocketZioTests.scala, client/sttp-client-ws-zio1/src/test/scalajvm/sttp/tapir/client/sttp/SttpClientZioTests.scala, client/sttp-client/src/test/scalajvm/sttp/tapir/client/sttp/SttpClientStreamingZioTests.scala, project/Versions.scala
Follow up to https://github.com/softwaremill/tapir/pull/1807#issuecomment-1027261041
Migrate `tapir-sttp-client` to ZIO 2.0 and add `tapir-sttp-client-ws-zio1` for ZIO 1.0. I used package name `zio1` to prevent the conflict.
=> Support ZIO 1.0 and ZIO 2.0 for sttp ws

core/src/main/scala-2/sttp/tapir/generic/internal/SchemaMagnoliaDerivation.scala, core/src/main/scala-3/sttp/tapir/internal/SchemaMagnoliaDerivation.scala, core/src/main/scala/sttp/tapir/generic/Configuration.scala, core/src/test/scala/sttp/tapir/generic/SchemaGenericAutoTest.scala
Without `discriminatorMapping` the OpenAPI generator can't make sense of the schema and fails.
---
I'm not sure if adding fields to `Configuration` was a right call – this breaks bin-compat, but I can re-work things here to re-use `toEncodedName` (and deal with the `$` suffix on the call site).
=> add discriminatorMapping when deriving a schema for co-products

server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxCatsServerOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxFutureServerOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxServerOptions.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxZioServerInterpreter.scala, server/vertx/src/main/scala/sttp/tapir/server/vertx/VertxZioServerOptions.scala
Now task cancelation is executed on main vertx pool. But task cancelation may be blocking operation. Here is such example:
```scala
import zio._
import zio.blocking.Blocking
val task =
for {
blocking <- ZIO.service[Blocking.Service]
_ <- blocking.effectBlocking({
println(Thread.currentThread().getName())
Thread.sleep(5000)
println("end")
})
} yield ()
val runtime = Runtime.default
val canceler = runtime.unsafeRunAsyncCancelable(task) { _ => () }
canceler(Fiber.Id.None) // this call is blocked by Thread.sleep(5000)
```
So interrupting of several tasks may block main vertx pool and leads to following warnings
```
Thread Thread[vert.x-eventloop-thread-1,5,zio-default-async] has been blocked for 6381 ms, time limit is 2000 ms
```
So it is better to execute this operation on blocking pool.
=> Move task cancelation on blocking pool

core/src/main/scala-2/sttp/tapir/generic/internal/EndpointAnnotationsMacro.scala, core/src/main/scala-2/sttp/tapir/internal/CaseClassUtil.scala, core/src/main/scala-3/sttp/tapir/internal/AnnotationsMacros.scala, core/src/main/scala-3/sttp/tapir/internal/CaseClass.scala
Replace the method with simpler pattern matching.
=> Simplify the extractTreeAndOptTreeFromAnnotation method

core/src/main/scala/sttp/tapir/package.scala
One type parameter for `PublicEndpoint` alias was labeled in a confusing way
=> Fix typo of `PublicEndpoint` alias

docs/swagger-ui-bundle/src/test/scala/sttp/tapir/swagger/bundle/SwaggerInterpreterTest.scala, docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUI.scala, project/Versions.scala
This update requires changes in SwaggerUI because this PR (https://github.com/swagger-api/swagger-ui/pull/7905) removes inline code from index.html where the hack with replacing petstore link was implemented. Now, petstore link lives inside swagger-initializer.js and replacing is now performed for the swagger-initializer.js file.
=> Update swagger-ui to 4.9.1

core/src/main/scala-2/sttp/tapir/generic/internal/OneOfMacro.scala, integrations/enumeratum/src/test/scala/sttp/tapir/codec/enumeratum/TapirCodecEnumeratumTest.scala
Similar to #1950 this example is unable to compile. I think the main distinction is the use of `enumeratum.EnumEntry` and possibly the conflicting tapir configuration that this case is trying to override with a custom mapping for the discriminator.
```
[error] /home/seglo/source/tapir/integrations/enumeratum/src/test/scala/sttp/tapir/codec/enumeratum/TapirCodecEnumeratumTest.scala:138:83: type mismatch;
[error]   ee.type|OfferType with scala.Product with java.io.Serializable
[error]       Schema.oneOfUsingField[CreateOfferRequest, OfferType](_.`type`, _.entryName)(
[error]                                                                                   ^
```
=> [BUG] oneOfUsingField fails for case object enums that inherit enumeratum EnumEntry reproducer

docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/schema.scala, docs/openapi-docs/src/test/resources/expected_default_and_example_on_nested_option_field.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala
=> Generate "default" and "example" values in OpenAPI for nested optional fields

doc/endpoint/ios.md
Closes https://github.com/softwaremill/tapir/issues/2041
I didn't find a place in the documentation that is focused on description of input/output thus put a minimal paragraph in the "Input/Output" page but I'm open to other suggestions.
=> docs: ✏️ Document how to hide input/output from OpenAPI

.github/workflows/ci.yml, .sbtopts
locally if I just launch sbt, the project never finishes loading because 1G is not enough...
```
[info] welcome to sbt 1.6.2 (Eclipse Adoptium Java 17.0.3)
[info] loading settings for project global-plugins from plugins.sbt ...
[info] loading global plugins from /home/joao/.sbt/1.0/plugins
[info] loading settings for project tapir-build from build.sbt,plugins.sbt ...
[info] loading project definition from /home/joao/git/tapir/project
[info] compiling 1 Scala source to /home/joao/git/tapir/project/target/scala-2.12/sbt-1.0/classes ...
[info] loading settings for project rootProject from build.sbt ...
[info] resolving key references (307896 settings) ...
[warn] In the last 10 seconds, 5.454 (55.5%) were spent in GC. [Heap: 0.00GB free of 1.00GB, max 1.00GB] Consider increasing the JVM heap …
```
=> move JAVA_OPTS to .sbtopts

core/src/main/scala/sttp/tapir/Validator.scala, core/src/test/scala/sttp/tapir/SchemaApplyValidationTest.scala, core/src/test/scala/sttp/tapir/ValidatorTest.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, integrations/cats/src/test/scala/sttp/tapir/integ/cats/ValidatorCatsTest.scala, integrations/refined/src/main/scala/sttp/tapir/codec/refined/TapirCodecRefined.scala, integrations/refined/src/test/scala/sttp/tapir/codec/refined/TapirCodecRefinedTest.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureHandler.scala, server/core/src/test/scala/sttp/tapir/server/interceptor/decodefailure/DefaultDecodeFailureHandlerTest.scala
Closes #1420, which was already partly resolved in #1567
Incorporates some ideas by @geirolz from #1467
=> Improve validators by introducing a dedicated ValidationResult type and simplifying ValidationError

doc/server/vertx.md
fixes https://github.com/softwaremill/tapir/issues/2140
Also fixes the wrong import:
zio with vertx requires "com.softwaremill.sttp.tapir" %% "tapir-zio" % V instead of "com.softwaremill.sttp.shared" %% "zio" % V
=> Fix zio vertx documentation

build.sbt, integrations/refined/src/main/scala/sttp/tapir/codec/refined/TapirCodecRefined.scala, integrations/refined/src/test/scala-2/sttp/tapir/codec/refined/TapirCodecRefinedTestScala2.scala, integrations/refined/src/test/scala-3/sttp/tapir/codec/refined/TapirCodecRefinedTestScala3.scala, integrations/refined/src/test/scala/sttp/tapir/codec/refined/TapirCodecRefinedTest.scala
Hi,
This PR adds `refined` support for Scala 3.
What has been done : 
- adding scala 3 as cross version in `build.sbt`
- the initial code was compiling but the tests were failing for Scala 3, so I've split the `refined` tests sources in 2 directories `scala-2` and `scala-3` and copied the original test file in both of them.
- I removed the use of shapeless in `scala-3` tests folder and used literal instead
- unfortunately the implicit for `MatchesRegex` was not working anymore so the `Validator` was `Custom` and not `Pattern`, so I've updated the implicit in sources and used `WitnessAs[S, String]` instead of `Witness.Aux[S]`. It fixed the issue. *Check with caution, I'm a `refined` user and not a `refined` expert.*
- I've added 2 extra tests (1 per scala major version) to ensure the …
=> Refined scala 3 support

core/src/main/scala-2/sttp/tapir/internal/CodecEnumerationMacro.scala, core/src/test/scala/sttp/tapir/namespacing/SchemaMacroNamespaceTest.scala
closes https://github.com/softwaremill/tapir/issues/2254
=> The derivedEnumeration macro should reference fully qualified class names

doc/endpoint/basics.md
I found it confusing to use `&` in this place because `&` is Scala 3 syntax for intersection type, so I thought I'd change it to “and” instead.
=> use `and` instead of `&`

metrics/prometheus-metrics/src/main/scala/sttp/tapir/server/metrics/prometheus/PrometheusMetrics.scala
The Prometheus Java client requires the list of labels to be declared,
and then the same number of labels to be passed when "observing" a data
point. The default requestDuration was missing the "phase" label in its
onException callback. This caused it to throw an
IllegalArgumentException at run time.
Fixes #2295.
=> Set the "phase" label on exception in default Prometheus duration metric

server/play-server/src/main/scala/sttp/tapir/server/play/PlayRequestBody.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerTest.scala
Fixes #2281 
When using the text body parser to read a data part, the content-length of the request is changed. This way the text body parser will not report that the request is too large.
=> Fix #2281: play server will read text data in multipart requests

build.sbt, doc/server/observability.md, examples/src/main/scala/sttp/tapir/examples/observability/DatadogMetricsExample.scala, metrics/datadog-metrics/src/main/scala/sttp/tapir/server/metrics/datadog/DatadogMetrics.scala, metrics/datadog-metrics/src/test/scala/sttp/tapir/server/metrics/datadog/DatadogMetricsTest.scala, project/Versions.scala
I wanted to see the metrics in Datadog, so I implemented it with reference to `PrometheusMetrics`.
It looks like it's working:
problem: Unit tests are very very slow.
=> Add datadog metrics

server/sttp-stub-server/src/main/scala/sttp/tapir/server/stub/SttpRequest.scala, server/sttp-stub-server/src/test/scala/sttp/tapir/server/stub/TapirStubInterpreterTest.scala
The PR fixes the following issue:
while testing endpoints with trailing slash like `http://test.com/api/products/` the stub server returned `Unit` rather than output value according to endpoint's server logic. 
Please see #2327 for details.
=> Ignore trailing slash in stub request

README.md, core/src/main/scala/sttp/tapir/EndpointIO.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointInputToParameterConverter.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/ExampleConverter.scala, docs/openapi-docs/src/test/resources/example/expected_multiple_examples_with_names.yml, docs/openapi-docs/src/test/resources/example/expected_single_example_with_description.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlExampleTest.scala, integrations/cats/src/test/scala/sttp/tapir/integ/cats/ExampleFunctorLawSpec.scala
I have added description field for examples as it might be useful in some cases. 
From code perspective, there is already implementation for description from OpenAPI point of view. What I did is, I just added `description` field to `Example` class from `EndpointIO.scala` which is then mapped to OpenAPI standard
Examples provided both in tests and below.
OpenAPI generated code could be tested against [https://editor.swagger.io/](url)
```
openapi: 3.0.3
info:
title: Test
version: 0.1.0-SNAPSHOT
paths:
/admin/health:
get:
tags:
- Health Check API
summary: Checks if application resources are up
operationId: getAdminHealth
responses:
'503':
description: ''
content:
application/json:
schema:
$ref: '#/components/schemas/TimeoutError'
examples:
sample1:
summary: "Some summary"
description: "some …
```
=> added description field to example class

doc/index.md
So that one doesn't have scroll to see `Reset` and `Generate ZIP` buttons.
=> fix: increase the adopt-tapir iframe's height

generated-doc/out/index.md
Increase the height to *590* so that `Reset` and `Generate ZIP` buttons are again visible.
Note that the current height value is available in [adopt-tapir](https://github.com/softwaremill/adopt-tapir/blob/main/ui/README.md#routing--embeddedable-version).
Follow-up to: softwaremill/adopt-tapir/issues/130
=> chore: adjust iFrame height to the revamped adopt-tapir UI

server/core/src/main/scala/sttp/tapir/server/interceptor/cors/CORSConfig.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/cors/CORSInterceptor.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerCORSTests.scala
This PR adds support for multiple matching origins in `CORSConfig`. This functionality is already present in CORS support for `Vert.X` or `zio-http`, so it is very helpful to have it in Tapir's native `CORSInterceptor`. Config is defined as `String => Boolean` function to allow partial matching.
=> Allow multiple origins in CORSConfig

doc/index.md
The `Preview` button of the `adopt-tapit` functionality opens new window with the source code therefore the sandbox'ed iframe requires the 'allow-popups' permission to be set.
Follow-up to softwaremill/adopt-tapir/issues/169
=> feat: add 'allow-popups' permission to adopt-tapir iframe

doc/docs/openapi.md, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, project/Versions.scala
* Updated `sttp-apispec` version from `0.2.1` to `0.3.1`, made minor changes to `TSchemaToASchema` as models in new `sttp-apispec` have changed slightly.
* Added documentation on how to generate OpenAPI documentation compatible with 3.1.0 specifications.
=> 2499 Use `sttp-apispec` 0.3.1 in tapir

serverless/aws/sam/src/main/scala/sttp/tapir/serverless/aws/sam/EndpointsToSamTemplate.scala, serverless/aws/sam/src/test/resources/code_source_template.yaml, serverless/aws/sam/src/test/resources/image_source_template.yaml, serverless/aws/sam/src/test/scala/sttp/tapir/serverless/aws/sam/VerifySamTemplateTest.scala
When defining an endpoint which contains a hyphen, I get
`Error: [InvalidResourceException('FooApiFunctionGetApiV1Bar-baz 'Logical ids must be alphanumeric.')] ('FooApiFunctionGetApiV1Bar-baz', 'Logical ids must be alphanumeric.')`
=> avoid special characters in SAM logical ids

build.sbt, doc/server/observability.md, examples/src/main/scala/sttp/tapir/examples/observability/ZioMetricsExample.scala, metrics/zio-metrics/src/main/scala/sttp/tapir/server/metrics/zio/ZioMetrics.scala, metrics/zio-metrics/src/test/scala/sttp/tapir/server/metrics/zio/ZioMetricsTest.scala
ZIO2 Integrated ZMX metrics into core with v2 adding an interceptor/collector makes sense.
* Did not include a metric endpoint as zio metrics don't define output only collection.
=> ZIO2 core metrics interceptor/collector

server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerOptions.scala, server/zio1-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio1-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerOptions.scala
This solves the problem when ZioHttpServerOptions are required to also have the same environment as the endpoints due to R type parameter being shared between them via the ZioHttpInterpreter trait.
=> Added necessary widens to support multiple environments

client/sttp-client/src/test/scalajvm/sttp/tapir/client/sttp/SttpClientZioTests.scala, server/armeria-server/zio/src/main/scala/sttp/tapir/server/armeria/zio/TapirZioService.scala, server/http4s-server/zio/src/test/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sServerStubTest.scala, server/http4s-server/zio/src/test/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sTestServerInterpreter.scala, server/vertx-server/zio/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala, server/vertx-server/zio/src/main/scala/sttp/tapir/server/vertx/zio/streams/zio.scala, server/vertx-server/zio/src/test/scala/sttp/tapir/server/vertx/zio/VertxStubServerTest.scala, server/vertx-server/zio/src/test/scala/sttp/tapir/server/vertx/zio/streams/ZStreamTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerStubTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala
It seems that unsafeCompat is deprecated in favor of unsafe
=> Replace unsafeCompat with usafe

server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/NettyCatsServerInterpreter.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyFutureServerInterpreter.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyBodyListener.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerInterpreter.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/RunAsync.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerMetricsTest.scala, server/vertx-server/cats/src/main/scala/sttp/tapir/server/vertx/cats/VertxCatsServerInterpreter.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/VertxBodyListener.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/VertxFutureServerInterpreter.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/interpreters/RunAsync.scala, server/vertx-server/zio/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala, server/vertx-server/zio1/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala
=> Fix metric collection in vertx and netty

.gitignore, serverless/aws/sam/src/main/scala/sttp/tapir/serverless/aws/sam/AwsSamOptions.scala, serverless/aws/sam/src/main/scala/sttp/tapir/serverless/aws/sam/AwsSamTemplateEncoders.scala, serverless/aws/sam/src/main/scala/sttp/tapir/serverless/aws/sam/EndpointsToSamTemplate.scala, serverless/aws/sam/src/main/scala/sttp/tapir/serverless/aws/sam/model.scala, serverless/aws/sam/src/test/resources/http_api_template.yaml, serverless/aws/sam/src/test/scala/sttp/tapir/serverless/aws/sam/VerifySamTemplateTest.scala
Hi,
I need to configure the CORS property in the AWS SAM templates.
I think that that the user facing APIs are backward compatible, but I am not sure.
=> handle the CORS configuration in SAM templates

examples/src/main/scala/sttp/tapir/examples/HelloWorldZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/ZioExampleZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/observability/ZioMetricsExample.scala, examples/src/main/scala/sttp/tapir/examples/openapi/RedocZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/streaming/StreamingZioHttpServer.scala
Use `Server.live` instead of `Server.default`.
`Server.default` forces the default port 8080 to be used, regardless of the provided `ServerConfig` layer.
=> Fix port binding in zio-http examples

build.sbt
This PR adds JS platforms in zio modules. I tested this change by running tests on zio modules. I attempted adding Scala Native as a platform but got into some compilation problems so this PR is limited to JS only.
=> Build zio modules for ScalaJS

doc/server/errors.md, server/core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureHandler.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala
=> Add an attribute to customise default decode failure handling for individual inputs/outputs

build.sbt, doc/server/ziohttp.md, examples/src/main/scala/sttp/tapir/examples/HelloWorldZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/ZioExampleZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/observability/ZioMetricsExample.scala, examples/src/main/scala/sttp/tapir/examples/openapi/RedocZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/streaming/StreamingZioHttpServer.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpCompositionTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala
Hey!
zio-http changed quite a bit between 0.0.4 and 0.0.3, mainly separating `Route`s from `Handler`s. The difference is basically that a `Route` is a `PartialFunction[Request, Handler[R, E, In, Out]`, i.e can choose to handle or not handle an incoming request.
It also introduces a new concept of an `App` that is what we can serve via a server. `App` is a special case of a `Handler[-R, Response, Request, Response]`, i.e the error we return needs to be a valid HTTP Response. In order to convert between the two there's a convenience function `Http#withDefaultErrorResponse` that handles errors as a `500` response.
This also re-adds 2.12 support for zio-http now that https://github.com/zio/zio-http/issues/1813 is fixed.
=> chore: zio-http 0.0.4

doc/docs/asyncapi.md, doc/endpoint/schemas.md, doc/endpoint/validation.md, doc/endpoint/xml.md, doc/testing.md
This PR fixes a few broken links in the docs to sections across pages. I'm using the Spinx cross-referencing syntax and sphinx.ext.autosectionlabel extension as documented on https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html
=> [docs] Fix broken links to sections across pages

doc/server/ziohttp.md, examples/src/main/scala/sttp/tapir/examples/HelloWorldZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/ZioExampleZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/observability/ZioMetricsExample.scala, examples/src/main/scala/sttp/tapir/examples/openapi/RedocZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/streaming/StreamingZioHttpServer.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerOptions.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpCompositionTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala
This is an attempt to fix #2708. Sorry about getting it wrong the first time, I'm still not completely familiar with the Middleware, Routing and Handler changes in zio-http 0.0.4.
If I understand https://github.com/zio/zio-http/issues/1975#issuecomment-1420947906 correctly, the issue with the current interpreter is that we're effectfully creating a handler [here](https://github.com/softwaremill/tapir/blob/master/server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala#L35-L36), which in turn will result in our interpreter accepting all routes (and more or less doing its internal routing later), which makes the middlewares run incorrectly from the point of view of a user.
This instead tries to adapt the pattern that the play interpreter uses and constructs a …
=> zio-http: Use Http.collectHandler

doc/server/play.md, doc/server/ziohttp.md, server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala
The request is decoded once, and the decision whether a request should be handled by tapir is done based on the shape of the path
=> Improve the efficiency of request handling in ZIO Http & Play

build.sbt, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala, server/zio-http-server/src/test/scala/zio/test/package.scala
Fake using the zio package to bypass the `private[zio]` in `NettyDriver`.
This can be removed after the next zio-http upgrade, but in the meantime this lets us restore Scala 2.12 suppport.
Since it's only in tests, I think it's acceptable.
=> Bring back 2.12 support for zio-http

build.sbt, project/Versions.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerRequest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpCompositionTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala, server/zio-http-server/src/test/scala/zio/test/package.scala
Upgrade ZIO HTTP server to latest version
=> Upgrade ZIO HTTP (0.0.5) + Cats Effect Interop (23.0.0.2)

core/src/main/scala/sttp/tapir/Endpoint.scala
In my code, I often share a common base endpoint that I use to create multiple concrete endpoint. But sometimes I want to overwrite the existing tags on the base endpoint.
What I currently do:
```scala
val baseEndpoint = endpoint.in("some-base").tag("basic api")
val myEndpoint = baseEndpoint
.info(baseEndpoint.info.copy(tags = Vector.empty)) // overwrite tag of base
.tag("personal api")
```
Does it make sense to support this?
This PR would introduce a method `tagsEmpty` to do this:
```scala
val myEndpoint = baseEndpoint
.withoutTags // or
.withTag("personal api") // or
.withTags(List("personal api"))
```
=> add ability to overwrite tags on endpoint

server/vertx-server/src/main/scala/sttp/tapir/server/vertx/VertxFutureServerInterpreter.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/encoders/VertxToResponseBody.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/handlers/package.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/streams/Pipe.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/streams/ReadStreamCompatible.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/streams/package.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/streams/websocket.scala, server/vertx-server/src/test/scala/sttp/tapir/server/vertx/VertxServerTest.scala, server/vertx-server/src/test/scala/sttp/tapir/server/vertx/VertxTestServerBlockingInterpreter.scala, server/vertx-server/src/test/scala/sttp/tapir/server/vertx/VertxTestServerInterpreter.scala
Hi everyone,
this PR is adding web sockets to the `VertxFutureServerInterpreter`.
You'll see that it misses some implementations of some configuration stuff: `ignorePong`, `autoPing`and `contatenateFrames`. 
But this is a first step and the web socket is already working, I could test it in my project.
=> Add `WebSockets` support to `VertxFutureServerInterpreter`

core/src/main/scala-2/sttp/tapir/internal/ValidatorEnumerationMacro.scala, core/src/main/scala-3/sttp/tapir/macros/ValidatorMacros.scala, core/src/test/scala-3/sttp/tapir/ValidatorScala3EnumTest.scala, core/src/test/scala/sttp/tapir/ValidatorTest.scala
Fix `Validator.derivedEnumeration` for cases like below
```scala
sealed trait EnumRoot
sealed trait ABranch extends EnumRoot
sealed trait BBranch extends EnumRoot
case object A1 extends ABranch
case object A2 extends ABranch
case object B1 extends BBranch
```
`Validator.derivedEnumeration[EnumRoot]`
**Expected**
- Validation one of (A1, A2, B1)
**Actual**
- compile error `All children must be objects or enum cases`
=> Validator.derivedEnumeration to handle sealed sub-level traits

build.sbt
By default dependencies of test can be run in parallel, it includeds Scala Native/Scala.js linkers. These can use lots of resources and eventually lead to OOM, especially on LLVM.
=> Add concurrecny restriction for linking ScalaNative and Scala.js

build.sbt
Analogous to the `ideSkipProject` setting, but for Metals. This should exclude JS/Native projects as well as Scala 2.12 / Scala 3 from builds.
=> Disable BSP if ideSkipProject

README.md, doc/flake.lock, doc/flake.nix
This change allows running a single command: `nix develop` to build and enter into development shell with all required python dependencies needed to work on the documentation.
- `flake.nix` defines the dev environment and refers to requirements.txt
- `flake.lock` freezes all versions of resolved packages
Using Nix for such purposes is a pretty cool experience, one does not need to worry that they will pollute the system with conflicting tools and libraries, which happens especially often with Python development.
=> Add Nix flake for the documentation dev tools

server/sttp-stub-server/src/main/scala/sttp/tapir/server/stub/SttpRequestBody.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala
Fixes https://github.com/softwaremill/tapir/issues/2849
BTW the real exception is
```
java.lang.ClassCastException: class zio.ZIO$Sync cannot be cast to class zio.stream.ZStream 
(zio.ZIO$Sync and zio.stream.ZStream are in unnamed module of loader 
sbt.internal.LayeredClassLoader @561245bc)
at sttp.tapir.ztapir.ZTapir$RichZEndpoint.$anonfun$zServerLogic$2(ZTapir.scala:24)
```
which gets lost somewhere in the error handling chain.
=> [bugfix] Don't wrap streams in the stub interpreter

.scalafix.conf
This configuration enables the "organize imports" action for Metals. I haven't changed the default settings too much, except setting `groupedImports` to `Merge`. This creates groups of imports if they are from the same package.
=> Add scalafix configuration for organizing imports

server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaBodyListener.scala, server/akka-http-server/src/test/scala/sttp/tapir/server/akkahttp/AkkaHttpServerTest.scala
Fixes #2778 
Based on https://github.com/akka/akka-http/issues/258
It turns out that `responseEntity.transformDataBytes` called without `contentLength` changes entity type to an octet-stream. This fix adds separate handling for empty entities and universal entites to preserve their type.
=> Fix handling Strict and Empty body in AkkaBodyListener

server/armeria-server/cats/src/main/scala/sttp/tapir/server/armeria/cats/ArmeriaCatsServerOptions.scala, server/armeria-server/cats/src/main/scala/sttp/tapir/server/armeria/cats/TapirCatsService.scala, server/finatra-server/cats/src/main/scala/sttp/tapir/server/finatra/cats/FinatraCatsServerInterpreter.scala, server/finatra-server/cats/src/main/scala/sttp/tapir/server/finatra/cats/FinatraCatsServerOptions.scala, server/finatra-server/cats/src/main/scala/sttp/tapir/server/finatra/cats/conversions.scala, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/internal/CatsUtil.scala, server/vertx-server/cats/src/main/scala/sttp/tapir/server/vertx/cats/VertxCatsServerInterpreter.scala, server/vertx-server/src/test/scala/sttp/tapir/server/vertx/VertxTestServerInterpreter.scala
Fixes https://github.com/softwaremill/tapir/issues/2892
The crucial change in CE 3.5 is that now `async_` is uncancellable, which may lead to deadlocks. It also affects `Async[F].fromFuture` which relies on it underneath, as well as `async`, which becomes uncancellable when returning a `None`.
This PR revises our usages of `async` and friends in order to add proper explicit handling for cancellation where needed.
1. `ArmeriaCatsServerOptions[F]`
Creating and deleting temp files for Armeria is now converted to `async` with an attempt to cancel the underlying Java Future.
2. Armeria's `CatsFutureConversion` now uses CE's `fromFutureCancelable`, with empty cancellation logic. The underlying Future cannot be canceled, but at least we remain consistent with previous behavior - the fiber that …
=> Adjust Async cancellation to CE 3.5

server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerOptions.scala
Reported in https://github.com/softwaremill/tapir/issues/2764
The `DecodeFailureHandler` should be provided only by .customiseInterceptors
=> Remove DecodeFailureHandler from ZioHttpServerOptions

doc/endpoint/contenttype.md, doc/endpoint/json.md
Documentation referring `customJsonBody` for Custom codec, though `customJsonBody` should be `customCodecJsonBody`, according to [migration](https://github.com/softwaremill/tapir/blob/c4ce0f5a08202998542c52b4f63c4aee7f02da7d/doc/migrating.md?plain=1#L12).
=> Fixed obsolete code examples

doc/index.md, doc/stability.md
Follow-up on #2904.
BTW, Json Schema documentation is not visibile in https://tapir.softwaremill.com/en/latest/ under section "DOCUMENTATION INTERPRETERS".
Do the docs need to be deployed manually?
=> Add json-schema to stability.md. Follow-up on #2904

doc/server/debugging.md, server/core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLog.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/log/ServerLogInterceptor.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerOptionsTests.scala
Implements https://github.com/softwaremill/tapir/issues/2827
This new API is similar to what we already provide in `.metricsInterceptor`, which allows setting `ignoreEndpoints: Seq[AnyEndpoint]`.
For logging, such method is now available on the `DefaultServerLog` class, allowing to specify server options like:
```scala
Http4sServerOptions
.customiseInterceptors[IO]
.serverLog(Http4sServerOptions.defaultServerLog.ignoreEndpoints(Seq(healthCheckEndpoint, versionEndpoint))
.options
```
This will skip listed endpoints when logging in `requestHandled`, but still keep logging exceptions and decoding failure errors if they are enabled.
=> Allow ignoring logging of request handling for some endpoints

server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerOptions.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerStubTest.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayTestServerInterpreter.scala
Add configuration parameter which set maxMemoryBuffer and maxDiskBuffer from application.conf by default
=>  [bugfix] Add configuration parameter to customiseInterceptors in PlayServerOptions

doc/endpoint/oneof.md, generated-doc/out/endpoint/oneof.md
It turns out that the docs section that describes `errorOutVariantPrepend` doesn't use `errorOutVariantPrepend` in its example.
=> Use errorOutVariantPrepend in docs example.

server/vertx-server/zio/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala, server/vertx-server/zio/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerOptions.scala, server/vertx-server/zio/src/main/scala/sttp/tapir/server/vertx/zio/streams/zio.scala, server/vertx-server/zio/src/test/scala/sttp/tapir/server/vertx/zio/VertxStubServerTest.scala, server/vertx-server/zio/src/test/scala/sttp/tapir/server/vertx/zio/ZioVertxTestServerInterpreter.scala, server/vertx-server/zio/src/test/scala/sttp/tapir/server/vertx/zio/streams/ZStreamTest.scala, server/vertx-server/zio1/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala, server/vertx-server/zio1/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerOptions.scala, server/vertx-server/zio1/src/main/scala/sttp/tapir/server/vertx/zio/streams/zio.scala, server/vertx-server/zio1/src/test/scala/sttp/tapir/server/vertx/zio/VertxStubServerTest.scala, server/vertx-server/zio1/src/test/scala/sttp/tapir/server/vertx/zio/ZioVertxTestServerInterpreter.scala, server/vertx-server/zio1/src/test/scala/sttp/tapir/server/vertx/zio/streams/ZStreamTest.scala
I noticed some changes in #3011 which I would like to use. And decided to make the same changes to VertxZioServerOptions also. Hope there would be no problem with backward compatibility.
=> Changed type parameter of VertxZioServerOptions from F[_] to R of RIO[R, *] interop effect type, added widen method.

build.sbt, doc/server/netty.md, examples/src/main/scala/sttp/tapir/examples/streaming/StreamingNettyFs2Server.scala, project/Versions.scala, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/NettyCatsServer.scala, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/NettyCatsServerInterpreter.scala, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/internal/NettyCatsRequestBody.scala, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/internal/NettyCatsToResponseBody.scala, server/netty-server/cats/src/test/scala/sttp/tapir/server/netty/cats/NettyCatsServerTest.scala, server/netty-server/cats/src/test/scala/sttp/tapir/server/netty/cats/NettyCatsTestServerInterpreter.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyConfig.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyFutureServer.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyResponseContent.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyServerRequest.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyRequestBody.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerHandler.scala, server/netty-server/src/test/scala/sttp/tapir/server/netty/NettyFutureTestServerInterpreter.scala, server/netty-server/zio/src/main/scala/sttp/tapir/server/netty/zio/NettyZioServer.scala, server/netty-server/zio/src/test/scala/sttp/tapir/server/netty/zio/NettyZioTestServerInterpreter.scala, server/tests/src/main/scala/sttp/tapir/server/tests/AllServerTests.scala, server/tests/src/main/scala/sttp/tapir/server/tests/CreateServerTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerFilesTests.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerStreamingTests.scala, tests/src/main/scala/sttp/tapir/tests/Streaming.scala
This PR enhances Netty Cats Effect server with streaming. 
From now on, the public API is:
```scala
NettyCatsServer
.io()
.use { server =>
server
.port(port)
.host(host)
.addEndpoint(serverEndpoint) // <<< ServerEndpoint[Fs2Streams[F]]
.start()
}
```
Implementation notes:
- I used `HttpStreamsServerHandler` from [netty-reactive-streams-http](https://github.com/playframework/netty-reactive-streams). Adding it to the pipeline allows using a response of type `DefaultStreamedHttpResponse`, which wraps a reactive `Publisher[HttpContent]`.
- However, this handler doesn't work together with `HttpObjectAggregator`, so I had to split the pipeline into streaming/non-streaming variants.
- Without `HttpObjectAggregator` we no longer can send `ChunkedInput`, but this isn't a problem, we can just send …
=> Netty streaming for Cats Effect

server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpBodyListener.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpResponseBody.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpToResponseBody.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/package.scala
Fixes #3034 
This PR changes handling of raw body types. Instead of always using a `ZStream`, such responses are packed into a `Chunk[Byte]`. This allows logging the response body by ` zio.http.internal.middlewares.RequestLogging`.
=> [bugfix] Return raw ZIO response body where applicable

server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyConfig.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyBootstrap.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyConnectionCounter.scala
The next point from [list](https://github.com/softwaremill/tapir/issues/2971).
I made it on the base:  https://stackoverflow.com/questions/46849964/how-to-set-maximum-concurrent-connections-with-netty
=> Add max connections to netty configuration

server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/internal/NettyCatsToResponseBody.scala
Should be `NettyToResponseBody.DefaultChunkSize` instead `r.contentLength.toInt`
Additional formatting fixes.
=> [bugfix] Fix chunk size for Netty Cats file body

server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sServerInterpreter.scala
Directly use `WebSocketBuilder2#build(sendReceive: Pipe[F, WebSocketFrame, WebSocketFrame])`. Maybe relates to #3048?
=> Simplify http4s websocket interpreter.

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/SchemaParserSpec.scala
Adds support for parsing [maps](https://swagger.io/docs/specification/data-models/dictionaries/).
```yaml
components:
schemas:
Model:
required:
- data
type: object
properties:
data:
type: object
additionalProperties:
type: object
required:
- value
properties:
value:
type: integer
```
Produces
```scala
case class Model (
data: Map[String, ModelDataItem]
)
case class ModelDataItem (
value: Int
)
```
This also adds support for arrays and maps containing objects. Previously only simple types were supported as array items.
=> Add support for map for codegen

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala
Handles parameters defined directly on path objects (whilst still permitting overriding via identically-named parameters directly on the method, as per the openapi spec)
Contains some additional unrelated test changes (looks like recently merged prs weren't up-to-date so some tests didn't compile when reconciled)
=> handle parameters defined on parent path of method (codegen)

build.sbt, doc/generator/sbt-openapi-codegen.md, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/ModelParserSpec.scala
Maybe not the best solution... for scala 3, it would obviously make sense to just use scala enums; for scala 2 on the jvm, it might make sense to use java enums; some people probably don't even mind scala 2's enumeration too much. The choice of enumeratum however has the advantage that it works on both versions of scala on all platforms, so I _think_ it's the right one here.
We only include the import when we actually generate enums, so this doesn't introduce a dependency on enumeratum _unless_ enums are actually specified.
=> Use Enumeratum for enum codegen

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala
Permits specifying a `Unit` output type by not providing a response content.
=> handle missing response content in codegen

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala
Probably the last one from me for a while - this will get tapir codegen to the point where it can generate the required code from some $realWorld stoplight output that I've been working with. Thanks so much for this project 😄 
Edit: I haven't touched the tests for this because it's super minor, and more a quirk of stoplight than anything else. I'd much rather the requestBody had just been fully absent from the output - which would already have worked - but instead I'm seeing
```
requestBody:
content: {}
```
Ridiculous. But the documentation [doesn't actually specify that the content map be non-empty](https://swagger.io/specification/#request-body-object)
=> handle empty requestBody.content in codegen

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiComponent.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala
Mixing up a few things in this pr:
- Fail codegen if parameters can't be decoded
- Added slightly more detail to a few of the error messages
- Support defining maps directly under schemas
- Make endpoint definitions lazy, to reduce occurrence of 'method too large' errors
Happy to put any of these changes into a separate pr if they're contentious, but figured there wasn't too much harm in putting a few little things all in the same pr
=> Some codegen improvements

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiComponent.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSecuritySchemeType.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/ModelParserSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/SchemaParserSpec.scala
Adds support for `bearer`, `basic` and `apiKey` [security schemes](https://swagger.io/docs/specification/authentication/).
=> Add security support for codegen

server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpResponseBody.scala
Small change to make it possible to eg. log server response body using Tapir interceptor. Right now it cannot be done without using some hacks as `ZioRawHttpResponseBody` trait (and case classes which extend this trait) are marked as private.
=> Make ZioHttpResponseBody public

README.md
I just added it to the list based on alphabetic order but another option is to have it after Akka HTTP in the list.
=> add Pekko HTTP support to README.md

build.sbt, server/pekko-http-server/src/main/scala/sttp/tapir/server/pekkohttp/PekkoServerRequest.scala, server/pekko-http-server/src/main/scala/sttp/tapir/server/pekkohttp/PekkoToResponseBody.scala
=> Enable pekko for Scala 3

doc/docs/openapi.md, docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUI.scala, docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUIOptions.scala
In swagger-ui, showing extensions is disabled by default, which results in them not being shown in tapir-swagger-ui, so the ability to control this option internally has been added.
=> Add support showExtensions option for swagger-ui

server/vertx-server/cats/src/main/scala/sttp/tapir/server/vertx/cats/VertxCatsServerInterpreter.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/VertxFutureServerInterpreter.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/VertxFutureServerOptions.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/decoders/VertxRequestBody.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/handlers/package.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/interpreters/CommonServerInterpreter.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/streams/Pipe.scala, server/vertx-server/zio/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala, server/vertx-server/zio1/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala
This pull request aims to improve codebase by utilizing the uploadDir path from the VertxServerSettings configuration instead of relying on the internal Vertx default value. 
Before this fix there was an issue where Vertx created unnecessary upload directories with default name (`file-uploads`) for every request, even without endpoints with file input type:
https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java#L234
The main cause is that BodyHandler by default is created with ability to handle file uploads and default upload dir:
https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java#L60
https://github.com/softwaremill/tapir/blob/master/server/vertx-ser …
=> Use uploadDir path from VertxServerSettings instead of internal Vertx default value + fix deprecations & unused imports

build.sbt
I've accidentally broke the cross-compile for refined in https://github.com/softwaremill/tapir/pull/3038/files#r1301183280
This PR fixes that mistake
=> restore cross-build for refined on js platform

build.sbt, server/core/src/main/scala/sttp/tapir/server/interpreter/ServerInterpreter.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, testing/src/main/scala/sttp/tapir/testing/EndpointVerificationError.scala, testing/src/main/scala/sttp/tapir/testing/EndpointVerifier.scala, testing/src/test/scala/sttp/tapir/testing/EndpointVerifierTest.scala
Initiated by: https://softwaremill.community/t/is-it-possible-to-raise-an-error-when-content-negotiation-is-invalid/261
=> Fail when there's an unexpected response body

docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUI.scala
I took me a while to resolve this as the [using-swaggerui-with-sbt-assembly](https://tapir.softwaremill.com/en/v0.17.20/docs/openapi.html#using-with-sbt-assembly) doc section is at the bottom.
=> detailed exception during swagger version initialization

integrations/enumeratum/src/main/scala/sttp/tapir/codec/enumeratum/TapirCodecEnumeratum.scala, integrations/enumeratum/src/test/scala/sttp/tapir/codec/enumeratum/TapirCodecEnumeratumTest.scala
This PR fixes schema name for enumeratum codec - currently it ends with extra dot like `a.b.TestEnum.`
=> Fix extra dot in schema name for enumeratum

build.sbt, doc/grpc.md, grpc/pekko-examples/src/main/protobuf/simple_books_example.proto, grpc/pekko-examples/src/main/scala/sttp/tapir/grpc/examples/PekkoGrpcSimpleBooksExample.scala, project/plugins.sbt, server/pekko-grpc-server/src/main/scala/sttp/tapir/server/pekkogrpc/PekkoGrpcRequestBody.scala, server/pekko-grpc-server/src/main/scala/sttp/tapir/server/pekkogrpc/PekkoGrpcServerInterpreter.scala, server/pekko-grpc-server/src/main/scala/sttp/tapir/server/pekkogrpc/PekkoGrpcToResponseBody.scala
=> add pekko grpc support

README.md
The readme was outdated, since currently only the Scala 3/JVM would be imported by default.
=> Update IntelliJ importing readme

doc/endpoint/pickler.md, json/pickler/src/main/scala/sttp/tapir/json/pickler/Pickler.scala, json/pickler/src/test/scala/sttp/tapir/json/pickler/PicklerTest.scala
Resolves #3207
I had to split the summonFrom matching into `Reader` and `Writer`, because trying to summon a `ReadWriter` ends with a strange `cannot establish a reference` compilation error.
=> Support all kinds of custom ReadWriters

core/src/main/scala/sttp/tapir/Validator.scala, core/src/test/scala/sttp/tapir/ValidatorTest.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala
Follow up to https://github.com/softwaremill/tapir/issues/3201. This PR adds optional support for counting unicode characters during validation.
=> Length validators: Support all unicode characters

README.md
This PR updates the README.md file to provide clearer guidance for new contributors, specifically addressing challenges encountered during binary compatibility check.
New contributors may experience difficulties when attempting to run `core/mimaReportBinaryIssues`, as tags are not fetched by default during forking.
I have enhanced the _**Contribution**_ section with more details on how to properly check binary compatibility, including the necessary steps to ensure that all relevant tags are fetched.
=> README: enhance contributing section

build.sbt, examples/src/main/scala/sttp/tapir/examples/observability/OpenTelemetryMetricsExample.scala
Adds a complete example of setting up OpenTelemetry metrics, using a gRPC exporter which sends the default metrics to an external collector.
=> Add OpenTelemetry metrics example

core/src/main/scala/sttp/tapir/attribute.scala, doc/docs/json-schema.md, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/Schemas.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/SchemasForEndpoints.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/ToKeyedSchemas.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/ToSchemaReference.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/schema.scala, docs/apispec-docs/src/test/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchemaTest.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/EndpointToAsyncAPIComponents.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/EndpointToAsyncAPIDocs.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/EndpointToAsyncAPIWebSocketChannel.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/MessagesForEndpoints.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointInputToParameterConverter.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOpenAPIComponents.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOpenAPIDocs.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOpenAPIPaths.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOperationResponse.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/ExampleConverter.scala, docs/openapi-docs/src/test/resources/enum/expected_enumeratum_enum_adding_default_when_encoded_value_specified.yml, docs/openapi-docs/src/test/resources/enum/expected_enumeratum_enum_default.yml, docs/openapi-docs/src/test/resources/enum/expected_enumeratum_enum_using_first_specified_default_value.yml, docs/openapi-docs/src/test/resources/expected_default_and_example_on_nested_option_field.yml, docs/openapi-docs/src/test/resources/multi_customise_schema/inlined.yml, docs/openapi-docs/src/test/resources/multi_customise_schema/nested_body.yml, docs/openapi-docs/src/test/resources/multi_customise_schema/top_level_body.yml, docs/openapi-docs/src/test/scalajvm-2/sttp/tapir/docs/openapi/VerifyYamlEnumeratumTest.scala, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlMultiCustomiseSchemaTest.scala, project/Versions.scala
Closes #1203
Also: https://softwaremill.community/t/tapir-redoc-annotations-not-working-as-expected/289
To implement this change, it was necessary to change the way schemas are referenced: this is no longer done using the `Reference` object and an `Either[Reference, Schema]`. Instead, schemas [can include a reference](https://github.com/softwaremill/sttp-apispec/pull/117) as part of the schema, as well as other properties. This is in-line with the changes done to JSON schema, and also referenced in the [OpenAPI docs](https://spec.openapis.org/oas/v3.1.0#reference-object).
=> Allow usage-site customisation of referenced schemas

docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/openapi-docs/src/test/resources/expected_nullable_option_class_field.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala
fixes #3234 
- inlines the reference type if `markOptionsAsNullable = true`
=> 3234: use markOptionsAsNullable for Option reference types

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala
See https://swagger.io/specification/#parameter-object
=> fixed parameter object in OpenAPI is not required

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/util/JavaEscape.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala
yaml files like this:
```yaml
openapi: 3.0.0
info:
version: …
title: …
paths:
/foo:
get:
description: …
parameters:
- name: …
in: …
required: …
description: a "quoted" string
schema:
type: …
responses:
'200':
description: …
```
Causes the generated code to not compile. The quotes are not escaped.
current solution just uses simple call to an included escape function. Perhaps we should use a cats show typeclass to stringify any descriptions and documentation. 
the whole module feels somewhat brittle to me.
=> escaping descriptions when generating endpoint from openapi

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/SchemaParserSpec.scala
I came across the across the following openAPI def (https://github.com/dahag-ag/keycloak-openapi/blob/0ec0f45ec0890ca12f9733aa4f5794a2e7a1d98b/OpenApiDefinitions/keycloak-21.0.0.yml#L7623):
The current version of the sbt-openapi-codegen does not support this and halts the import. This PR fixes that
```yaml
components:
schemas:
ClientPoliciesRepresentation:
type: object
properties:
policies:
type: array
items:
type: object
description: ClientPolicyRepresentation
```
=> added support for (array of) object without properties

integrations/iron/src/main/scala/sttp/iron/codec/iron/TapirCodecIron.scala, integrations/iron/src/test/scala-3/sttp/iron/codec/iron/RefinedInt.scala, integrations/iron/src/test/scala-3/sttp/iron/codec/iron/TapirCodecIronTestScala3.scala
Using the Iron library, a common pattern is to hide the constrained type behind an opaque alias, to disallow similarly constrained types (The same result can be obtained using `DescribedAs`, but I prefer not messing description with identity).
```scala
type RefinedIntConstraint = Interval.ClosedOpen[0, 10]
opaque type RefinedInt <: Int = Int :| RefinedIntConstraint
object RefinedInt extends RefinedTypeOpsImpl[Int, RefinedIntConstraint, RefinedInt]
```
Once the alias is opaque, it is not possible anymore to derive instances with the `Value :| Predicate` type pattern. 
This PR provides instances relying on the given `RefinedTypeOps.Mirror[T]` instance that is provided by `RefinedTypeOpsImpl`.
I wonder if the provided tests are enough or if there is corner cases I need to be aware of.
=> Feature: Add iron's RefinedTypeOps support

json/pickler/src/main/scala/sttp/tapir/json/pickler/Pickler.scala, json/pickler/src/test/scala/sttp/tapir/json/pickler/PicklerBasicTest.scala
Fixes https://github.com/softwaremill/tapir/issues/3287
For custom type `T` which are not products or coproducts, one should be able to derive a Pickler by providing implicit `Reader[T]`, `Writer[T]` (or `ReadWriter[T]`) and `Schema[T]`, then just calling `Pickler.derive[T]`.
Currenlty `derive` requires a `Mirror.Of[T]` in its signature, which needs to be removed and moved deeper into a `summonFrom` resolution, to defer determining how to construct the Pickler.
Additionally, the `nonMirrorPickler[T]` method will have a better error message, indicating that user should use `Pickler.derived[T]`
We can't hide `nonMirrorPickler` entirely, because it has to be in scope for correct resolution of predefined picklers (like String, List, Option, etc).
=> [bugfix] Allow calling Pickler.derive on non-mirrored types

server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerOptions.scala
Attempt at #3290.
@adamw I'm not sure what would be the best way to test these changes, do you have any suggestions? Also, the addition of the argument in `ZioHttpServerOptions` makes this a breaking change. Should we add the default value to the constructor of `ZioHttpServerOptions` to make it at least source compatible?
=> Add option to provide custom WS config in zio-http

integrations/iron/src/main/scala/sttp/iron/codec/iron/TapirCodecIron.scala, integrations/iron/src/test/scala-3/sttp/iron/codec/iron/RefinedInt.scala, project/Versions.scala
Iron v2.3.0 introduced a slight name change in `RefinedTypeOps`, causing this module to not be compatible with the latest version. This PR fixes this issue.
I'm have little experience working with SBT so I'd suggest to make sure my changes are valid.
=> feat: Update Iron to v2.3.0

core/src/main/scala/sttp/tapir/Codec.scala, core/src/test/scala/sttp/tapir/CodecTest.scala
This is a proposition to add a `Codec.emap` function for mapping with `Either`, similar to what is done in several libraries with codecs:
- circe has `Codec.iemap`: https://github.com/circe/circe/blob/cddf7f28c37aaff46407e097b48135d8b411520b/modules/core/shared/src/main/scala/io/circe/Codec.scala#L42
- doobie has `Meta.timap`: https://github.com/tpolecat/doobie/blob/e79bab24b2ae1bc639f3a846dcdd74343696a786/modules/core/src/main/scala/doobie/util/meta/meta.scala#L33
- skunk has `Decoder.emap`: https://github.com/typelevel/skunk/blob/3911dc47e9429bea0663227a4dc5647d72a95bb3/modules/core/shared/src/main/scala/Decoder.scala#L32
- ...
=> syntactic sugar: add Codec.mapEither

build.sbt
It was common to all netty projects. Should be only in `netty-zio`.
=> Fix zio-interop-reactivestreams dependency

doc/server/options.md, examples/src/main/scala/sttp/tapir/examples/errors/CustomErrorsOnDecodeFailureAkkaServer.scala, examples/src/main/scala/sttp/tapir/examples/streaming/StreamingNettyZioServer.scala, metrics/datadog-metrics/src/test/scala/sttp/tapir/server/metrics/datadog/DatadogMetricsTest.scala, metrics/opentelemetry-metrics/src/test/scala/sttp/tapir/server/metrics/opentelemetry/OpenTelemetryMetricsTest.scala, metrics/prometheus-metrics/src/test/scala/sttp/tapir/server/metrics/prometheus/PrometheusMetricsTest.scala, metrics/zio-metrics/src/test/scala/sttp/tapir/server/metrics/zio/ZioMetricsTest.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/CustomiseInterceptors.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureHandler.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureInterceptor.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerOptions.scala, server/sttp-stub-server/src/test/scala/sttp/tapir/server/stub/TapirStubInterpreterTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerFilesTests.scala
Brings the same feature to DecodeFailureHandler like other interceptor handlers have.
=> Add type parameter F[_] to DecodeFailureHandler.

server/akka-http-server/src/test/scala/sttp/tapir/server/akkahttp/AkkaHttpTestServerInterpreter.scala, server/armeria-server/src/test/scala/sttp/tapir/server/armeria/ArmeriaTestServerInterpreter.scala, server/finatra-server/cats/src/test/scala/sttp/tapir/server/finatra/cats/FinatraCatsTestServerInterpreter.scala, server/finatra-server/src/test/scala/sttp/tapir/server/finatra/FinatraTestServerInterpreter.scala, server/http4s-server/src/test/scala/sttp/tapir/server/http4s/Http4sTestServerInterpreter.scala, server/http4s-server/zio/src/test/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sTestServerInterpreter.scala, server/http4s-server/zio1/src/test/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sTestServerInterpreter.scala, server/jdkhttp-server/src/test/scala/sttp/tapir/server/jdkhttp/JdkHttpTestServerInterpreter.scala, server/netty-server/cats/src/test/scala/sttp/tapir/server/netty/cats/NettyCatsTestServerInterpreter.scala, server/netty-server/loom/src/test/scala/sttp/tapir/server/netty/loom/NettyIdTestServerInterpreter.scala, server/netty-server/src/test/scala/sttp/tapir/server/netty/NettyFutureTestServerInterpreter.scala, server/netty-server/zio/src/test/scala/sttp/tapir/server/netty/zio/NettyZioTestServerInterpreter.scala, server/nima-server/src/test/scala/sttp/tapir/server/nima/NimaTestServerInterpreter.scala, server/pekko-http-server/src/test/scala/sttp/tapir/server/pekkohttp/PekkoHttpTestServerInterpreter.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayTestServerInterpreter.scala, server/tests/src/main/scala/sttp/tapir/server/tests/CreateServerTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/TestServerInterpreter.scala, server/vertx-server/cats/src/test/scala/sttp/tapir/server/vertx/cats/CatsVertxTestServerInterpreter.scala, server/vertx-server/src/test/scala/sttp/tapir/server/vertx/VertxTestServerInterpreter.scala, server/vertx-server/zio/src/test/scala/sttp/tapir/server/vertx/zio/ZioVertxTestServerInterpreter.scala, server/vertx-server/zio1/src/test/scala/sttp/tapir/server/vertx/zio/ZioVertxTestServerInterpreter.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala, server/zio1-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala, serverless/aws/lambda-cats-effect-tests/src/test/scala/sttp/tapir/serverless/aws/lambda/tests/AwsLambdaCreateServerStubTest.scala, serverless/aws/lambda-cats-effect-tests/src/test/scala/sttp/tapir/serverless/aws/lambda/tests/AwsLambdaStubHttpTest.scala, serverless/aws/lambda-zio-tests/src/test/scala/sttp/tapir/serverless/aws/ziolambda/tests/AwsLambdaCreateServerStubTest.scala, serverless/aws/lambda-zio-tests/src/test/scala/sttp/tapir/serverless/aws/ziolambda/tests/AwsLambdaStubHttpTest.scala, tests/src/main/scala/sttp/tapir/tests/package.scala
A follow-up to https://github.com/softwaremill/tapir/pull/3294
Implements `serverWithStop` for all test interpreters, so that any server test can now be run with graceful shutdown enabled, as well as shutdown hook (called KillSwitch) available as a test parameter using `testServerLogicWithStop`.
Example:
```scala
testServerLogicWithStop(
endpoint
.out(plainBody[String])
.serverLogic { _ =>
// do something with input
},
"Server name",
gracefulShutdownTimeout = Some(4.seconds) // enabled
) { (release) => (backend, baseUri) =>
// test body, you can use the `release: IO[Unit]` kill switch in your test 
// to stop the server arbitrarily, or just let it be stopped by test cleanup automatically
}
```
Some servers don't seem to support graceful shutdown out of the box, namely `VertX`, `zio-http …
=> [tests] Implement serverWithStop in all test interpreters

server/core/src/main/scala/sttp/tapir/server/interceptor/reject/RejectContext.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/reject/RejectHandler.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/reject/RejectInterceptor.scala
Sometimes, in order to form the body of the response in the case of 404 Not Found, it is necessary to use data from the request (for example headers: requestId, cookie etc). It is impossible to do this without implementing your custom RejectInterceptor.
Implementing custom reject interceptor and prepending it to CustomiseInterceptors brake standard interceptor order and may lead to unwanted behavior.
=> Add RejectContext to RejectHandler.

integrations/cats-effect/src/main/scala/sttp/tapir/integ/cats/effect/CatsMonadError.scala, server/armeria-server/cats/src/main/scala/sttp/tapir/server/armeria/cats/CatsMonadAsyncError.scala
A follow-up to https://softwaremill.community/t/sttp-monad-monaderror-blocking-for-cats-effect/314
We shouldn't use the default implementation which does `F.delay(t)`
=> [bugfix] Fix blocking implementation for CatsMonadAsyncError

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/SchemaParserSpec.scala
Adds support for [any type](https://swagger.io/docs/specification/data-models/data-types/#any)
Previously schema without a type was incorrectly parsed as an object.
=> Codegen any type support

build.sbt, doc/server/observability.md, examples/src/main/scala/sttp/tapir/examples/observability/PrometheusMetricsExample.scala, metrics/prometheus-metrics/src/main/scala/sttp/tapir/server/metrics/prometheus/PrometheusMetrics.scala, metrics/prometheus-metrics/src/test/scala/sttp/tapir/server/metrics/prometheus/PrometheusMetricsTest.scala
Trying to use the [bridge](https://prometheus.github.io/client_java/migration/simpleclient/#migration-using-the-simpleclient-bridge) provided by prometheus to not have the need of upgrading the old client produced a bug reported in #3315.
I upgraded the [prometheus java client](https://prometheus.github.io/client_java/) following the instructions to [refactor the instrumentation code](https://prometheus.github.io/client_java/migration/simpleclient/#refactoring-the-instrumentation-code) to the version [1.1.0](https://github.com/prometheus/client_java/releases/tag/v1.1.0) which is the latest one today and was released 5 days ago.
I also modified the assertions of the `PrometheusMetricsTest` suite. Instead of just validating that there is an exact string contained in the metrics generated, I …
=> #3315 - upgrade prometheus client java to 1.1.0

docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/openapi-docs/src/test/resources/expected_nullable_option_class_field_303.yml, docs/openapi-docs/src/test/resources/expected_nullable_option_field_303.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala, project/Versions.scala
These null-types are only supported in openapi 3.1.0. For 3.0.3, we need a different encoding.
Therefore, we should leave the distinction to sttp-apispec which handles this already, instead of deciding here in tapir.
=> make schema nullable instead of adding null-types into the apispec schema

.github/workflows/ci.yml
Installing Node.js using `sudo apt install npm` fails due to https://github.com/actions/runner-images/issues/8779
As per recommendations in the announcement, I'm switching to `actions/setup-node`.
=> Use setup-node to install npm

build.sbt
With only `Compile / compile` in `compileScoped`, the tests are compiled later in the `Test` step. The `Test` step is wrapped in retries, which causes unnecessary long retries in case of failing test compilation.
=> [CI] Compile tests in compileScoped

.github/workflows/ci.yml
Here's another attempt to make this better.
After recent change which  moves test compilation to the `compileScoped` step (https://github.com/softwaremill/tapir/pull/3336), I noticed that the `Test` step takes much less time (yay!). It's now a matter of minutes, usually far less than 10m if successful.
Because of this, I propose:
1. Reducing timeout: if tests freeze, let's retry after 15 minutes instead of 45 minutes
2. Increasing number of retries: let's bump this a bit, from 3 to 4
=> [CI] Tune test timeouts

.github/workflows/ci.yml
Reverts softwaremill/tapir#3348
=> Revert "Pretty layout for tests results."

server/vertx-server/src/main/scala/sttp/tapir/server/vertx/decoders/VertxRequestBody.scala, server/vertx-server/src/test/scala/sttp/tapir/server/vertx/VertxServerTest.scala
Hi.
I am using VertxServerInterpreter.
I did a file upload with multipart and the `Part.contentType` was set to None and the ContentType of the request was not set.
Since `io.vertx.ext.web.FileUpload` in Vert.x has a `contentType` method, I thought I could simply set it if it was valid as MediaType, so I fixed it.
=> Fix: ContentType is not set for multipart file upload in VertxServer

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala
Endpoint using `patch` method is generated twice and not at all when using `trace`.
=> Fix codegen method parsing

.scala-steward.conf, project/Versions.scala
Circe Yaml 1.15.0 was released by mistake ([see circe-yaml](https://github.com/circe/circe-yaml/releases/tag/mistake-v1.15.0)).
- Replaced circe-yaml version with 0.15.1 ([see circe-yaml release](https://github.com/circe/circe-yaml/releases/tag/v0.15.1))
- Add ignore for circe 1.15.0 in scala-steward conf.
=> Fix Circe Yaml

server/finatra-server/src/main/scala/sttp/tapir/server/finatra/FinatraServerRequest.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/decoders/VertxServerRequest.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerRequest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala
Fixes #3384
Inspired by how Vert.x does this: https://github.com/vert-x3/vertx-web/pull/443/files#diff-1ddd6931545856eae625d256298d4252ce3c89150ad3ee83db5c9d985427b79bR255
=> fix(server): proper path segment decoding

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala
Parsing was already done, circe renders Instant in the correct format.
=> Add date-time support to codegen

doc/docs/json-schema.md, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/MetaSchema.scala, docs/apispec-docs/src/test/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchemaTest.scala
The meta schema ID for Draft 4 uses `http`, not `https`, according to https://json-schema.org/understanding-json-schema/reference/schema. Having it as `https` causes some parsers to reject the schema ID, even though it's also available there.
=> Fix Json Schema meta schema ID

core/src/main/scala-3/sttp/tapir/internal/SNameMacros.scala, core/src/main/scala-3/sttp/tapir/macros/SchemaMacros.scala, core/src/main/scala/sttp/tapir/Schema.scala, core/src/test/scala-3/sttp/tapir/SchemaMacroScala3Test.scala, doc/endpoint/schemas.md
=> Add derivation for schemas of union types

core/src/main/scala-2/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala-3/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/test/scala/sttp/tapir/SchemaMacroTest.scala, core/src/test/scala/sttp/tapir/SchemaMacroTestData.scala, json/pickler/src/main/scala/sttp/tapir/json/pickler/SchemaDerivation.scala, json/pickler/src/test/scala/sttp/tapir/json/pickler/SchemaDerivationTest.scala
Fixes https://github.com/softwaremill/tapir/issues/3424
=> [bugfix] Don't inherit encodedName

core/src/main/scala-2/sttp/tapir/internal/MapToMacro.scala, core/src/main/scala-3/sttp/tapir/internal/ComplietimeErrors.scala
=> Better error messages when can't map because a class has more than 22 fields

server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/NettyCatsServer.scala, server/netty-server/loom/src/main/scala/sttp/tapir/server/netty/loom/NettyIdServer.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyFutureServer.scala, server/netty-server/zio/src/main/scala/sttp/tapir/server/netty/zio/NettyZioServer.scala
Netty's `DefaultEventExecutor` has to be explicitly shut down, otherwise it may leave a hanging thread, preventing JVM from closing.
=> [bugfix] Close the DefaultEventExecutor on shutdown

server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/reactivestreams/FileWriterSubscriber.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/reactivestreams/SimpleSubscriber.scala
During performance tests of Netty servers (https://github.com/softwaremill/tapir/pull/3434) I noticed log entries like:
```
[info] 2024-01-22 11:04:21,657 [epollEventLoopGroup-2-4] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
[info] Recent access records:
[info] Created at:
[info]  io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:144)
```
This fix adds explicit release of resources, which makes the problematic logs go away. We'll look deeper into memory consumption with a profiler using performance tests.
=> [bugfix] Release Netty buffers

client/sttp-client/src/main/scala/sttp/tapir/client/sttp/EndpointToSttpClient.scala, client/sttp-client/src/test/scala/sttp/tapir/client/sttp/SttpClientRequestTests.scala
Closes https://github.com/softwaremill/tapir/issues/3470
However, I suspect other client interpreters to have the same issue, like `Http4sClientInterpreter`.
=> Fix sttp client content-type header override

build.sbt, server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/impl/JsonCodecs.scala
Closes #3477
Adding extra Circe Encoder/Decoder Boilerplate to remove the need to use Shapeless and thus supporting Scala 3 for sttp-mock-server
=> Add Scala 3 support to sttp-mock-server

perf-tests/README.md, perf-tests/src/main/scala/sttp/tapir/perf/Common.scala, perf-tests/src/test/scala/sttp/tapir/perf/GatlingLogProcessor.scala, perf-tests/src/test/scala/sttp/tapir/perf/PerfTestSuiteRunner.scala, perf-tests/src/test/scala/sttp/tapir/perf/Simulations.scala
Current way of warming-up backends has a few downsides. Here's a proposition of improvements. Instead of running `warmupScenario.andThen(actualScenario)` we run Gatling twice with just the `actualScenario` but different parameters. This gives correct Gatling reports in the end,  right now these reports are tainted with warmup data and unusable.
Our aggregated reports were correct because we were filtering for warmup data, which we don't need to do anymore after this improvement.
=> Performance tests: Fix warm-up phase

build.sbt, examples/src/main/scala/sttp/tapir/examples/BooksExample.scala, examples/src/main/scala/sttp/tapir/examples/BooksPicklerExample.scala, examples/src/main/scala/sttp/tapir/examples/client/Http4sClientExample.scala, examples/src/main/scala/sttp/tapir/examples/custom_types/BooksExampleSemiauto.scala, examples/src/main/scala/sttp/tapir/examples/logging/Logging.scala, examples/src/main/scala/sttp/tapir/examples/observability/DatadogMetricsExample.scala, examples/src/main/scala/sttp/tapir/examples/observability/OpenTelemetryMetricsExample.scala, examples/src/main/scala/sttp/tapir/examples/observability/PrometheusMetricsExample.scala, examples/src/main/scala/sttp/tapir/examples/streaming/ProxyHttp4sFs2Server.scala, grpc/examples/src/main/scala/sttp/tapir/grpc/examples/GrpcSimpleBooksExample.scala, grpc/pekko-examples/src/main/scala/sttp/tapir/grpc/examples/PekkoGrpcSimpleBooksExample.scala, grpc/protobuf/src/main/scala/sttp/tapir/grpc/protobuf/ProtoSchemaGenerator.scala, project/Versions.scala, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/NettyCatsServerOptions.scala, server/netty-server/loom/src/main/scala/sttp/tapir/server/netty/loom/NettyIdServerOptions.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyFutureServerOptions.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyDefaults.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerHandler.scala, server/netty-server/zio/src/main/scala/sttp/tapir/server/netty/zio/NettyZioServerOptions.scala, server/nima-server/src/main/scala/sttp/tapir/server/nima/NimaServerOptions.scala, server/tests/src/main/scala/sttp/tapir/server/tests/CreateServerTest.scala, serverless/aws/lambda-cats-effect/src/main/scala/sttp/tapir/serverless/aws/lambda/runtime/AwsLambdaRuntimeInvocation.scala
=> Remove dependency on logback-classic and scala-logging where unnecessary

perf-tests/README.md, perf-tests/src/main/scala/sttp/tapir/perf/Common.scala, perf-tests/src/main/scala/sttp/tapir/perf/http4s/Http4s.scala, perf-tests/src/main/scala/sttp/tapir/perf/netty/cats/NettyCats.scala, perf-tests/src/main/scala/sttp/tapir/perf/netty/future/NettyFuture.scala, perf-tests/src/main/scala/sttp/tapir/perf/pekko/PekkoHttp.scala, perf-tests/src/main/scala/sttp/tapir/perf/play/Play.scala, perf-tests/src/main/scala/sttp/tapir/perf/vertx/Vertx.scala, perf-tests/src/main/scala/sttp/tapir/perf/vertx/cats/VertxCats.scala, perf-tests/src/test/scala/sttp/tapir/perf/PerfTestSuiteParams.scala
1. Allow running tests for server groups like `pekko.*`, `vertx.future.*`, etc. 
2. Remove `*` for running all servers - there's too many of them anyway
3. Add servers with ServerLog interceptor enabled
=> Improvements to the performance testing harness

server/netty-server/zio/src/main/scala/sttp/tapir/server/netty/zio/internal/ZioStreamCompatible.scala
Without an explicit release, the netty leak detector occasionally complains of leakage like this:
ERROR i.n.u.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information. This change immediately 
releases the buffer after conversion to Chunk and silences the leak detector.
=> Release netty buffers after use

server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/internal/Fs2StreamCompatible.scala
Inspired by https://github.com/softwaremill/tapir/pull/3485
Tested with
```
perfTests/Test/runMain sttp.tapir.perf.PerfTestSuiteRunner -s netty.cats.Tapir -m PostBytes,PostLongBytes -d 25 -u 15
```
=> [bugfix] Fix memory leak of Netty byte buffer in netty.cats server

core/src/main/scala/sttp/tapir/TapirAuth.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/SecuritySchemesForEndpoints.scala, docs/openapi-docs/src/test/resources/security/expected_oauth2.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlSecurityTest.scala, examples/src/main/scala/sttp/tapir/examples/openapi/SwaggerUIOAuth2PekkoServer.scala, examples/src/main/scala/sttp/tapir/examples/security/OAuth2GithubHttp4sServer.scala
Hello everyone!
Here is proposal how to describe OAuth2 a bit more precisely. I encountered in inability to describe the client credentials flow and then I looked  through the code and  made up with such solution. It's not pretty well, but it should work.
=> Proposal to describe OAuth2 flows

server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala
Certain (malicious) requests currently zio-http `Request` objects with a `url` field that encodes to an empty String, provoking an exceptions within tapir zio-http like
```
timestamp=2024-01-24T15:01:30.568420263Z level=ERROR thread=#zio-fiber-130 message="" cause="Exception in thread "zio-fiber-130" java.lang.IllegalArgumentException: empty string is not valid uri
at sttp.model.UriInterpolator$.interpolate(UriInterpolator.scala:66)
at sttp.model.UriInterpolator$UriContext.uri(UriInterpolator.scala:39)
at sttp.model.Uri$.unsafeParse(Uri.scala:537)
at sttp.tapir.server.ziohttp.ZioHttpServerRequest.uri$lzyINIT1(ZioHttpServerRequest.scala:23)
at sttp.tapir.server.ziohttp.ZioHttpServerRequest.uri(ZioHttpServerRequest.scala:23)
at sttp.tapir.server.ziohttp.ZioHttpServerRequest.pathSegments$lzyI …
```
=> Guard against bad zio-http Request objects, sometimes provoked by malicious requests 

perf-tests/src/test/scala/sttp/tapir/perf/CsvReportPrinter.scala, perf-tests/src/test/scala/sttp/tapir/perf/PerfTestSuiteRunner.scala
When specifying test order in the command, columns in the report should be in the same order, so that it's easier and faster to copy the results into a sheet which generates charts.
=> Improve CSV reports for perf tests

.scala-steward.conf
Gatling uses scopt 3.7.1 and fails on Gatling/testOnly for scopt 4.x
=> Pin scopt 3.7.1

build.sbt, perf-tests/README.md, perf-tests/src/main/scala/sttp/tapir/perf/Common.scala, perf-tests/src/main/scala/sttp/tapir/perf/http4s/Http4s.scala, perf-tests/src/test/scala/sttp/tapir/perf/Simulations.scala, perf-tests/src/test/scala/sttp/tapir/perf/TypeScanner.scala, project/Versions.scala
This PR adds an endpoint for performance tests of WebSockets: `ws://127.0.0.1:8080/ws/ts`, returning current timestamp.
A special simulation called `WebSocketsSimulation` can then be executed. It would build a histogram reporting latency percentiles.
This simulation cannot be configured and run using standard way (`PerfTestSuiteRunner`), so the process is described in `perfTests/README.md`.
Based on https://github.com/kamilkloch/websocket-benchmark
WS endpoint will be added to other servers in separate PRs.
=> Perf test: WebSockets (http4s)

server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/NettyCatsServerInterpreter.scala, server/netty-server/loom/src/main/scala/sttp/tapir/server/netty/loom/NettyIdServerInterpreter.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyFutureServerInterpreter.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/RunAsync.scala, server/netty-server/zio/src/main/scala/sttp/tapir/server/netty/zio/NettyZioServerInterpreter.scala
The `apply` method in `RunAsync` takes an unnecessary type parameter. Kyo allows nesting of effects for composition but it's necessary to prove that a computation isn't nested to invoke methods that handle effects, which is necessary for `RunAsync`'s implementation. I'm currently using [an unsafe flat check](https://github.com/getkyo/kyo/blob/7985576fafa45d58088573653fab647c50f7fee7/kyo-tapir/src/main/scala/kyo/server/NettyKyoServer.scala#L135) to work this around. 
Modify `RunAsync.apply` to take a an `F` fixed to `Unit`, which Kyo is able to prove as flat and matches the usage in `NettyBodyListener`.
- I imagine this isn't considered a breaking change since the trait is internal.
- I'd like to keep the integration with Tapir in Kyo's repository, which is why I'm using internal APIs. Is …
=> Avoid generic type in Netty's RunAsync

perf-tests/src/main/scala/sttp/tapir/perf/http4s/Http4s.scala
Adding WS endpoint made REST endpoints unreachable.
=> Fix exposing both WS and REST endpoints in http4s perf tests

perf-tests/README.md, perf-tests/src/test/scala/sttp/tapir/perf/HistogramPrinter.scala, perf-tests/src/test/scala/sttp/tapir/perf/Simulations.scala
Similarly to what we do in `WebSocketsSimulation`, I added recording HdrHistogram response times for other tests: SimpleGet, SimpleGetMultiRoute, PostBytes, PostString, PostLongBytes.
Gatling records only p99 latency, while some interesting bottlenecks can be observed in higher percentiles, even 99.999+
P.S. The PostFile test is omitted, because I have doubts if we want to have this test at all.
=> Record HdrHistogram for standard REST perf tests

core/src/main/scala/sttp/tapir/Endpoint.scala
Fixes https://github.com/softwaremill/tapir/issues/3545
=> Make some Endpoint method lazy vals

core/src/main/scala/sttp/tapir/Endpoint.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sServerRequest.scala
Fixes https://github.com/softwaremill/tapir/issues/3546
This PR makes the `Http4sServerRequest.uri` create the `Uri` object manually to avoid expensive toString and parsing.
=> Optimize Http4sServerRequest.uri

server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerHandler.scala
Scala's `foreach` is quite difficult for the JIT to optimize. The use of shared abstract implementations in Scala's collections makes call sides become highly polymorphic and simple cases like this one end up requiring allocations and interface dispatches.
Use a `while` since `pendingResponses` is a mutable queue and can efficiently dequeue elements.
- This is part of https://github.com/softwaremill/tapir/issues/3552
- This issue isn't present in my benchmark [implementation](https://github.com/fwbrasil/rinha-2024-q1) anymore because I've fixed the nginx config to use keepalive but I thought it was still worth sending the patch.
=> optimize channel closing to avoid allocations when flushing pending responses

server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaServerRequest.scala, server/pekko-http-server/src/main/scala/sttp/tapir/server/pekkohttp/PekkoServerRequest.scala
=> Optimize server request .uri for pekko-http and akka-http

server/core/src/main/scala/sttp/tapir/server/interpreter/DecodeBasicInputs.scala
The decoding of inputs from paths is a hot operation in my [bechmark](https://github.com/fwbrasil/rinha-2024-q1) implementation and has a high allocation rate of `Tuple2` instances. 
- Since `decodedPathInputs` follows the same order and has the same size as `pathInputs` at the end of a successful decoding, use an `Array` to collect the decoded inputs and positionally refer to the original path input using `pathInputs` when folding the results.
- Modify both `matchPathInner` and `foldDecodedPathInputs` to use index-based iteration.
- Avoid `Vector.headAndTail` calls since it produces a `Tuple2` allocation. The JIT should have an easier time eliding this allocation but I think it's best to avoid it given how hot the method is.
- This is part of …
=> optimize path input decoding to avoid allocations

server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyConfig.scala
Tapir sets the `SO_LINGER` socket option by default. This config holds the connection for some time after it's closed and Netty uses a global thread pool (`GlobalEventExecutor`) with a single ephemeral thread to delay the connection close. Netty doesn't set this config by default and I couldn't identify a mechanism to make it use another thread pool.
I noticed this issue when benchmarking with a high rate of short-lived connections, which ended up generating a backlog in this thread pool and memory pressure. The `GlobalEventExecutor` also keeps constantly tearing down its thread and creating new ones, which introduces additional overhead.
Don't set the configuration by default.
- There can be cases where the config makes sense but I'd say it's important that it is done by an expert …
=> disable connection linger timeout by default

server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaModel.scala, server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaToResponseBody.scala, server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/ContentTypeCache.scala, server/pekko-http-server/src/main/scala/sttp/tapir/server/pekkohttp/ContentTypeCache.scala, server/pekko-http-server/src/main/scala/sttp/tapir/server/pekkohttp/PekkoModel.scala, server/pekko-http-server/src/main/scala/sttp/tapir/server/pekkohttp/PekkoToResponseBody.scala
Fixes https://github.com/softwaremill/tapir/issues/3544
CPU samples registered in profiler:
Before:
```
sttp.tapir.server.pekkohttp.PekkoToResponseBody.parseContentType(String) 3.53%
sttp.tapir.server.pekkohttp.PekkoModel$.parseHeadersOrThrowWithoutContentHeaders(HasHeaders) 2.13%
```
After:
```
sttp.tapir.server.pekkohttp.PekkoToResponseBody.parseContentType(String) 0.18%
sttp.tapir.server.pekkohttp.PekkoModel$.parseHeadersOrThrowWithoutContentHeaders(HasHeaders) 0.14%
```
Throughput in `SimpleGet` Simulation for 128 users:
Before:
After:
(Yes, the timestamps are OK, I ran the test on the optimized server first :))
Note:
The issue mentions one more hot frame:
```
sttp.tapir.server.pekkohttp.PekkoServerRequest.acceptsContentTypes() 2.4%
```
It's a common issue caused by the base …
=> Optimize parsing headers for pekko-http and akka-http

server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/internal/NettyCatsRequestBody.scala, server/netty-server/loom/src/main/scala/sttp/tapir/server/netty/loom/NettyIdRequestBody.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyFutureRequestBody.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyRequestBody.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/reactivestreams/SimpleSubscriber.scala, server/netty-server/zio/src/main/scala/sttp/tapir/server/netty/zio/internal/NettyZioRequestBody.scala
Fixes #3548 
This PR updates the `SimpleSubscriber` with following improvements:
1. If there is only one chunk of data (by default for body length < 8192), read it from the buffer and return immediately, requiring only one array allocation
2. If there are multiple chunks, collect all Netty `ByteBufs` without rewriting them into arrays, then copy them into the final array in `onComplete`. Disclaimer: initially I wanted to cover this case with Netty's `CompositeByteBuf`, but it turned out to be bad idea. It does some reallocations to resize internal representation underneath, resulting in making the overall performance significantly worse.
Results:
`PostBytes` Simulation
|                          |      Before |  After   |
|---------------------|:-------------:|-----------:|
| CPU samples …
=> Optimize SimpleSubscriber for Netty

build.sbt, perf-tests/README.md
Putting JFR into java opts is not convenient, because it affects performance and increases complexity in case one just wants to measure latency/throughput without profiling.
I recommend attaching profiler separately, particularly `async-profiler` which has the most accurate CPU sampling.
=> Use async-profiler as a recommended tool

core/src/main/scala/sttp/tapir/model/ServerRequest.scala, server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaServerRequest.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sServerRequest.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyServerRequest.scala, server/nima-server/src/main/scala/sttp/tapir/server/nima/internal/NimaServerRequest.scala, server/pekko-http-server/src/main/scala/sttp/tapir/server/pekkohttp/PekkoServerRequest.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerRequest.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/decoders/VertxServerRequest.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpServerRequest.scala
Fixes https://github.com/softwaremill/tapir/issues/3550, https://github.com/softwaremill/tapir/issues/3547, https://github.com/softwaremill/tapir/issues/3272
The `ServerRequest.showShort` method is used in `DefaultServerLog` and possibly in user logs as well. It is quite expensive due to the overhead of `sttp.model.Uri.unsafeParse`. This cost can be reduced by overriding `showShort`, which prints the uri from the request as directly as possible.
P.S. It's ok to just get the full `.uri()` String in Netty/Vert.X, because this string contains only the path + query params.
=> Improve showShort to avoid parsing Uri

server/vertx-server/cats/src/main/scala/sttp/tapir/server/vertx/cats/streams/fs2.scala
This PR resolves https://github.com/softwaremill/tapir/issues/3539. `fs2.Channel` is used for more efficient stream merging, outperforming the previous `Stream#mergeHaltL` and `Stream#parJoin` methods.
Here is the latency overhead before and after:
=> Updated Vertx Cats WebSocket

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala
It can be very tricky figuring out exactly where in an openapi spec the generator is barfing. This pr adds the path and method to any endpoint generation errors, to make it a little easier to locate the source of the issue
=> Better codegen errors

doc/generator/sbt-openapi-codegen.md, openapi-codegen/cli/src/main/scala/sttp/tapir/codegen/GenScala.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/BasicGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenKeys.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenPlugin.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenTask.scala
I've been thinking about this for ages and finally got around to it. If autogenerating files for a very large spec, it's possible to hit the JVM limits on class size since all definitions go into the same object; so from a purely technical perspective, this does enable working with certain specs that would otherwise require some fudging (such as calling the codegen cli on multiple input files); although I confess to also just finding it a bit tidier. This pr adds a new flag `useHeadTagForObjectNames` (defaulting to false, to preserve existing behaviour). If this flag is true then the generated endpoints are grouped by the first tag, and each group put into a new file+object with the same name as that tag. All types/enums/classes generated from schemas remain in the default object model as …
=> Codegen: Add new `useHeadTagForObjectNames` flag to permit splitting generated endpoint objects by tag

doc/generator/sbt-openapi-codegen.md, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/BasicGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala
Support for enum query params in codegen. I've gone for case-insensitive decoding here, but arguably case-sensitive would be the better option; it should be very easy to change or make configurable later on.
=> codegen: support enum query params

integrations/cats/src/main/scala/sttp/tapir/integ/cats/TapirCodecCats.scala, integrations/cats/src/test/scala/sttp/tapir/integ/cats/TapirCodecCatsTest.scala
NonEmptyVector was not covered. Added production code and test coverage, very similar to other NonEmpty collections
=> Added missing Schema/Codec for cats NonEmptyVector to integration module

build.sbt, perf-tests/README.md, perf-tests/src/main/scala/sttp/tapir/perf/apis/Endpoints.scala, perf-tests/src/main/scala/sttp/tapir/perf/netty/loom/NettyId.scala, perf-tests/src/main/scala/sttp/tapir/perf/nima/Nima.scala
This PR adds Loom-based backends to performance tests. These backends were used for the "Benchmarking Tapir: Part 3 (Loom)" blog post.
=> Performance tests for loom-based backends

build.sbt, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/NettyCatsServer.scala, server/netty-server/loom/src/main/scala/sttp/tapir/server/netty/loom/NettyIdServer.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyConfig.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyFutureServer.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerHandler.scala, server/netty-server/zio/src/main/scala/sttp/tapir/server/netty/zio/NettyZioServer.scala
Closes https://github.com/softwaremill/tapir/issues/2971
=> Allow setting Server header in Netty config

build.sbt, doc/generator/sbt-openapi-codegen.md, openapi-codegen/cli/src/main/scala/sttp/tapir/codegen/GenScala.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/BasicGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenKeys.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenPlugin.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenTask.scala
Starts to address https://github.com/softwaremill/tapir/issues/840
Adds support for jsoniter serdes in codegen.
Since, in order to support jsoniter, it became necessary to explicitly define the desired serdes, I've also moved from `io.circe.generic.auto._` to `io.circe.generic.semiauto._`; the latter of which has the notable benefit that if it's going to fail to compile, it doesn't take until the heat death of the universe to do so.
I've also modified the model generation. When multipart file support was initially added, the generated type for `format: binary` strings was changed to `sttp.model.Part[java.io.File]`, which notably does not work with json serialisation. In order to retain that support, I've added a check so that if a schema is _not_ used in any application/json content we'll …
=> codegen: Jsoniter support (#840)

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/DefaultValueRenderer.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/SpecificationExtensionRenderer.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/ModelParserSpec.scala
The OpenApi spec permits defining [Specification Extensions](https://swagger.io/specification/#specification-extensions) on a large number of components. Not all of those have any kind of obvious mapping into the tapir model; however it feels natural to map extensions on path and operation definitions into `.attribute` declarations on generated endpoints, thus making this metadata accessible at runtime for $variousSundryPurposes
For context, this would enable me to implement some specific authorization guards cleanly at the implementation layer without having to hack around with tags. I don't think tapir would currently emit any specification extensions when generating the openapi from an endpoint with attributes, so I guess there's a break in idempotency there? But since we currently …
=> Codegen: Generate attributes on endpoints for any specification extensions defined on path or operation objects

core/src/main/scala-3/sttp/tapir/typelevel/IntersectionTypeMirror.scala, core/src/main/scala-3/sttp/tapir/typelevel/UnionTypeMirror.scala
The issue was found by the scala 3 open community build, and caused the macro expansion of the tests to fail compilation on scala 3.4.0. The previous implementation generated types which then later could not be "inline matched" by the newer compiler (generating new compile time errors), but somehow managed to go through the cracks of the older compiler. Those types would have shape like:
```scala
scala.*:[_ >: scala.Nothing <: scala.Any, _ >: scala.Nothing <: scala.Any][scala.Some[scala.Any], scala.Tuple$package.EmptyTuple]
```
(a type applied with wildcards, and also applied with correct types).
This PR fixes the implementation, so that the macro expansion will be successful for users using tapir on scala 3.4.0.
Underlying issue and fix found by @nicolasstucki
More information: …
=> Fix tapir on scala 3.4.0: an incorrect form of a tuple type being generated

doc/generator/sbt-openapi-codegen.md, openapi-codegen/cli/src/main/scala/sttp/tapir/codegen/GenScala.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/BasicGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/ModelParserSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/testutils/CompileCheckTestBase.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenKeys.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenPlugin.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenTask.scala
Supports `oneOf` schemas in codegen. 
For both circe and jsoniter, when a `oneOf` schema has no discriminator, on decode we iterate over the subtype schemas in their declared order and stop on the first successfully decoded type. Obviously this means that it's possible to roundtrip an object to a different type if the serialised form can be validly decoded to multiple different subtypes, so I've added in a check that the models can be safely disambiguated this way (the check can be disabled with `openapiValidateNonDiscriminatedOneOfs := false` in case of false positives or if you want to live like a cowboy). This falling-back method is probably not the most efficient implementation, but writing a more efficient one generically is beyond me.
For jsoniter-scala support this requires  the …
=> codegen: implement oneOf support

.github/workflows/ci.yml
This should silence GH warnings about nodejs 16.
=> [CI] update checkout and setup-java actions

client/testserver/src/main/scala/sttp/tapir/client/tests/HttpServer.scala, server/http4s-server/src/main/scalajvm/sttp/tapir/server/http4s/Http4sDefaultServerLog.scala
Hi, it's me about logging again.
I noticed the http4s server integration was using log4s, [which will be removed in http4s 1.0](https://github.com/http4s/http4s/commit/3b553ccd98bb7e74b44f42aca1306976696f73e9).
Http4s now uses log4cats internally.
=> Remove log4s usage in http4s-server integration

server/netty-server/cats/src/test/scala/sttp/tapir/server/netty/cats/NettyCatsServerTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerWebSocketTests.scala
I suspect that https://github.com/softwaremill/tapir/pull/3628 might have introduced high instability of tests. They time out very frequently, exhausting max retries. 
I tried to isolate the cause, but I need more time for the analysis. To unblock PRs until then, I propose to restore `ServerWebSocketTests` to its state from before the Netty Web Sockets PR. This seems to make the tests more reliable again. I will keep on investigating what's the concrete issue.
=> Temporarily restore previous Web Socket tests

server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerWithContextTest.scala, server/play29-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala, server/play29-server/src/test/scala/sttp/tapir/server/play/PlayServerWithContextTest.scala
=> Using RequestHeader that without context for WebSocket handling

doc/server/netty.md, perf-tests/src/main/scala/sttp/tapir/perf/netty/loom/NettySync.scala, server/netty-server/loom/src/main/scala/sttp/tapir/server/netty/loom/NettySyncRequestBody.scala, server/netty-server/loom/src/main/scala/sttp/tapir/server/netty/loom/NettySyncServer.scala, server/netty-server/loom/src/main/scala/sttp/tapir/server/netty/loom/NettySyncServerInterpreter.scala, server/netty-server/loom/src/main/scala/sttp/tapir/server/netty/loom/NettySyncServerOptions.scala, server/netty-server/loom/src/test/scala/sttp/tapir/server/netty/loom/NettySyncServerTest.scala, server/netty-server/loom/src/test/scala/sttp/tapir/server/netty/loom/NettySyncTestServerInterpreter.scala
=> Renamed NettyId to NettySync

core/src/main/scala/sttp/tapir/Endpoint.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerOneOfTests.scala
The errorOutVariantsPrepend method should match over the prepended error variants before falling back to the default variant passed to .errorOut or other, previously defined prepend variants.
This fixes https://github.com/softwaremill/tapir/issues/3592
=> [FIX] `errorOutVariantsPrepend` should try to match passed variants before falling back to the default one

doc/generator/sbt-openapi-codegen.md, openapi-codegen/cli/src/main/scala/sttp/tapir/codegen/GenScala.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/SchemaGenerator.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/BasicGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenKeys.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenPlugin.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenTask.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedSchemas.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_scala3/Expected.scala.txt
This would address two issues with the code currently being generated:
1) When using the codegen, until now I've had to add in a sourceGenerator hack to replace `import sttp.tapir.generic.auto._` with a `implicit def schemaForAny[T]: sttp.tapir.Schema[T] = sttp.tapir.Schema.any[T]` stub, since I was hitting javac class size limits (also, compilation was taking a while to fail - I guess because the leaf schemas were being regenerated for everything that needed it? I don't really know enough about how the scala compiler handles memoization of implicit resolution to be sure of that though...). ANYWAY:
2) This also means that the schemas for ADTs should be more* correct (automatic derivation didn't know about discriminators or lack thereof).
This pr will create explicit schemas for every …
=> codegen: Semiauto schema derivation

docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOperationResponse.scala, docs/openapi-docs/src/test/resources/oneOf/expected_the_same_status_codes_and_content_types.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlOneOfTest.scala
Fixes #3660 
Chose to use `anyOf` (not `oneOf`) because there's no discriminator and we cannot guarantee that only one model will match.
=> Generate `anyOf` schema for `oneOfVariant`s with the same status code and content-type

server/netty-server/sync/src/main/scala/sttp/tapir/server/netty/sync/internal/ox/OxDispatcher.scala, server/netty-server/sync/src/main/scala/sttp/tapir/server/netty/sync/internal/reactivestreams/OxProcessor.scala, server/netty-server/sync/src/test/scala/sttp/tapir/server/netty/sync/NettySyncServerTest.scala
This PR enhances the `OxDispatcher` usage, so that we can externally interrupt a running process when Web Sockets Processor runs into `onError` or `orComplete`. We need this in order to handle situations like `ChannelSubscriber` blocked on `source.receiveOrClosed()` if there are no responses in the outgoing source, but the client ends connection. In such case the asynchronous process (fork started by OxDispatcher) would never finish, leaving an orphaned open scope.
When we explicitly cancel the fork, we also make sure that any forks created by user in their `Pipe` get interrupted.
=> [bugfix] Ensure cancelation of WS pipeline forks

server/netty-server/sync/src/main/scala/sttp/tapir/server/netty/sync/NettySyncServer.scala, server/netty-server/sync/src/main/scala/sttp/tapir/server/netty/sync/internal/ox/OxDispatcher.scala, server/netty-server/sync/src/test/scala/sttp/tapir/server/netty/sync/NettySyncTestServerInterpreter.scala
Whenever I read OxDispatcher code I got a bit confused, and got worried that the captured `Ox` scope is going to be used when calling `.runAsync` on another thread. 
Separating creation of the dispatcher (where the scope needs to be captured) from scheduling computations (where we just need to send a message to an actor on a channel) maybe will clarify this for future users (and me ;) )
=> Separate creation & usage of OxDispatcher

server/core/src/main/scala/sttp/tapir/server/interceptor/exception/ExceptionHandler.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sRequestBody.scala
This update optimizes how `Stream[F, Byte]` is handled.
- For `StringBody`, instead of combining all chunks and copying the entire resulting byte array, I propose `body.through(decodeWithCharset(...).compile.string`, which decodes incoming byte chunks into smaller Strings, and then collects them efficiently into one final `String` using fs2's `.string`.
- More importantly, for `InputStreamBody` and `InputStreamBodyRange`, I propose `fs2.io.toInputStreamBody(body)` to produce a lazily evaluated `InputStream` instead of fetching all bytes and returning them wrapped  in a `ByteArrayInputStream`.
P.S. Similar optimization to `StringBody` can be adapted to `netty-cats`
=> Optimize byte array operations in Http4sRequestBody

doc/server/ziohttp.md, examples/src/main/scala/sttp/tapir/examples/HelloWorldZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/ZioExampleZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/observability/ZioMetricsExample.scala, examples/src/main/scala/sttp/tapir/examples/openapi/RedocZioHttpServer.scala, examples/src/main/scala/sttp/tapir/examples/streaming/StreamingZioHttpServer.scala, examples2/src/main/scala/sttp/tapir/examples2/security/ServerSecurityLogicZio.scala, project/Versions.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpCompositionTest.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala
Supersedes #3768 and fixes incompatibilities introduced by deprecating `HttpApp`.
=> chore: Upgrade zio-http to version 3.0.0-RC7

integrations/iron/src/main/scala/sttp/iron/codec/iron/TapirCodecIron.scala, integrations/iron/src/main/scala/sttp/iron/codec/iron/UnionTypeMirror.scala, integrations/iron/src/test/scala-3/sttp/iron/codec/iron/TapirCodecIronTestScala3.scala
These fixes should address issues reported here: https://softwaremill.community/t/how-to-improve-open-api-documentation-for-iron-refined-types/396/9
1. `LessEqual` and `GreaterEqual` validators aren't resolved correctly if these predicates are combined with other predicates using `Or` or `And`. They would be handled by `validatorForDescribedOr`, so I added variants called `validatorForDescribedOrGe` and `validatorForDescribedOrLe` witch additional "witnesses" like `isGe: P =:= GreaterEqual[Num]` to redirect back to `validatorForGreaterEqual` and `validatorForLessEqual`.
2. Constraint `In[(1, 2, 3)]` was handled as a standard union type constraint, resulting in a list of validators, where each validator was a `Validator.enumeration(List(int))` with a single value in the list. I have added …
=> Fixes for iron derivation for GreaterEqual, LessEqual, In

server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sWebSockets.scala, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/internal/WebSocketPipeProcessor.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/ws/WebSocketFrameConverters.scala, server/netty-server/sync/src/main/scala/sttp/tapir/server/netty/sync/internal/ws/OxSourceWebSocketProcessor.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerWebSocketTests.scala, server/vertx-server/cats/src/test/scala/sttp/tapir/server/vertx/cats/CatsVertxServerTest.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/streams/websocket.scala, server/vertx-server/src/test/scala/sttp/tapir/server/vertx/VertxServerTest.scala, server/vertx-server/zio/src/test/scala/sttp/tapir/server/vertx/zio/ZioVertxServerTest.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioWebSockets.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala
When handling incoming WebSocket frames, there was a missing case for a "non-final data frame and no data accumulated".
1. I added the case and moved frame concatenation to `WebSocketFrameConverters`, so it's shared between netty-sync and netty-cats
2. I also added cases where a binary frame comes after a text frame, this is specific to Netty (a `WebSocketContinuationFrame` is a binary frame that follows a text frame). 
3. I added test cases mentioned in 1. to other backends where they were missing: Vert.X, zio-http, http4s.
BTW it turns out http4s does frame concatenation by itself, regardless of our configuration.
After adding missing cases, there are issues with concatenation in zio-http and vert.x. The stream freezes after receiving first frame in the accumulation. This needs separate …
=> Fix WebSocket frame concatenation for Netty

doc/endpoint/pickler.md, json/pickler/src/main/scala/sttp/tapir/json/pickler/PicklerConfiguration.scala, json/pickler/src/main/scala/sttp/tapir/json/pickler/Writers.scala, json/pickler/src/main/scala/sttp/tapir/json/pickler/macros.scala, json/pickler/src/test/scala/sttp/tapir/json/pickler/Fixtures.scala, json/pickler/src/test/scala/sttp/tapir/json/pickler/PicklerBasicTest.scala
This PR enhances Pickler JSON codec with 2 features:
1. When deserializing, missing fields for `Option` fields are now treated as `None` instead of causing errors.
2. When serializing a `None`, a `transientNone` flag from `PicklerConfiguration` decides how to handle it:
a) skip the field entirely (when transientNone == true, default)
b) serialize value as `null` (when transientNone == false)
The flag name and behavior are inspired by jsoniter-scala. This changes the current behavior, which was b). Skipping by default seems like a more convenient default though.
=> Pickler: add transientNone for optional fields

integrations/iron/src/main/scala/sttp/iron/codec/iron/TapirCodecIron.scala, integrations/iron/src/test/scala-3/sttp/iron/codec/iron/TapirCodecIronTestScala3.scala
This PR adds validator for `Pure` constraint, which allows to automatically derive `Schema` and `Codec` instances for pure newtypes, eg `type NewtypeInt = Int :| Pure`
=> Iron: add validator for Pure constraint

build.sbt, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/NettyCatsServer.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyConfig.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyFutureServer.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyBootstrap.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerHandler.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/UnhandledExceptionHandler.scala, server/netty-server/sync/src/main/scala/sttp/tapir/server/netty/sync/NettySyncServer.scala, server/netty-server/zio/src/main/scala/sttp/tapir/server/netty/zio/NettyZioServer.scala
Fixes https://github.com/softwaremill/tapir/issues/3795
This PR replaces usage of `ReadTimeoutHandler` with `IdleStateHandler`.
The `ReadStateHandler` was configured using `NettyConfig.requestTimeout` value, but it wasn't serving the purpose of failing when there is no response within given timeout. This handler throws an exception when there is no data _read_ , which means no request from the client.
We will be using `IdleStateHandler` to deal with timeouts correctly:
1. One such handler is created for each request, with timeout set to `nettyConfig.requestTimeout`. If it expires, the channel is closed, a HTTP 503 response is returned, and in-flight requests in the channel are canceled. An error is logged.
2. if backend manages to produce a response, the handler is removed.
3. Thus, in …
=> Netty servers: handle requestTimeout properly, add idleTimeout

project/Versions.scala, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/internal/WebSocketPipeProcessor.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerHandler.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/ws/WebSocketPingPongFrameHandler.scala, server/netty-server/sync/src/main/scala/sttp/tapir/server/netty/sync/internal/reactivestreams/OxProcessor.scala, server/netty-server/sync/src/main/scala/sttp/tapir/server/netty/sync/internal/ws/OxSourceWebSocketProcessor.scala, server/netty-server/sync/src/test/scala/sttp/tapir/server/netty/sync/NettySyncServerTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerWebSocketTests.scala
Fixes https://github.com/softwaremill/tapir/issues/3776
With this fix, netty-cats and netty-sync backends should handle `Close` frame sequentially, after all previously received frames are processed.
=> Fix handling of WS Close frame in Netty backends

perf-tests/README.md, perf-tests/src/test/scala/sttp/tapir/perf/Simulations.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala, server/play29-server/src/main/scala/sttp/tapir/server/play/PlayServerInterpreter.scala
Related issue: https://github.com/softwaremill/tapir/issues/3549
This PR makes the following changes:
- in `PlayServerInterpreter.toRoutes`, avoid instantiating a `ServerInterpreter` for each request.
- Fix scenario names in `Simulations.scala`, to avoid a runtime error related to duplicate names.
-------------
I ran some of the gatling tests a couple times (as explained in the perf-tests [README](https://github.com/softwaremill/tapir/blob/master/perf-tests/README.md)), and this change seems to increase throughput.
I started a server using 
```
perfTests/runMain sttp.tapir.perf.apis.ServerRunner play.Tapir
```
Then I ran the tests using
```
perfTests/Gatling/testOnly sttp.tapir.perf.SimpleGetSimulation
perfTests/Gatling/testOnly sttp.tapir.perf.PostLongBytesSimulation
```
1) Without the …
=> Improve PlayServerInterpreter.toRoutes

perf-tests/src/main/scala/sttp/tapir/perf/play/Play.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayServerWithContextTest.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayTestServerInterpreter.scala, server/play29-server/src/test/scala/sttp/tapir/server/play/PlayServerTest.scala, server/play29-server/src/test/scala/sttp/tapir/server/play/PlayServerWithContextTest.scala, server/play29-server/src/test/scala/sttp/tapir/server/play/PlayTestServerInterpreter.scala
Closes https://github.com/softwaremill/tapir/issues/3549
Turns out Play calls `DefaultPekkoHttpServerComponents.route` on each request, so we shouldn't rebuild routing in that method. Instead, it should return a pre-calculated value.
This isn't a fix to Tapir per se, but to all usages of the Play server we have in standard tests and performance tests.
Performance tests used to show terrible latency/throughput and Tapir code occupying over 90% of all frames registered by the profiler.
After this fix, the latency is dramatically better (see the blue line):
Throughput also reaches great values: ~160k reqs/sec vs 5k before the fix. Tapir code occupies no more than 9% of all profiler frames. There may be still some possible optimizations in the late 0.999s of latency to reach values closer to …
=> Play: Optimize usages of `route`

integrations/refined/src/main/scala/sttp/tapir/codec/refined/TapirCodecRefined.scala, integrations/refined/src/test/scala-2/sttp/tapir/codec/refined/TapirCodecRefinedTestScala2.scala, integrations/refined/src/test/scala-3/sttp/tapir/codec/refined/TapirCodecRefinedTestScala3.scala, integrations/refined/src/test/scala/sttp/tapir/codec/refined/TapirCodecRefinedTest.scala
Fixes https://github.com/softwaremill/tapir/issues/3828
- Schemas for types with refined constrains `MinSize`, `MaxSize` and `NonEmpty` will now get proper non-custom validators, translated to `minItems` and `maxItems` properties in specs.
- Schemas for types validated with `MinSize` will now be marked as required (`optional = false`)
Example fields:
```scala
nicknames: List[String Refined (MinSize[3] And MaxSize[6])] Refined NonEmpty,
nicknames2: List[String Refined MinSize[4]] Refined (MaxSize[7] And MinSize[2]),
nicknames3: List[String] Refined MaxSize[50]
```
Docs:
=> Refined: Treat fields with NonEmpty or MinSize(>0) as required

integrations/iron/src/main/scala/sttp/iron/codec/iron/TapirCodecIron.scala, integrations/iron/src/test/scala-3/sttp/iron/codec/iron/TapirCodecIronTestScala3.scala
Fixes https://github.com/softwaremill/tapir/issues/3829
Should now behave similarly to changes made to Refined in https://github.com/softwaremill/tapir/pull/3839
=> Iron: Support MinLength, MaxLength, Not[Empty] for Iterables

core/src/main/scala/sttp/tapir/Endpoint.scala, docs/redoc/src/main/scala/sttp/tapir/redoc/Redoc.scala, docs/swagger-ui/src/main/scala/sttp/tapir/swagger/SwaggerUI.scala, server/core/src/test/scala/sttp/tapir/server/interpreter/FilterServerEndpointsTest.scala
This PR adds two methods to `Endpoint` to avoid boilerplates 
- `serverLogicSuccessPure` - For cases where the result is always a pure success ( healthcheck, stream*, etc... )
- `serverLogicErrorPure` - For cases where the result is always a pure failure 
\* stream = when you build a streamed API the logic is `F[Either[E, Stream[...]]]` since the errors and the side effects will be handled by the stream you often have to write `.serverLogicSuccess(i => myStream(i).pure[F])`. with `serverLogicSuccessPure` you can avoid that small boiler plate when needed.
I also wonder if it would be useful to add something like `serverStreamLogic` which is equals to `serverLogicSuccessPure` but have the constraints that the output is a stream ( Idk if this is feasible ). The advantages in this case are …
=> Add Endpoint serverLogicSuccessPure and serverLogicErrorPure

server/netty-server/cats/src/test/scala/sttp/tapir/server/netty/cats/NettyFs2StreamingCancellationTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerWebSocketTests.scala
This should fix occasional failures of the "empty client" test on Vertx.
There's also an improvement to fs2 streaming cancelation test, which sometimes failed due to a check on unreliable  number of accumulated elements.
=> Fix some occasionally failing tests

core/src/main/scala/sttp/tapir/Schema.scala, core/src/test/scala/sttp/tapir/SchemaTest.scala, docs/apispec-docs/src/test/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchemaTest.scala
Fixes https://github.com/softwaremill/tapir/issues/3833
=> Improve name generation for Schemas of Eithers with parameterized types

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala
Small change to openapi codegen to make non-required query parameters to generate as `Option[_]` types.
=> codgegen: Optional query parameters

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala
This makes endpoints from generated code return serialised default values in json objects - which is what I'd expect.
It still uses the defaults when deserialising requests.
=> codegen: serialize default values with jsoniter

integrations/iron/src/main/scala/sttp/iron/codec/iron/IntersectionTypeMirror.scala, integrations/iron/src/main/scala/sttp/iron/codec/iron/TapirCodecIron.scala, integrations/iron/src/main/scala/sttp/iron/codec/iron/UnionTypeMirror.scala, integrations/iron/src/test/scala-3/sttp/iron/codec/iron/TapirCodecIronTestScala3.scala
Fixes https://github.com/softwaremill/tapir/issues/3830
This PR fixes some bugs in iron integration:
* union and intersection mirrors were using dealiased types, causing predicates like `MinLength` become `DescribedAs[Length[GreaterEqual[0]]], _]`. This made our validator resolution fail.
* union and intersection primitive elements had an issue in `summonFrom`, resulting in wrong validators being resolved
These fixes should cover cases of problematic schema resolution for types with constrains like `DescribedAs`, `String :| Not[Empty]`, unions, intersections, and possibly some other cases.
=> Fixes in iron: union, intersection, Not[Empty] and other cases

doc/generator/sbt-openapi-codegen.md, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenKeys.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenPlugin.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenTask.scala
This will permit generating multiple packages based on multiple schemas (e.g. for generating versioned apis)
=> codegen: add openapiAdditionalPackages arg to sbt plugin

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EnumGenerator.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/ModelParserSpec.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_scala3/Expected.scala.txt
Support enums in path params. Most of the diff here is just renaming variables and types to reflect that they no longer pertain only to _query_ params, but also to path params; nearly all of the implementation is supported just by reusing those existing mechanisms
=> codegen: Support enums in paths

build.sbt, project/Versions.scala
As some dependencies are now available for Scala Native 0.5.x, we are restoring nativePlatform build for: `core`, `files`, `cats`, `json/circe`, `json/upickle`, `server/core`, and `client/core`.
We still can't have a proper backend until `cats-effect` + `fs2` + `http4s` catch up.
=> Restore Native support for core and a few other modules

server/tests/src/main/scala/sttp/tapir/server/tests/TestServerInterpreter.scala
The `server` resource uses `serverWithStop` and ignores its `release` effect. As a result, non-erroneous closing of this resource doesn't release anything, so we need to call the hook manually.
=> Fix releasing resources in TestServerInterpreter

server/akka-http-server/src/test/scala/sttp/tapir/server/akkahttp/AkkaHttpTestServerInterpreter.scala, server/armeria-server/src/test/scala/sttp/tapir/server/armeria/ArmeriaTestServerInterpreter.scala, server/finatra-server/src/test/scala/sttp/tapir/server/finatra/FinatraTestServerInterpreter.scala, server/http4s-server/src/test/scala/sttp/tapir/server/http4s/Http4sTestServerInterpreter.scala, server/http4s-server/zio/src/test/scala/sttp/tapir/server/http4s/ztapir/ZHttp4sTestServerInterpreter.scala, server/jdkhttp-server/src/test/scala/sttp/tapir/server/jdkhttp/JdkHttpTestServerInterpreter.scala, server/netty-server/cats/src/test/scala/sttp/tapir/server/netty/cats/NettyCatsTestServerInterpreter.scala, server/netty-server/src/test/scala/sttp/tapir/server/netty/NettyFutureTestServerInterpreter.scala, server/netty-server/sync/src/test/scala/sttp/tapir/server/netty/sync/NettySyncTestServerInterpreter.scala, server/netty-server/zio/src/test/scala/sttp/tapir/server/netty/zio/NettyZioTestServerInterpreter.scala, server/nima-server/src/test/scala/sttp/tapir/server/nima/NimaTestServerInterpreter.scala, server/pekko-http-server/src/test/scala/sttp/tapir/server/pekkohttp/PekkoHttpTestServerInterpreter.scala, server/play-server/src/test/scala/sttp/tapir/server/play/PlayTestServerInterpreter.scala, server/play29-server/src/test/scala/sttp/tapir/server/play/PlayTestServerInterpreter.scala, server/tests/src/main/scala/sttp/tapir/server/tests/CreateServerTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/TestServerInterpreter.scala, server/vertx-server/cats/src/test/scala/sttp/tapir/server/vertx/cats/CatsVertxTestServerInterpreter.scala, server/vertx-server/src/test/scala/sttp/tapir/server/vertx/VertxTestServerInterpreter.scala, server/vertx-server/zio/src/test/scala/sttp/tapir/server/vertx/zio/ZioVertxTestServerInterpreter.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpTestServerInterpreter.scala, serverless/aws/lambda-cats-effect-tests/src/test/scala/sttp/tapir/serverless/aws/lambda/tests/AwsLambdaCreateServerStubTest.scala, serverless/aws/lambda-cats-effect-tests/src/test/scala/sttp/tapir/serverless/aws/lambda/tests/AwsLambdaStubHttpTest.scala, serverless/aws/lambda-zio-tests/src/test/scala/sttp/tapir/serverless/aws/ziolambda/tests/AwsLambdaCreateServerStubTest.scala, serverless/aws/lambda-zio-tests/src/test/scala/sttp/tapir/serverless/aws/ziolambda/tests/AwsLambdaStubHttpTest.scala
Instead of defining `serverWithStop` and deriving `server` on top of it, each backend's test interpreter will now do the opposite: define `server`, which returns a `Resource[IO, Port]`, then use this in base `serverWithStop`.
=> Fix shutdowns in test servers

docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/ExampleConverter.scala, docs/asyncapi-docs/src/main/scala/sttp/tapir/docs/asyncapi/MessagesForEndpoints.scala, docs/asyncapi-docs/src/test/resources/expected_json_example_name_summary.yml, docs/asyncapi-docs/src/test/scala/sttp/tapir/docs/asyncapi/VerifyAsyncAPIYamlTest.scala, project/Versions.scala
Updated sttpApispec to 0.11.
Fixes example rendering issue (softwaremill/sttp-apispec#174, #3901).
Note tapir lacks convenient api to define async example name and summary (see TODO in the VerifyAsyncAPIYamlTest).
=>  Async api example rendering bugfix

core/src/main/scala/sttp/tapir/Endpoint.scala, doc/docs/openapi.md, doc/testing.md, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/EndpointToOpenAPIDocs.scala, docs/openapi-docs/src/main/scala/sttp/tapir/docs/openapi/OpenAPIDocsOptions.scala, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/EndpointToOpenAPIDocsTest.scala, testing/src/main/scala/sttp/tapir/testing/EndpointVerificationError.scala, testing/src/main/scala/sttp/tapir/testing/EndpointVerifier.scala, testing/src/test/scala/sttp/tapir/testing/EndpointVerifierTest.scala
From my interpretation on the OpenAPI spec, operationId's (endpoint names), should be unique. This test shows it is currently not detected in the EndpointVerifier and when generating the OpenAPI spec it does not warn or fail on duplicate operationId's, it just generates it.
Shall I continue implement the test in the EndpointVerifier?
Should the `OpenAPIDocsInterpreter` throw an exception on duplicate names? Or perhaps add a `toVerifiedOpenAPI: Either[OpenAPIError, OpenAPI]` method to the interpreter and not allow e.g. duplicate operationId's?
Refs: https://softwaremill.community/t/duplicate-operationids/416/7
=> test(testing): add test to detect duplicate endpoint names

doc/server/http4s.md, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sServerInterpreter.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/package.scala, server/http4s-server/src/test/scala/sttp/tapir/server/http4s/Http4sServerTest.scala
Hi!  I'd like to use the context of http4s `ContextRoutes` as part of security logic, though AFAICS currently threading through http4s context is supported only by `contextIn` which adds the context as a server logic input.  This PR adds a corresponding `securityContextIn` method for doing the same for security logic.
Thanks!
=> Add contextSecurityIn for http4s endpoints

integrations/iron/src/main/scala/sttp/iron/codec/iron/TapirCodecIron.scala
This change adds 1 more intermediate `LowPriorityValidatorForPredicate` trait which now contains `validatorForDescribed*` methods. Change is motivated by [failures in Scala 3 Open Community Build ](https://github.com/VirtusLab/community-build3/actions/runs/9915156118/job/27395918787) under changes to implicit resolution in Scala 3.6. 
Example of snippet that fails to compile
```scala
type IntConstraint = LessEqual[3]
type LimitedInt = Int :| IntConstraint
val limitedIntCodec = summon[PlainCodec[LimitedInt]]
```
Under 3.3 LTS compiler can construct `PlainCodec` in 2 different ways, but implicitly picks one of the alternatives. This behaviour has changed since 3.6 and the compiler warns about it since 3.5:
```scala
arn] -- Warning: …
```
=> Move `validatorForDescribed*` to LowPriority trait to prevent ambigious implicits under Scala 3.6+

core/src/main/scala/sttp/tapir/Schema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/MetaSchema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchema.scala, docs/apispec-docs/src/test/scala/sttp/tapir/docs/apispec/schema/TapirSchemaToJsonSchemaTest.scala
Relates to #2604.
Looking at https://json-schema.org/understanding-json-schema/reference/array#tupleValidation it seems Array is natural representation for tuples (and this is what circe mentioned in the ticket does by default).
- For now PR only adds attribute to allow such schema to be defined; if agreed - probably default schema generation for scala tuples should be updated to enable it by default.
- Also schema rendering should be updated, as it produces `Draft04`, which used slightly different way of representing array element type constraints (`items` instead of `prefixItems`).
- array arity constraint should be also rendered
=> ProductAsArray attribute added, alternative rendering of SProduct

core/src/main/scala-3/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala, core/src/main/scala/sttp/tapir/Schema.scala, core/src/main/scala/sttp/tapir/SchemaType.scala, core/src/test/scala/sttp/tapir/SchemaMacroTest.scala, core/src/test/scala/sttp/tapir/generic/SchemaGenericAutoTest.scala, docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala, docs/asyncapi-docs/src/test/resources/expected_coproduct_with_discriminator.yml, docs/asyncapi-docs/src/test/scala/sttp/tapir/docs/asyncapi/VerifyAsyncAPIYamlTest.scala, docs/openapi-docs/src/test/resources/coproduct/expected_coproduct_discriminator.yml, docs/openapi-docs/src/test/resources/coproduct/expected_coproduct_discriminator_nested.yml, docs/openapi-docs/src/test/resources/coproduct/expected_coproduct_discriminator_with_enum_circe.yml, docs/openapi-docs/src/test/resources/coproduct/expected_coproduct_independent.yml, json/pickler/src/test/scala/sttp/tapir/json/pickler/SchemaDerivationTest.scala, project/Versions.scala
An alternative approach to #3763
cc @kamilkloch @zorba128 @seveneves
Closes #3909
=> Add an encoded discriminator value attribute for coproducts, use it to render const constraints

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedSchemas.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
It turns out that children of oneOf declarations with a discriminator should have the discriminator declared as a property (cf https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/), and some other openapi tooling gets broken if the children do not have that property declaration. We cannot simply declare the discriminator property on a child to be a standard field since that breaks jsoniter adt codecs (for jsoniter, the discriminator must _not_ be a field on the child class). I also didn't like the idea of dropping the property entirely from the child if it's declared in the openapi yaml, since that feels like a violation of the declared construct (even if it does accord with the declaration in over-the-wire formats).
As a compromise between these different …
=> codegen: permit parent properties in one of children

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EnumGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/project/build.properties, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/project/plugins.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/src/main/scala/Main.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/swagger.yaml, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/test
Fixes a couple of issues with jsoniter in scala 3:
- Enum serde generation now works
- Custom discriminator mappings now work
I'm not sure what magic makes `JsonCodecMaker.simpleClassName` work when trying to construct the full path name fails, but since the parent traits for all oneOf definitions are sealed, and our class heirarchy is completely flat, there's no potential for ambiguity just using the simple class name.
With this change, we no longer do anything with the full package path in the serde generations, so I was able to remove that parameter entirely from the class, which is nice.
=> codegen: Fix issues with jsoniter in scala3

generated-doc/out/generator/sbt-openapi-codegen.md, openapi-codegen/cli/src/main/scala/sttp/tapir/codegen/GenScala.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/BasicGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenKeys.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenPlugin.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenTask.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/src/test/scala/BinaryEndpoints.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Adding support for `application/octet-stream` content types, via `streamBody`/`streamTextBody`. Since the correct output code to produce depends upon the server provider, this also adds the flag `openapiStreamingImplementation`. 
There are more interpreters that this could support, but I figured that the 4 I've added are probably the most common and it should be easy to add support for others down the line.
I'd originally intended to support only Array[Byte] schemas, but I don't think that restriction is actually necessary; given that the implementing service will need to provide the serdes to/from the bytestream independently of the endpoint generation, and the Schema generation already seems to work pretty well, I figure it's probably fine just to use `Schema.binary[$theFormat]` and …
=> codegen: add streaming support for application/octet-stream contents

core/src/main/scala-3/sttp/tapir/generic/auto/SchemaMagnoliaDerivation.scala
https://github.com/softwaremill/tapir/pull/3970 does not actually resolve https://github.com/softwaremill/tapir/issues/3967 but this change does.
Scala 3's explicit nulls requires that `inProgress` be of type `mutable.Set[String]` (note the absence of ` | Null`) otherwise this causes client code to fail compilation.
By adding `.nn` after the null check we safely discard the ` | Null` half of the type, which allows `inProgress` to be the required non-null type.
=> Make inlined schema derivation null safe

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/SchemaGenerator.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala
Adding a bit of support for oneOfVariants. Where the previous code would've generated
```scala
.errorOut(jsonBody[MessageResponse].description("Bad Request").and(statusCode(sttp.model.StatusCode(400))))
.errorOut(jsonBody[MessageResponse].description("Forbidden").and(statusCode(sttp.model.StatusCode(403))))
.errorOut(jsonBody[MessageResponse].description("Not Found").and(statusCode(sttp.model.StatusCode(404))))
.errorOut(jsonBody[MessageResponse].description("Unauthorized").and(statusCode(sttp.model.StatusCode(401))))
```
we would now generate
```scala
.errorOut(oneOf(oneOfVariant(sttp.model.StatusCode(400), jsonBody[MessageResponse].description("Bad Request")), oneOfVariant(sttp.model.StatusCode(404), jsonBody[MessageResponse].description("Not Found")), …
```
=> codegen: limited support for oneOfVariant in responses

build.sbt, server/play29-server/src/main/scala/sttp/tapir/server/play/PlayRequestBody.scala
Back when we added the Play 2.9 module (#3313), the tests for Scala 3 failed and so it was removed.
Now, however, we'd like to move to Scala 3 and so this PR re-enables the Scala 3 build, fixing the dependency issues.
It seems like Scala 3 artifacts for Akka are pulled in, but akka-http-core was never published for Scala 3 and so these different binary versions clash.
Following the [official guide](https://www.playframework.com/documentation/2.9.x/ScalaAkka#Important-note-on-using-Akka-HTTP-10.5.0-or-newer-with-Scala-3), I excluded all the relevant native Scala 3 dependencies and replaced them with `for3Use2_13` ones.
=> Enable Scala 3 build for Play 2.9 Server

server/akka-grpc-server/src/main/scala/sttp/tapir/server/akkagrpc/AkkaGrpcRequestBody.scala, server/akka-grpc-server/src/main/scala/sttp/tapir/server/akkagrpc/AkkaGrpcToResponseBody.scala, server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaWebSockets.scala, server/pekko-grpc-server/src/main/scala/sttp/tapir/server/pekkogrpc/PekkoGrpcRequestBody.scala, server/pekko-grpc-server/src/main/scala/sttp/tapir/server/pekkogrpc/PekkoGrpcToResponseBody.scala, server/pekko-http-server/src/main/scala/sttp/tapir/server/pekkohttp/PekkoWebSockets.scala, server/play-server/src/main/scala/sttp/tapir/server/play/PlayRequestBody.scala, server/play29-server/src/main/scala/sttp/tapir/server/play/PlayRequestBody.scala
Pekko/Akka ByteString supports unsafe methods to create ByteStrings without cloning arrays or output the underlying array data (again without cloning). This is ok if no the other code that works with the arrays isn't modifying the array data.
Pekko 1.1 also has a ByteString.asInputStream method which is more efficient than getting an array and wrapping as ByteArrayInputStream.
=> use ByteString unsafe methods where it is ok

server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala, server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpInterpreter.scala
=> Generalise path templates when generating ZIO Http RoutePattern-s

client/sttp-client/src/main/scala/sttp/tapir/client/sttp/SttpClientInterpreter.scala
=> Add more detail to exceptions thrown in the client interpreter

client/sttp-client/src/main/scala/sttp/tapir/client/sttp/SttpClientInterpreter.scala
Reverts softwaremill/tapir#4085
=> Revert "Add more detail to exceptions thrown in the client interpreter"

json/pickler/src/main/scala/sttp/tapir/json/pickler/CreateDerivedEnumerationPickler.scala, json/pickler/src/test/scala/sttp/tapir/json/pickler/Fixtures.scala, json/pickler/src/test/scala/sttp/tapir/json/pickler/PicklerEnumTest.scala
=> Fix pickler deserialization when enum cases are not alphabetically sorted

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/SchemaGenerator.scala
This error message is a bit more useful
=> codegen: better errors if schemas not found during schema construction

server/akka-http-server/src/main/scala/sttp/tapir/server/akkahttp/AkkaBodyListener.scala, server/akka-http-server/src/test/scala/sttp/tapir/server/akkahttp/AkkaHttpServerTest.scala, server/pekko-http-server/src/main/scala/sttp/tapir/server/pekkohttp/PekkoBodyListener.scala, server/pekko-http-server/src/test/scala/sttp/tapir/server/pekkohttp/PekkoHttpServerTest.scala
Current implementation will throw IllegalArgumentException from HttpEntity.Default if `contentLenght` is 0 but `contentType` doesn't match `NoContentType`.
For example following entity breaks bodyListener: `Right(HttpEntity.Strict(application/json,0 bytes total))` 
Such entity could be created when one use Circe to generate body from simple Scala types like `None`
Original bug: https://github.com/softwaremill/tapir/issues/4138
=> Better handling of Empty entity in Akka an Pekko BodyListener.

.scalafix.conf, build.sbt, project/Versions.scala, server/core/src/main/scala/sttp/tapir/server/interceptor/metrics/MetricsEndpointInterceptor.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/NettyConfig.scala, server/netty-server/src/main/scala/sttp/tapir/server/netty/internal/NettyServerHandler.scala, server/netty-server/src/test/scala/sttp/tapir/server/netty/NettyFutureRequestTimeoutTests.scala, server/netty-server/src/test/scala/sttp/tapir/server/netty/NettyFutureServerTest.scala, server/netty-server/src/test/scala/sttp/tapir/server/netty/NettyRequestTimeoutTests.scala, server/netty-server/sync/src/main/scala/sttp/tapir/server/netty/sync/NettySyncServerOptions.scala, server/netty-server/sync/src/test/scala/sttp/tapir/server/netty/sync/NettySyncRequestTimeoutTests.scala, server/netty-server/sync/src/test/scala/sttp/tapir/server/netty/sync/NettySyncServerTest.scala
=> Fix cleanup in Netty handler after a request timeout

core/src/main/scala/sttp/tapir/macros/CreateDerivedEnumerationCodec.scala, examples/src/main/scala/sttp/tapir/examples/custom_types/enumQueryParameter.scala
=> Use correct validator when creating an enum codec so that error messages are rendered correctly

build.sbt, perf-tests/src/main/resources/64KB.json, perf-tests/src/main/scala/sttp/tapir/perf/apis/Endpoints.scala, perf-tests/src/test/scala/sttp/tapir/perf/Simulations.scala, server/netty-server/cats/src/main/scala/sttp/tapir/server/netty/cats/internal/Fs2StreamCompatible.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerBasicTests.scala
We've run into issues when decoding large JSON bodies using the netty cats backend. For some requests, decoding failed, due to parts of the input JSON missing.
The issue doesn't occur every time and is not deterministic, but we were able to track it down to this PR: https://github.com/softwaremill/tapir/pull/3489.
We believe that the issue is caused by the buffer sometimes being released to early, as the fs2 `Chunk` doesn't copy it and `httpContent.release()` sometimes trigger a deallocation by netty before the buffer is read into an array later. Our proposed fix is to explicitly copy the buffer into an array and only then call `release()`. 
We've added a new performance test for large JSON bodies that reliably shows the error. You should be able to compare the difference yourself by …
=> Copy HttpContent into array to avoid buffer being released too early

metrics/opentelemetry-metrics/src/main/scala/sttp/tapir/server/metrics/opentelemetry/OpenTelemetryMetrics.scala, metrics/opentelemetry-metrics/src/test/scala/sttp/tapir/server/metrics/opentelemetry/OpenTelemetryMetricsTest.scala, metrics/zio-metrics/src/main/scala/sttp/tapir/server/metrics/zio/ZioMetrics.scala, server/core/src/main/scala/sttp/tapir/server/metrics/Metric.scala
=> refactor: prometheus attributes format to otel attributes

openapi-codegen/cli/src/main/scala/sttp/tapir/codegen/GenScala.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/BasicGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenKeys.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenPlugin.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenTask.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedSchemas.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Adds a new `openapiGenerateEndpointTypes` setting (default false).
If 'true', we will generate type aliases for generated endpoint declarations (see changes to openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt).
If 'false' the only behavioural change should be that the LUB type is specified explicitly when generating `.errorOut(oneOf[LUB](oneOfVariant...` stuff (this is actually a little nicer usually -- it means the type will be `TheParentType` rather than `TheParentType with Product with Serializable`)
I would find having pre-defined type aliases for all the endpoint types to be extremely useful; locally I have a sourceGenerator step that replaces the `lazy val generatedEndpoints = List(...)` declaration on generated files with an HList …
=> codegen: Permit autogenerating types aliases for endpoints

server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/SttpMockServerClient.scala, server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/model.scala, server/sttp-mock-server/src/test/scala/sttp/tapir/server/mockserver/SttpMockServerClientSpec.scala
Mock Server expects the query parameters in a field called `queryStringParameters` instead of in the URL.
This PR follows the way headers are mapped to a MultiMapOpt to map query parameters to a `Map[String,List[String]]`
Closes #4219
=> Add correct handling of query parameters in SttpMockServerClient

serverless/aws/cdk-tests/src/main/scala/sttp/tapir/serverless/aws/cdk/tests/CdkTestLambdaHandler.scala, serverless/aws/cdk/src/test/scala/sttp/tapir/serverless/aws/cdk/IOLambdaHandlerV1Test.scala, serverless/aws/cdk/src/test/scala/sttp/tapir/serverless/aws/cdk/test/IOLambdaHandlerV1.scala, serverless/aws/examples/src/main/scalajvm/sttp/tapir/serverless/aws/examples/LambdaApiExample.scala, serverless/aws/examples/src/main/scalajvm/sttp/tapir/serverless/aws/examples/LambdaApiV1Example.scala, serverless/aws/lambda-cats-effect-tests/src/main/scala/sttp/tapir/serverless/aws/lambda/tests/IOLambdaHandlerV2.scala, serverless/aws/lambda-cats-effect/src/main/scala/sttp/tapir/serverless/aws/lambda/LambdaHandler.scala, serverless/aws/lambda-zio/src/main/scala/sttp/tapir/serverless/aws/ziolambda/ZioLambdaHandler.scala
*Why I did it?*
LambdaHandler had the hardcoded AwsServerOptions, so delivering
the custom server options was impossible.
*How I did it:*
LambdaHandler started to accept options by analogous to ZioLambdaHandler
Closes #4064
=> Add server options to AWS Lambda handler

build.sbt, examples/src/main/scala/sttp/tapir/examples/observability/Otel4sTracingExample.scala, project/Versions.scala
This example demonstrates how to implement distributed tracing in a Scala application using the 
[ otel4s library](https://github.com/typelevel/otel4s) . More info about oltel4s you may find [here](https://typelevel.org/otel4s/).
In order to collect and visualize traces, you can run Jaeger using Docker with the following command:
`docker run --name jaeger -e COLLECTOR_OTLP_ENABLED=true -p 16686:16686 -p 4317:4317 -p 4318:4318 jaegertracing/all-in-one:1.35`
Jaeger UI is available at http://localhost:16686. You can find the collected traces there.
=> Collecting traces example using otel4s.

build.sbt, examples/src/main/scala/sttp/tapir/examples/security/corsInterceptorVertxServer.scala, server/vertx-server/cats/src/main/scala/sttp/tapir/server/vertx/cats/VertxCatsServerInterpreter.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/VertxFutureServerInterpreter.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/interpreters/CommonServerInterpreter.scala, server/vertx-server/src/main/scala/sttp/tapir/server/vertx/routing/PathMapping.scala, server/vertx-server/zio/src/main/scala/sttp/tapir/server/vertx/zio/VertxZioServerInterpreter.scala
*Technical changes related to this issue:*
- registered options handler explicitly
*Technical changes NOT related to this issue:*
- added CORSInterceptor example for Vert.x server
Closes #3651
=> Fixed handling of CORS within Vert.x

.github/workflows/dependency-graph.yml
*Why I did it?*
GitHub dropped sbt from ubuntu-latest
https://github.com/sbt/setup-sbt?tab=readme-ov-file#december-2024
=> Fixed dependency graph

.github/dependabot.yaml
*Why I did it?*
In order to mark its PRs with `automarge` and
`dependency` labels
https://bit.ly/3DNpUUt
=> Adjusted dependabot's labels

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala
Fixes return LUB type for return type when generating endpoints with response objects without a common parent in scala 3 (was generating `Some(Foo) | Some(Bar)` instead of `Foo | Bar` :facepalm:)
=> codegen: fix oneOf types without common parent for scala 3

.github/workflows/ci.yml
*Why I did it?*
Dependabot automatically added `automerge` label,
so it didn't need `label` job as a precondition.
=> Fixed automerge dependabot's PRs

examples/src/main/scala/sttp/tapir/examples/security/csrfTokens.scala
Example added with endpoint secured with CSRF token
=> Example for use of CSRF token to secure endpoint

server/pekko-http-server/src/main/scala/sttp/tapir/server/pekkohttp/PekkoHttpServerInterpreter.scala, server/pekko-http-server/src/test/scala/sttp/tapir/server/pekkohttp/PekkoHttpServerTest.scala
Pekko [supports](https://pekko.apache.org/docs/pekko-http/current/common/http-model.html#registering-custom-status-codes) registering custom status codes with values >=600. Currently, if an endpoint returns such a status code, the Pekko interpreter will crash due to the call to the two argument version of `StatusCodes.custom`. This PR ~~adds possibility of registering Pekko custom status codes using `PekkoHttpServerOptions`~~ fixes that behavior by using the five parameter version of the method.
=> Add support in Pekko interpreter for status codes >=600

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedSchemas.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Use case for this is being able to migrate an endpoint that returns an 'Option[Foo]'. It seemed to me that adding `nullable: true` is the most natural way to declare this in openapi 3.0; although I'm aware that this was removed in openapi 3.1, so I've _also_ added support for declaring nullability with multiple types (i.e. `type: ['null', 'object']`). I'm not sure what long-term plans really are for version support, but figured it'd be better to support the feature for both 3.0 and 3.1 specifications
Edit: this might not really be what I want actually. Might want to be able to declare optionality by specifying that one status code (e.g. 204) doesn't return a body, and derive it for a oneOf...
=> codegen: Support top level nullables on json responses

docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/ToKeyedSchemas.scala, docs/openapi-docs/src/test/resources/coproduct/expected_coproduct_discriminator_enum.yml, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlCoproductTest.scala, docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/dtos/VerifyYamlCoproductTestData.scala
See https://softwaremill.community/t/json-schema-wrong-schema-for-enum/475
=> Fix OpenAPI schema generation when the discriminator field is an enum

doc/generator/sbt-openapi-codegen.md, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/SchemaGenerator.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenKeys.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/swagger.yaml
Very basic 'works in some places' support for 'free-form' json in codegen with circe (which already worked a bit) and jsoniter-scala (which didn't work anywhere at all). Not trying to be exhaustive of all cases just yet... Doesn't handle more specific but still generic forms such as free-form object.
Also updated some documentation, which I'd overlooked in previous prs
Since jsoniter-scala doesn't have an intermediate JSON repr of its own, support for generic json will require the jsoniter-scala-circe dependency
=> codegen: add generic json support for jsoniter-scala

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/swagger.yaml
Expands upon https://github.com/softwaremill/tapir/pull/4367. Adds tests and fixes type generation
=> codegen: better enum handling in query params

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/SchemaGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/ExpectedSchemas.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/swagger.yaml, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/swagger.yaml, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_scala3/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_scala3/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_scala3/project/plugins.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_scala3/swagger.yaml
Adds: 
- support in-line req object defns with simple fields for multipart/form-data
- support in-line req object defns with simple fields for application/json
- support multiple empty responses with no aligned defined response
- support ref aliases for lists
- support application/octet-stream in error position
Tests for all new support added for circe/zio/jsoniter (scala 2), and just circe (scala 3)
Probably the endpoint generator should be able to delegate to the class generator for inline defns, or else we should be pulling the inline defns out of the paths and passing it straight to the class generator at the root, but either refactor might be a little way out... I haven't encountered endpoints that nest inline definitions yet, but there shouldn't be a reason we can't support them in …
=> codegen: More content type support

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/swagger.yaml
Adds support for custom codecs to codegen. Everything in 'error' position is assumed to be 'eager' - if text/foo, then a utf8 string; if anything else, then a byte array. Everything in 'success' position is assumed to be a stream of bytes, whether text/ or not.
Without injection of custom codecs, this does not lend itself to content-type negotiation yet... I'll try to figure something out there since (as this pr probably makes clear) what I _really_ want is content-negotiation on different binary stream formats. Still, pr-ing as-is since it's new functionality even without that.
=> codegen: Support custom content types

project/Versions.scala, server/zio-http-server/src/test/scala/sttp/tapir/server/ziohttp/ZioHttpServerTest.scala
In tests, `route.runZIO` now asks for a Scope so it was just a matter of providing one in order to make the failing tests pass
=> Update ZIO HTTP to 3.1.0

build.sbt, doc/server/observability.md, project/Versions.scala, tracing/otel4s-tracing/src/main/scala/sttp/tapir/server/tracing/otel4s/Otel4sTracing.scala, tracing/otel4s-tracing/src/main/scala/sttp/tapir/server/tracing/otel4s/Otel4sTracingConfig.scala, tracing/otel4s-tracing/src/test/scala/sttp/tapir/server/tracing/otel4s/Otel4sTracingTest.scala
This PR adds support for OpenTelemetry integration with Tapir using the [otel4s](https://typelevel.org/otel4s/) library.
It adds a new module `tapir-otel4s-tracing` which is highly inspired by the existing `tapir-opentelemetry-tracing` module.
It fullfils the same testuite.
- `Otel4sTracing` - Main interceptor class that handles span creation and management
- `Otel4sTracingConfig` - Configuration class for customizing span names and attributes
- Proper error handling and status code reporting
- Support for W3C context propagation
This closes https://github.com/softwaremill/tapir/issues/4427.
Due [to](https://typelevel.org/otel4s/oteljava/tracing-context-propagation.html):
> Cats Effect 3.6.0 introduced a new method of fiber context tracking, which can be integrated almost seamlessly with …
=> Adds support for otel4s server tracing

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/swagger.yaml
Not supporting recursion down to enums defined on further-inlined objects here. Just at top level of the schema. Previously would've looked something like `{"type":"A"}` instead of `"A"`
=> Codegen: serialize inline enums on schema definitions as strings when using jsoniter

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSecuritySchemeType.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/util/MapUtils.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/src/test/scala/BinaryEndpoints.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Supports oauth2 flow security schema declarations. Also supports multiple security declarations on an endpoint, as long as they all reasolve to bearer auth (which is not enough to support the petstore yaml yet because that declares api_key and oauth2 security on the same endpoint, but still deals with some real-world cases such as defining both oauth2 and bearer auth schemas on the same endpoint).
Doesn't yet do anything with scopes. Not sure what would be useful there. What might be cool would be some sort of static typing on the security token so you had a `case class Token[Scope1 & Scope2](value: String)` and then require the type param to be a subset of required scopes? Could also be a nightmare. I haven't really played with the idea yet though and I'm deeming it out-of-scope (haha. …
=> Codegen: oauth2 security schemas support

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiComponent.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiReqResp.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/ModelParserSpec.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Supports requestBody and response definitions in the 'components' section of openapi yaml.
Nothing very clever here, there are probably more map lookups than there could be if we had an earlier single-pass resolve step, but the refs are still resolved relatively early and I can't envisage this ever producing particular egregious performance characteristics
=> codegen: support components/requestBodies and components/responses

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiReqResp.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Support defining 'headers' on responses.
Depends on https://github.com/softwaremill/tapir/pull/4457, since that started to parse the response headers from the openapi yaml in some places.
Doesn't handle the situation where differing headers are defined for multiple response codes in same 'bucket' (i.e. multiple error, or multiple success, status codes). I _think_ that in order to be able to do that, we'd need to introduce something a bit more elaborate to the endpoint defns... possibly something like
```scala
sealed trait MyEndpointNameResponseType
case class MyEndpointNameResponse200(body: SomeType, headerName1: String) extends MyEndpointNameResponseType
case class MyEndpointNameResponse201(headerName2: String) extends MyEndpointNameResponseType
```
so that we could get an appropriate …
=> Codegen: Support response headers

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_scala3/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_scala3/swagger.yaml
The codegen was treating all security schemas as having a type of `String`, but `auth.basic[UsernamePassword]()` does not. This fixes type generation when `openapiGenerateEndpointTypes := true`
Shouldn't imagine this will have any conflicts with my other pr, so can go in first
=> codegen: fix type declaration for basic auth security

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_scala3/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_scala3/swagger.yaml, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/petstore/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/petstore/swagger.yaml
Follow-up to https://github.com/softwaremill/tapir/pull/4464
With this, an unmodified petstore.yml will generate some pretty reasonable, usable code.
Some things are still missing -- we do nothing with security scopes, I've just realised we never '.name(..)' our endpoints in the generated code, we should support x-www-form-urlencoded directly with the tapir built-in codec, there's nothing generated to reify the 'servers' and 'infos' fields, ... but we shouldn't throw errors or generate unusable code
=> codegen: Add support for multiple security declarations on an endpoint ('full' petstore support)

doc/generator/sbt-openapi-codegen.md, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/GenerationDirectives.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Adds 'x-tapir-codegen-directives' with corresponding value 'json-body-as-string', for when you absolutely have to treat the json on a particular endpoint as a String. I'm introducing it as a flagset rather than a single extension with a boolean since it feels more extensible and I have other extensions in mind for future prs... (I think in particular being able to specify whether an endpoint use streaming or eager content would be a useful flag)
Sometimes you just really need `stringJsonBody` (e.g. if you absolutely need to satisfy the requirement that some data be saved and retrieved in char-for-char identical formats, even if invalid json).
The only sane way I could see to support this was to add a new extension. I've chosen to enable it at the operation ('path+method') level; perhaps …
=> codegen: Add support for generating stringJsonBody

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/SecurityGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/util/ErrUtils.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Supports declaring 'security' at the top level of the openapi doc. This will be applied to all routes, unless a route explicitly overrides the auth requirement.
This also sanitises the parsing and security declaration somewhat; previously, we were performing completely illegal transformations on the security requirement, and would have generated invalid code in the case where multiple schemes were declared on same security requirement. We will now throw an error instead.
=> codegen: Support top-level security declarations

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/SecurityGenerator.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/petstore/Expected.scala.txt
Also supports 'optional' Auth if declarations contains an empty map
Will just transform inputs to the first matching declaration if multiple declarations support multiple security params, and a superset of both of them is present in the request. That could presumably be improved, if required, by refining the match implementations a bit so that supersets weren't matched on multi-declaration sites, but the extra complexity hardly seems worth it...
=> codegen: support multiple security schemes on same declaration

doc/generator/sbt-openapi-codegen.md, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/BasicGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/GenerationDirectives.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Adds a new custom extension 'x-tapir-codegen-security-path-prefixes', for when your auth logic wants to know some prefix of the path (e.g. for validating that a jwt contains perms for the segment)
The path security input will be prepended after any other security inputs are declared and mapped, so that the security path will appear before other security inputs in the signature. This matches the non-security inputs, where path is also first.
There may be a neater way to do this that I've missed, but my understanding is that security inputs are _always_ parsed before non-security input, so if you want to know about the path in the security logic this is the only approach that works...
=> codegen: Support security path declarations

core/src/main/scala/sttp/tapir/Codec.scala
`CookieWithMeta` also pulls in `scala-java-time`, so these two `Codec`s have also been made lazy as per #4500. I've confirmed this is the minimal set to avoid the dependency entirely, saving a full 1.12MB of bundle size (a further ~0.4MB can be saved on other codecs)
=> Fix: bundle size for JS

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Fixes placement of 'description' field on endpoint with a header but no body, and with no other response status codes of same type. Before, would occasionally produce code than can't compile. E.g. would generate
```scala
.out(statusCode(sttp.model.StatusCode(302)).and(header[Option[String]]("foo").description("bar.")).description(""))
```
which will fail to compile with `value description is not a member of sttp.tapir.EndpointOutput[Option[String]]`
=> codegen: fix placement of 'description' call in edgecase

doc/endpoint/static.md, files/src/main/scalajvm/sttp/tapir/files/TapirStaticContentEndpoints.scala, generated-doc/out/endpoint/static.md
Fixes #4529: adds `extraHeaders` to each of the server endpoint descriptions (defaulting to `Nil`), which can then be used to do things like cache control.
=> feat(files): added extraHeaders to server endpoints for files/resources

doc/generator/sbt-openapi-codegen.md, openapi-codegen/cli/src/main/scala/sttp/tapir/codegen/GenScala.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EndpointGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/EnumGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/RootGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/SchemaGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/SecurityGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ServersGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/XmlSerdeGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/RootGeneratorSpec.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenTask.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedSchemas.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
Supports allOf, a bit, should permit reusing parameter set declarations between models.
Only objects and refs to objects are supported. I think that's the only usecase for allOf until validation is implemented anyway so that sounds fine to me.
Errors seem sensible enough in cases where incompatible fields are declared in the members -- e.g. trying to use two different schemas in an allOf with different properties with the same name and different types will give something like
`[error] java.lang.IllegalStateException: Non-matching conflicting fields found on allOf declaration. For HasFooBarBazQuux.bar found both OpenapiSchemaString(false) and OpenapiSchemaInt(false)`
There may be other use-cases for allOf but I'm keeping this quite limited in scope
I've also updated the doc comments …
=> codegen: support allOf

tracing/opentelemetry-tracing/src/main/scala/sttp/tapir/server/tracing/opentelemetry/OpenTelemetryTracing.scala, tracing/opentelemetry-tracing/src/test/scala/sttp/tapir/server/tracing/opentelemetry/OpenTelemetryTracingTest.scala, tracing/otel4s-tracing/src/main/scala/sttp/tapir/server/tracing/otel4s/Otel4sTracing.scala, tracing/otel4s-tracing/src/test/scala/sttp/tapir/server/tracing/otel4s/Otel4sTracingTest.scala
Currently, all spans created through requests are set with the `span kind` as `internal`. I'm not sure if this is the correct behavior, it should be set to `server`. This happens because the default value for the `span kind` is set to `internal`.
=> Add server span kind for otel4s tracing

doc/generator/sbt-openapi-codegen.md, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ValidationGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/DefaultValueRenderer.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/ExpectedSchemas.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip-zio/swagger.yaml, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/ExpectedValidators.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/src/test/scala/ValidationSpec.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/swagger.yaml
Follow-up to https://github.com/softwaremill/tapir/pull/4564. Supports `uniqueItems` by declaring the type as a Set rather than a Seq, when the value is true.
=> codegen: Support uniqueItems on array defns

build.sbt, doc/generator/sbt-openapi-codegen.md, openapi-codegen/cli/src/main/scala/sttp/tapir/codegen/GenScala.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/RootGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/util/MapUtils.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/RootGeneratorSpec.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenKeys.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenPlugin.scala, openapi-codegen/sbt-plugin/src/main/scala/sttp/tapir/sbt/OpenapiCodegenTask.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/build.sbt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/ExpectedJsonSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/build.sbt
Mitigates flakiness in macro expansion during compilation (cf [this issue](https://github.com/plokhotnyuk/jsoniter-scala/issues/1279))
Enabling the newer codegen with an option (default can be changed at some point sufficiently-far-in-the-future) because I don't want to break things for those as don't need this.
=> codegen: Add support for custom jsoniter-scala serde config

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ClassDefinitionGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/ValidationGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/DefaultValueRenderer.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/src/test/scala/ValidationSpec.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/swagger.yaml
A use-case for allOf that I'd missed is supporting default values on fields whose type are declared by 'ref's. In fact, there are really the only two ways to do that that works with openapi 3.0:
```yaml
allOf:
- $ref: ...someRef
- default: defaultValue
```
and
```yaml
allOf:
- $ref: ...someRef
default: defaultValue
```
since sibling fields to $ref are ignored.
I'm only supporting the latter form here, and _not_ attempting to support other usages of allOf outside of top-level usage in components/schemas definitions (which are already largely handled). This is really a very specific case, and more general handling would be _far_ more involved
(github's default diff on this looks really weird, it makes more sense with 'hide whitespace' enabled)
=> codegen: support singleton allOf for default on refs

openapi-codegen/core/src/main/scala/sttp/tapir/codegen/JsonSerdeGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/SchemaGenerator.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiModels.scala, openapi-codegen/core/src/main/scala/sttp/tapir/codegen/openapi/models/OpenapiSchemaType.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/ClassDefinitionGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/EndpointGeneratorSpec.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/TestHelpers.scala, openapi-codegen/core/src/test/scala/sttp/tapir/codegen/models/SchemaParserSpec.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/ExpectedXmlSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/src/test/scala/JsonRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter/src/test/scala/XmlRoundtrip.scala, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/oneOf-json-roundtrip_jsoniter_scala3/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/petstore/Expected.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/petstore/ExpectedXmlSerdes.scala.txt, openapi-codegen/sbt-plugin/src/sbt-test/sbt-openapi-codegen/petstore/src/test/scala/XmlRoundtrip.scala
The non-deterministic ordering of the field declarations in object schemas is annoying, and can randomly break code that depends on it being consistent (e.g. case-class pattern matching, or positional case class construction). The sanest consistent field ordering is the one declared in the openapi yaml. This pr replaces usage of Map with LinkedHashMap, which retains the initial ordering of fields as declared in the schema.
Where 'allOf' is involved, fields will be declared in the order in which they first appear in the flattened property list of all component schemas.
Endpoint ordering has also been non-deterministic, which can also be problematic (although it's probably less of an issue for most). That has a similar resolution - to read the paths into a LinkedHashMap rather than a Map, …
=> codegen: make generated class field & endpoint decl orders consistent with api declarations

files/src/main/scalajvm/sttp/tapir/files/Files.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerFilesTests.scala
Closes #4715
It seems that the call to `.getRealPath()` was unnecessary, as later in `resolveSystemPathUrl` there's also a `resolved.toRealPath(LinkOption.NOFOLLOW_LINKS)` call. This is done after checking, if the file exists. That way, we can simplify the logic and remove one `MonadError.blocking` call.
=> Properly return a 404 when trying to get a non-existent single file

server/armeria-server/cats/src/test/scala/sttp/tapir/server/armeria/cats/ArmeriaCatsServerTest.scala, server/armeria-server/src/main/scala/sttp/tapir/server/armeria/ArmeriaRequestBody.scala, server/armeria-server/src/test/scala/sttp/tapir/server/armeria/ArmeriaFutureServerTest.scala, server/armeria-server/zio/src/test/scala/sttp/tapir/server/armeria/zio/ArmeriaZioServerTest.scala, server/http4s-server/src/main/scala/sttp/tapir/server/http4s/Http4sRequestBody.scala, server/jdkhttp-server/src/test/scala/sttp/tapir/server/jdkhttp/JdkHttpServerTest.scala, server/tests/src/main/scala/sttp/tapir/server/tests/ServerMultipartTests.scala, tests/src/main/scalajs/sttp/tapir/tests/TestUtilExtensions.scala, tests/src/main/scalajvm/sttp/tapir/tests/TestUtilExtensions.scala, tests/src/main/scalanative/sttp/tapir/tests/TestUtilExtensions.scala
Closes #4730 
Not supported in Armeria & JDK-builtin server interpreters
=> Fix filename decoding in http4s multipart handling

perf-tests/README.md, server/netty-server/sync/src/main/scala/sttp/tapir/server/netty/sync/NettySyncServer.scala, server/netty-server/sync/src/test/scala/sttp/tapir/server/netty/sync/NettySyncTestServerInterpreter.scala, server/netty-server/sync/src/test/scala/sttp/tapir/server/netty/sync/perf/NettySyncServerRunner.scala
=> Use the current Ox scope when running a Netty sync-server to create threads (forks)

build.sbt
- https://github.com/openjdk/jdk/commit/4338f527aa81350e3636dcfbcd2eb17ddaad3914 
- https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/net/URL.html#%3Cinit%3E(java.lang.String) 
- https://bugs.openjdk.org/browse/JDK-8295949
=> avoid deprecated `java.net.URL` constructor
